
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `dProduct` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model dProduct
 * 
 */
export type dProductModel = runtime.Types.Result.DefaultSelection<Prisma.$dProductPayload>

export type AggregateDProduct = {
  _count: DProductCountAggregateOutputType | null
  _avg: DProductAvgAggregateOutputType | null
  _sum: DProductSumAggregateOutputType | null
  _min: DProductMinAggregateOutputType | null
  _max: DProductMaxAggregateOutputType | null
}

export type DProductAvgAggregateOutputType = {
  Identifier: number | null
  CreationID: number | null
  MaintenanceID: number | null
  BreakNumber: runtime.Decimal | null
  SizeNumber: runtime.Decimal | null
  SizeQuantity: runtime.Decimal | null
  IdentStorage: number | null
  ExternalID: number | null
}

export type DProductSumAggregateOutputType = {
  Identifier: number | null
  CreationID: number | null
  MaintenanceID: number | null
  BreakNumber: runtime.Decimal | null
  SizeNumber: runtime.Decimal | null
  SizeQuantity: runtime.Decimal | null
  IdentStorage: number | null
  ExternalID: number | null
}

export type DProductMinAggregateOutputType = {
  Identifier: number | null
  Status: string | null
  Creation: Date | null
  CreationID: number | null
  Maintenance: Date | null
  MaintenanceID: number | null
  Product: string | null
  ItemCode: string | null
  ProductKey: string | null
  PropertyGroup: string | null
  Description: string | null
  Description2: string | null
  Description3: string | null
  UPC: string | null
  GTIN: string | null
  GS1: string | null
  PLU: string | null
  IMP: string | null
  NAMP: string | null
  SeasonType: string | null
  PageTitle: string | null
  StockLabel: string | null
  PalletLabel: string | null
  Picked: boolean | null
  ReqRebox: string | null
  HoldCode: string | null
  Plants: string | null
  Class: string | null
  UOM: string | null
  PackUnit: string | null
  BreakUnit: string | null
  BreakNumber: runtime.Decimal | null
  SizeUnit: string | null
  SizeNumber: runtime.Decimal | null
  SizeQuantity: runtime.Decimal | null
  ERPExempt: boolean | null
  IdentStorage: number | null
  ExternalID: number | null
}

export type DProductMaxAggregateOutputType = {
  Identifier: number | null
  Status: string | null
  Creation: Date | null
  CreationID: number | null
  Maintenance: Date | null
  MaintenanceID: number | null
  Product: string | null
  ItemCode: string | null
  ProductKey: string | null
  PropertyGroup: string | null
  Description: string | null
  Description2: string | null
  Description3: string | null
  UPC: string | null
  GTIN: string | null
  GS1: string | null
  PLU: string | null
  IMP: string | null
  NAMP: string | null
  SeasonType: string | null
  PageTitle: string | null
  StockLabel: string | null
  PalletLabel: string | null
  Picked: boolean | null
  ReqRebox: string | null
  HoldCode: string | null
  Plants: string | null
  Class: string | null
  UOM: string | null
  PackUnit: string | null
  BreakUnit: string | null
  BreakNumber: runtime.Decimal | null
  SizeUnit: string | null
  SizeNumber: runtime.Decimal | null
  SizeQuantity: runtime.Decimal | null
  ERPExempt: boolean | null
  IdentStorage: number | null
  ExternalID: number | null
}

export type DProductCountAggregateOutputType = {
  Identifier: number
  Status: number
  Creation: number
  CreationID: number
  Maintenance: number
  MaintenanceID: number
  Product: number
  ItemCode: number
  ProductKey: number
  PropertyGroup: number
  Description: number
  Description2: number
  Description3: number
  UPC: number
  GTIN: number
  GS1: number
  PLU: number
  IMP: number
  NAMP: number
  SeasonType: number
  PageTitle: number
  StockLabel: number
  PalletLabel: number
  Picked: number
  ReqRebox: number
  HoldCode: number
  Plants: number
  Class: number
  UOM: number
  PackUnit: number
  BreakUnit: number
  BreakNumber: number
  SizeUnit: number
  SizeNumber: number
  SizeQuantity: number
  ERPExempt: number
  IdentStorage: number
  ExternalID: number
  _all: number
}


export type DProductAvgAggregateInputType = {
  Identifier?: true
  CreationID?: true
  MaintenanceID?: true
  BreakNumber?: true
  SizeNumber?: true
  SizeQuantity?: true
  IdentStorage?: true
  ExternalID?: true
}

export type DProductSumAggregateInputType = {
  Identifier?: true
  CreationID?: true
  MaintenanceID?: true
  BreakNumber?: true
  SizeNumber?: true
  SizeQuantity?: true
  IdentStorage?: true
  ExternalID?: true
}

export type DProductMinAggregateInputType = {
  Identifier?: true
  Status?: true
  Creation?: true
  CreationID?: true
  Maintenance?: true
  MaintenanceID?: true
  Product?: true
  ItemCode?: true
  ProductKey?: true
  PropertyGroup?: true
  Description?: true
  Description2?: true
  Description3?: true
  UPC?: true
  GTIN?: true
  GS1?: true
  PLU?: true
  IMP?: true
  NAMP?: true
  SeasonType?: true
  PageTitle?: true
  StockLabel?: true
  PalletLabel?: true
  Picked?: true
  ReqRebox?: true
  HoldCode?: true
  Plants?: true
  Class?: true
  UOM?: true
  PackUnit?: true
  BreakUnit?: true
  BreakNumber?: true
  SizeUnit?: true
  SizeNumber?: true
  SizeQuantity?: true
  ERPExempt?: true
  IdentStorage?: true
  ExternalID?: true
}

export type DProductMaxAggregateInputType = {
  Identifier?: true
  Status?: true
  Creation?: true
  CreationID?: true
  Maintenance?: true
  MaintenanceID?: true
  Product?: true
  ItemCode?: true
  ProductKey?: true
  PropertyGroup?: true
  Description?: true
  Description2?: true
  Description3?: true
  UPC?: true
  GTIN?: true
  GS1?: true
  PLU?: true
  IMP?: true
  NAMP?: true
  SeasonType?: true
  PageTitle?: true
  StockLabel?: true
  PalletLabel?: true
  Picked?: true
  ReqRebox?: true
  HoldCode?: true
  Plants?: true
  Class?: true
  UOM?: true
  PackUnit?: true
  BreakUnit?: true
  BreakNumber?: true
  SizeUnit?: true
  SizeNumber?: true
  SizeQuantity?: true
  ERPExempt?: true
  IdentStorage?: true
  ExternalID?: true
}

export type DProductCountAggregateInputType = {
  Identifier?: true
  Status?: true
  Creation?: true
  CreationID?: true
  Maintenance?: true
  MaintenanceID?: true
  Product?: true
  ItemCode?: true
  ProductKey?: true
  PropertyGroup?: true
  Description?: true
  Description2?: true
  Description3?: true
  UPC?: true
  GTIN?: true
  GS1?: true
  PLU?: true
  IMP?: true
  NAMP?: true
  SeasonType?: true
  PageTitle?: true
  StockLabel?: true
  PalletLabel?: true
  Picked?: true
  ReqRebox?: true
  HoldCode?: true
  Plants?: true
  Class?: true
  UOM?: true
  PackUnit?: true
  BreakUnit?: true
  BreakNumber?: true
  SizeUnit?: true
  SizeNumber?: true
  SizeQuantity?: true
  ERPExempt?: true
  IdentStorage?: true
  ExternalID?: true
  _all?: true
}

export type DProductAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which dProduct to aggregate.
   */
  where?: Prisma.dProductWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of dProducts to fetch.
   */
  orderBy?: Prisma.dProductOrderByWithRelationInput | Prisma.dProductOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.dProductWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` dProducts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` dProducts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned dProducts
  **/
  _count?: true | DProductCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: DProductAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: DProductSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DProductMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DProductMaxAggregateInputType
}

export type GetDProductAggregateType<T extends DProductAggregateArgs> = {
      [P in keyof T & keyof AggregateDProduct]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDProduct[P]>
    : Prisma.GetScalarType<T[P], AggregateDProduct[P]>
}




export type dProductGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.dProductWhereInput
  orderBy?: Prisma.dProductOrderByWithAggregationInput | Prisma.dProductOrderByWithAggregationInput[]
  by: Prisma.DProductScalarFieldEnum[] | Prisma.DProductScalarFieldEnum
  having?: Prisma.dProductScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DProductCountAggregateInputType | true
  _avg?: DProductAvgAggregateInputType
  _sum?: DProductSumAggregateInputType
  _min?: DProductMinAggregateInputType
  _max?: DProductMaxAggregateInputType
}

export type DProductGroupByOutputType = {
  Identifier: number
  Status: string
  Creation: Date
  CreationID: number
  Maintenance: Date
  MaintenanceID: number
  Product: string
  ItemCode: string | null
  ProductKey: string | null
  PropertyGroup: string | null
  Description: string | null
  Description2: string | null
  Description3: string | null
  UPC: string | null
  GTIN: string | null
  GS1: string | null
  PLU: string | null
  IMP: string | null
  NAMP: string | null
  SeasonType: string | null
  PageTitle: string | null
  StockLabel: string | null
  PalletLabel: string | null
  Picked: boolean
  ReqRebox: string
  HoldCode: string
  Plants: string | null
  Class: string | null
  UOM: string | null
  PackUnit: string | null
  BreakUnit: string | null
  BreakNumber: runtime.Decimal | null
  SizeUnit: string | null
  SizeNumber: runtime.Decimal | null
  SizeQuantity: runtime.Decimal | null
  ERPExempt: boolean
  IdentStorage: number
  ExternalID: number | null
  _count: DProductCountAggregateOutputType | null
  _avg: DProductAvgAggregateOutputType | null
  _sum: DProductSumAggregateOutputType | null
  _min: DProductMinAggregateOutputType | null
  _max: DProductMaxAggregateOutputType | null
}

type GetDProductGroupByPayload<T extends dProductGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DProductGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DProductGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DProductGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DProductGroupByOutputType[P]>
      }
    >
  >



export type dProductWhereInput = {
  AND?: Prisma.dProductWhereInput | Prisma.dProductWhereInput[]
  OR?: Prisma.dProductWhereInput[]
  NOT?: Prisma.dProductWhereInput | Prisma.dProductWhereInput[]
  Identifier?: Prisma.IntFilter<"dProduct"> | number
  Status?: Prisma.StringFilter<"dProduct"> | string
  Creation?: Prisma.DateTimeFilter<"dProduct"> | Date | string
  CreationID?: Prisma.IntFilter<"dProduct"> | number
  Maintenance?: Prisma.DateTimeFilter<"dProduct"> | Date | string
  MaintenanceID?: Prisma.IntFilter<"dProduct"> | number
  Product?: Prisma.StringFilter<"dProduct"> | string
  ItemCode?: Prisma.StringNullableFilter<"dProduct"> | string | null
  ProductKey?: Prisma.StringNullableFilter<"dProduct"> | string | null
  PropertyGroup?: Prisma.StringNullableFilter<"dProduct"> | string | null
  Description?: Prisma.StringNullableFilter<"dProduct"> | string | null
  Description2?: Prisma.StringNullableFilter<"dProduct"> | string | null
  Description3?: Prisma.StringNullableFilter<"dProduct"> | string | null
  UPC?: Prisma.StringNullableFilter<"dProduct"> | string | null
  GTIN?: Prisma.StringNullableFilter<"dProduct"> | string | null
  GS1?: Prisma.StringNullableFilter<"dProduct"> | string | null
  PLU?: Prisma.StringNullableFilter<"dProduct"> | string | null
  IMP?: Prisma.StringNullableFilter<"dProduct"> | string | null
  NAMP?: Prisma.StringNullableFilter<"dProduct"> | string | null
  SeasonType?: Prisma.StringNullableFilter<"dProduct"> | string | null
  PageTitle?: Prisma.StringNullableFilter<"dProduct"> | string | null
  StockLabel?: Prisma.StringNullableFilter<"dProduct"> | string | null
  PalletLabel?: Prisma.StringNullableFilter<"dProduct"> | string | null
  Picked?: Prisma.BoolFilter<"dProduct"> | boolean
  ReqRebox?: Prisma.StringFilter<"dProduct"> | string
  HoldCode?: Prisma.StringFilter<"dProduct"> | string
  Plants?: Prisma.StringNullableFilter<"dProduct"> | string | null
  Class?: Prisma.StringNullableFilter<"dProduct"> | string | null
  UOM?: Prisma.StringNullableFilter<"dProduct"> | string | null
  PackUnit?: Prisma.StringNullableFilter<"dProduct"> | string | null
  BreakUnit?: Prisma.StringNullableFilter<"dProduct"> | string | null
  BreakNumber?: Prisma.DecimalNullableFilter<"dProduct"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  SizeUnit?: Prisma.StringNullableFilter<"dProduct"> | string | null
  SizeNumber?: Prisma.DecimalNullableFilter<"dProduct"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  SizeQuantity?: Prisma.DecimalNullableFilter<"dProduct"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  ERPExempt?: Prisma.BoolFilter<"dProduct"> | boolean
  IdentStorage?: Prisma.IntFilter<"dProduct"> | number
  ExternalID?: Prisma.IntNullableFilter<"dProduct"> | number | null
}

export type dProductOrderByWithRelationInput = {
  Identifier?: Prisma.SortOrder
  Status?: Prisma.SortOrder
  Creation?: Prisma.SortOrder
  CreationID?: Prisma.SortOrder
  Maintenance?: Prisma.SortOrder
  MaintenanceID?: Prisma.SortOrder
  Product?: Prisma.SortOrder
  ItemCode?: Prisma.SortOrderInput | Prisma.SortOrder
  ProductKey?: Prisma.SortOrderInput | Prisma.SortOrder
  PropertyGroup?: Prisma.SortOrderInput | Prisma.SortOrder
  Description?: Prisma.SortOrderInput | Prisma.SortOrder
  Description2?: Prisma.SortOrderInput | Prisma.SortOrder
  Description3?: Prisma.SortOrderInput | Prisma.SortOrder
  UPC?: Prisma.SortOrderInput | Prisma.SortOrder
  GTIN?: Prisma.SortOrderInput | Prisma.SortOrder
  GS1?: Prisma.SortOrderInput | Prisma.SortOrder
  PLU?: Prisma.SortOrderInput | Prisma.SortOrder
  IMP?: Prisma.SortOrderInput | Prisma.SortOrder
  NAMP?: Prisma.SortOrderInput | Prisma.SortOrder
  SeasonType?: Prisma.SortOrderInput | Prisma.SortOrder
  PageTitle?: Prisma.SortOrderInput | Prisma.SortOrder
  StockLabel?: Prisma.SortOrderInput | Prisma.SortOrder
  PalletLabel?: Prisma.SortOrderInput | Prisma.SortOrder
  Picked?: Prisma.SortOrder
  ReqRebox?: Prisma.SortOrder
  HoldCode?: Prisma.SortOrder
  Plants?: Prisma.SortOrderInput | Prisma.SortOrder
  Class?: Prisma.SortOrderInput | Prisma.SortOrder
  UOM?: Prisma.SortOrderInput | Prisma.SortOrder
  PackUnit?: Prisma.SortOrderInput | Prisma.SortOrder
  BreakUnit?: Prisma.SortOrderInput | Prisma.SortOrder
  BreakNumber?: Prisma.SortOrderInput | Prisma.SortOrder
  SizeUnit?: Prisma.SortOrderInput | Prisma.SortOrder
  SizeNumber?: Prisma.SortOrderInput | Prisma.SortOrder
  SizeQuantity?: Prisma.SortOrderInput | Prisma.SortOrder
  ERPExempt?: Prisma.SortOrder
  IdentStorage?: Prisma.SortOrder
  ExternalID?: Prisma.SortOrderInput | Prisma.SortOrder
}

export type dProductWhereUniqueInput = Prisma.AtLeast<{
  Identifier?: number
  ProductKey?: string
  AND?: Prisma.dProductWhereInput | Prisma.dProductWhereInput[]
  OR?: Prisma.dProductWhereInput[]
  NOT?: Prisma.dProductWhereInput | Prisma.dProductWhereInput[]
  Status?: Prisma.StringFilter<"dProduct"> | string
  Creation?: Prisma.DateTimeFilter<"dProduct"> | Date | string
  CreationID?: Prisma.IntFilter<"dProduct"> | number
  Maintenance?: Prisma.DateTimeFilter<"dProduct"> | Date | string
  MaintenanceID?: Prisma.IntFilter<"dProduct"> | number
  Product?: Prisma.StringFilter<"dProduct"> | string
  ItemCode?: Prisma.StringNullableFilter<"dProduct"> | string | null
  PropertyGroup?: Prisma.StringNullableFilter<"dProduct"> | string | null
  Description?: Prisma.StringNullableFilter<"dProduct"> | string | null
  Description2?: Prisma.StringNullableFilter<"dProduct"> | string | null
  Description3?: Prisma.StringNullableFilter<"dProduct"> | string | null
  UPC?: Prisma.StringNullableFilter<"dProduct"> | string | null
  GTIN?: Prisma.StringNullableFilter<"dProduct"> | string | null
  GS1?: Prisma.StringNullableFilter<"dProduct"> | string | null
  PLU?: Prisma.StringNullableFilter<"dProduct"> | string | null
  IMP?: Prisma.StringNullableFilter<"dProduct"> | string | null
  NAMP?: Prisma.StringNullableFilter<"dProduct"> | string | null
  SeasonType?: Prisma.StringNullableFilter<"dProduct"> | string | null
  PageTitle?: Prisma.StringNullableFilter<"dProduct"> | string | null
  StockLabel?: Prisma.StringNullableFilter<"dProduct"> | string | null
  PalletLabel?: Prisma.StringNullableFilter<"dProduct"> | string | null
  Picked?: Prisma.BoolFilter<"dProduct"> | boolean
  ReqRebox?: Prisma.StringFilter<"dProduct"> | string
  HoldCode?: Prisma.StringFilter<"dProduct"> | string
  Plants?: Prisma.StringNullableFilter<"dProduct"> | string | null
  Class?: Prisma.StringNullableFilter<"dProduct"> | string | null
  UOM?: Prisma.StringNullableFilter<"dProduct"> | string | null
  PackUnit?: Prisma.StringNullableFilter<"dProduct"> | string | null
  BreakUnit?: Prisma.StringNullableFilter<"dProduct"> | string | null
  BreakNumber?: Prisma.DecimalNullableFilter<"dProduct"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  SizeUnit?: Prisma.StringNullableFilter<"dProduct"> | string | null
  SizeNumber?: Prisma.DecimalNullableFilter<"dProduct"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  SizeQuantity?: Prisma.DecimalNullableFilter<"dProduct"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  ERPExempt?: Prisma.BoolFilter<"dProduct"> | boolean
  IdentStorage?: Prisma.IntFilter<"dProduct"> | number
  ExternalID?: Prisma.IntNullableFilter<"dProduct"> | number | null
}, "Identifier" | "ProductKey">

export type dProductOrderByWithAggregationInput = {
  Identifier?: Prisma.SortOrder
  Status?: Prisma.SortOrder
  Creation?: Prisma.SortOrder
  CreationID?: Prisma.SortOrder
  Maintenance?: Prisma.SortOrder
  MaintenanceID?: Prisma.SortOrder
  Product?: Prisma.SortOrder
  ItemCode?: Prisma.SortOrderInput | Prisma.SortOrder
  ProductKey?: Prisma.SortOrderInput | Prisma.SortOrder
  PropertyGroup?: Prisma.SortOrderInput | Prisma.SortOrder
  Description?: Prisma.SortOrderInput | Prisma.SortOrder
  Description2?: Prisma.SortOrderInput | Prisma.SortOrder
  Description3?: Prisma.SortOrderInput | Prisma.SortOrder
  UPC?: Prisma.SortOrderInput | Prisma.SortOrder
  GTIN?: Prisma.SortOrderInput | Prisma.SortOrder
  GS1?: Prisma.SortOrderInput | Prisma.SortOrder
  PLU?: Prisma.SortOrderInput | Prisma.SortOrder
  IMP?: Prisma.SortOrderInput | Prisma.SortOrder
  NAMP?: Prisma.SortOrderInput | Prisma.SortOrder
  SeasonType?: Prisma.SortOrderInput | Prisma.SortOrder
  PageTitle?: Prisma.SortOrderInput | Prisma.SortOrder
  StockLabel?: Prisma.SortOrderInput | Prisma.SortOrder
  PalletLabel?: Prisma.SortOrderInput | Prisma.SortOrder
  Picked?: Prisma.SortOrder
  ReqRebox?: Prisma.SortOrder
  HoldCode?: Prisma.SortOrder
  Plants?: Prisma.SortOrderInput | Prisma.SortOrder
  Class?: Prisma.SortOrderInput | Prisma.SortOrder
  UOM?: Prisma.SortOrderInput | Prisma.SortOrder
  PackUnit?: Prisma.SortOrderInput | Prisma.SortOrder
  BreakUnit?: Prisma.SortOrderInput | Prisma.SortOrder
  BreakNumber?: Prisma.SortOrderInput | Prisma.SortOrder
  SizeUnit?: Prisma.SortOrderInput | Prisma.SortOrder
  SizeNumber?: Prisma.SortOrderInput | Prisma.SortOrder
  SizeQuantity?: Prisma.SortOrderInput | Prisma.SortOrder
  ERPExempt?: Prisma.SortOrder
  IdentStorage?: Prisma.SortOrder
  ExternalID?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.dProductCountOrderByAggregateInput
  _avg?: Prisma.dProductAvgOrderByAggregateInput
  _max?: Prisma.dProductMaxOrderByAggregateInput
  _min?: Prisma.dProductMinOrderByAggregateInput
  _sum?: Prisma.dProductSumOrderByAggregateInput
}

export type dProductScalarWhereWithAggregatesInput = {
  AND?: Prisma.dProductScalarWhereWithAggregatesInput | Prisma.dProductScalarWhereWithAggregatesInput[]
  OR?: Prisma.dProductScalarWhereWithAggregatesInput[]
  NOT?: Prisma.dProductScalarWhereWithAggregatesInput | Prisma.dProductScalarWhereWithAggregatesInput[]
  Identifier?: Prisma.IntWithAggregatesFilter<"dProduct"> | number
  Status?: Prisma.StringWithAggregatesFilter<"dProduct"> | string
  Creation?: Prisma.DateTimeWithAggregatesFilter<"dProduct"> | Date | string
  CreationID?: Prisma.IntWithAggregatesFilter<"dProduct"> | number
  Maintenance?: Prisma.DateTimeWithAggregatesFilter<"dProduct"> | Date | string
  MaintenanceID?: Prisma.IntWithAggregatesFilter<"dProduct"> | number
  Product?: Prisma.StringWithAggregatesFilter<"dProduct"> | string
  ItemCode?: Prisma.StringNullableWithAggregatesFilter<"dProduct"> | string | null
  ProductKey?: Prisma.StringNullableWithAggregatesFilter<"dProduct"> | string | null
  PropertyGroup?: Prisma.StringNullableWithAggregatesFilter<"dProduct"> | string | null
  Description?: Prisma.StringNullableWithAggregatesFilter<"dProduct"> | string | null
  Description2?: Prisma.StringNullableWithAggregatesFilter<"dProduct"> | string | null
  Description3?: Prisma.StringNullableWithAggregatesFilter<"dProduct"> | string | null
  UPC?: Prisma.StringNullableWithAggregatesFilter<"dProduct"> | string | null
  GTIN?: Prisma.StringNullableWithAggregatesFilter<"dProduct"> | string | null
  GS1?: Prisma.StringNullableWithAggregatesFilter<"dProduct"> | string | null
  PLU?: Prisma.StringNullableWithAggregatesFilter<"dProduct"> | string | null
  IMP?: Prisma.StringNullableWithAggregatesFilter<"dProduct"> | string | null
  NAMP?: Prisma.StringNullableWithAggregatesFilter<"dProduct"> | string | null
  SeasonType?: Prisma.StringNullableWithAggregatesFilter<"dProduct"> | string | null
  PageTitle?: Prisma.StringNullableWithAggregatesFilter<"dProduct"> | string | null
  StockLabel?: Prisma.StringNullableWithAggregatesFilter<"dProduct"> | string | null
  PalletLabel?: Prisma.StringNullableWithAggregatesFilter<"dProduct"> | string | null
  Picked?: Prisma.BoolWithAggregatesFilter<"dProduct"> | boolean
  ReqRebox?: Prisma.StringWithAggregatesFilter<"dProduct"> | string
  HoldCode?: Prisma.StringWithAggregatesFilter<"dProduct"> | string
  Plants?: Prisma.StringNullableWithAggregatesFilter<"dProduct"> | string | null
  Class?: Prisma.StringNullableWithAggregatesFilter<"dProduct"> | string | null
  UOM?: Prisma.StringNullableWithAggregatesFilter<"dProduct"> | string | null
  PackUnit?: Prisma.StringNullableWithAggregatesFilter<"dProduct"> | string | null
  BreakUnit?: Prisma.StringNullableWithAggregatesFilter<"dProduct"> | string | null
  BreakNumber?: Prisma.DecimalNullableWithAggregatesFilter<"dProduct"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  SizeUnit?: Prisma.StringNullableWithAggregatesFilter<"dProduct"> | string | null
  SizeNumber?: Prisma.DecimalNullableWithAggregatesFilter<"dProduct"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  SizeQuantity?: Prisma.DecimalNullableWithAggregatesFilter<"dProduct"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  ERPExempt?: Prisma.BoolWithAggregatesFilter<"dProduct"> | boolean
  IdentStorage?: Prisma.IntWithAggregatesFilter<"dProduct"> | number
  ExternalID?: Prisma.IntNullableWithAggregatesFilter<"dProduct"> | number | null
}

export type dProductCreateInput = {
  Status?: string
  Creation?: Date | string
  CreationID?: number
  Maintenance?: Date | string
  MaintenanceID?: number
  Product: string
  ItemCode?: string | null
  ProductKey?: string | null
  PropertyGroup?: string | null
  Description?: string | null
  Description2?: string | null
  Description3?: string | null
  UPC?: string | null
  GTIN?: string | null
  GS1?: string | null
  PLU?: string | null
  IMP?: string | null
  NAMP?: string | null
  SeasonType?: string | null
  PageTitle?: string | null
  StockLabel?: string | null
  PalletLabel?: string | null
  Picked?: boolean
  ReqRebox?: string
  HoldCode?: string
  Plants?: string | null
  Class?: string | null
  UOM?: string | null
  PackUnit?: string | null
  BreakUnit?: string | null
  BreakNumber?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  SizeUnit?: string | null
  SizeNumber?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  SizeQuantity?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  ERPExempt?: boolean
  IdentStorage?: number
  ExternalID?: number | null
}

export type dProductUncheckedCreateInput = {
  Identifier?: number
  Status?: string
  Creation?: Date | string
  CreationID?: number
  Maintenance?: Date | string
  MaintenanceID?: number
  Product: string
  ItemCode?: string | null
  ProductKey?: string | null
  PropertyGroup?: string | null
  Description?: string | null
  Description2?: string | null
  Description3?: string | null
  UPC?: string | null
  GTIN?: string | null
  GS1?: string | null
  PLU?: string | null
  IMP?: string | null
  NAMP?: string | null
  SeasonType?: string | null
  PageTitle?: string | null
  StockLabel?: string | null
  PalletLabel?: string | null
  Picked?: boolean
  ReqRebox?: string
  HoldCode?: string
  Plants?: string | null
  Class?: string | null
  UOM?: string | null
  PackUnit?: string | null
  BreakUnit?: string | null
  BreakNumber?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  SizeUnit?: string | null
  SizeNumber?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  SizeQuantity?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  ERPExempt?: boolean
  IdentStorage?: number
  ExternalID?: number | null
}

export type dProductUpdateInput = {
  Status?: Prisma.StringFieldUpdateOperationsInput | string
  Creation?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  CreationID?: Prisma.IntFieldUpdateOperationsInput | number
  Maintenance?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  MaintenanceID?: Prisma.IntFieldUpdateOperationsInput | number
  Product?: Prisma.StringFieldUpdateOperationsInput | string
  ItemCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ProductKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  PropertyGroup?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Description2?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Description3?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  UPC?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  GTIN?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  GS1?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  PLU?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  IMP?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  NAMP?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  SeasonType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  PageTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  StockLabel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  PalletLabel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Picked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  ReqRebox?: Prisma.StringFieldUpdateOperationsInput | string
  HoldCode?: Prisma.StringFieldUpdateOperationsInput | string
  Plants?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Class?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  UOM?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  PackUnit?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  BreakUnit?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  BreakNumber?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  SizeUnit?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  SizeNumber?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  SizeQuantity?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  ERPExempt?: Prisma.BoolFieldUpdateOperationsInput | boolean
  IdentStorage?: Prisma.IntFieldUpdateOperationsInput | number
  ExternalID?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type dProductUncheckedUpdateInput = {
  Identifier?: Prisma.IntFieldUpdateOperationsInput | number
  Status?: Prisma.StringFieldUpdateOperationsInput | string
  Creation?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  CreationID?: Prisma.IntFieldUpdateOperationsInput | number
  Maintenance?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  MaintenanceID?: Prisma.IntFieldUpdateOperationsInput | number
  Product?: Prisma.StringFieldUpdateOperationsInput | string
  ItemCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ProductKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  PropertyGroup?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Description2?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Description3?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  UPC?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  GTIN?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  GS1?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  PLU?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  IMP?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  NAMP?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  SeasonType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  PageTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  StockLabel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  PalletLabel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Picked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  ReqRebox?: Prisma.StringFieldUpdateOperationsInput | string
  HoldCode?: Prisma.StringFieldUpdateOperationsInput | string
  Plants?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Class?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  UOM?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  PackUnit?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  BreakUnit?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  BreakNumber?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  SizeUnit?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  SizeNumber?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  SizeQuantity?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  ERPExempt?: Prisma.BoolFieldUpdateOperationsInput | boolean
  IdentStorage?: Prisma.IntFieldUpdateOperationsInput | number
  ExternalID?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type dProductCreateManyInput = {
  Status?: string
  Creation?: Date | string
  CreationID?: number
  Maintenance?: Date | string
  MaintenanceID?: number
  Product: string
  ItemCode?: string | null
  ProductKey?: string | null
  PropertyGroup?: string | null
  Description?: string | null
  Description2?: string | null
  Description3?: string | null
  UPC?: string | null
  GTIN?: string | null
  GS1?: string | null
  PLU?: string | null
  IMP?: string | null
  NAMP?: string | null
  SeasonType?: string | null
  PageTitle?: string | null
  StockLabel?: string | null
  PalletLabel?: string | null
  Picked?: boolean
  ReqRebox?: string
  HoldCode?: string
  Plants?: string | null
  Class?: string | null
  UOM?: string | null
  PackUnit?: string | null
  BreakUnit?: string | null
  BreakNumber?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  SizeUnit?: string | null
  SizeNumber?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  SizeQuantity?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  ERPExempt?: boolean
  IdentStorage?: number
  ExternalID?: number | null
}

export type dProductUpdateManyMutationInput = {
  Status?: Prisma.StringFieldUpdateOperationsInput | string
  Creation?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  CreationID?: Prisma.IntFieldUpdateOperationsInput | number
  Maintenance?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  MaintenanceID?: Prisma.IntFieldUpdateOperationsInput | number
  Product?: Prisma.StringFieldUpdateOperationsInput | string
  ItemCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ProductKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  PropertyGroup?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Description2?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Description3?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  UPC?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  GTIN?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  GS1?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  PLU?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  IMP?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  NAMP?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  SeasonType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  PageTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  StockLabel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  PalletLabel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Picked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  ReqRebox?: Prisma.StringFieldUpdateOperationsInput | string
  HoldCode?: Prisma.StringFieldUpdateOperationsInput | string
  Plants?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Class?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  UOM?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  PackUnit?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  BreakUnit?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  BreakNumber?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  SizeUnit?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  SizeNumber?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  SizeQuantity?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  ERPExempt?: Prisma.BoolFieldUpdateOperationsInput | boolean
  IdentStorage?: Prisma.IntFieldUpdateOperationsInput | number
  ExternalID?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type dProductUncheckedUpdateManyInput = {
  Identifier?: Prisma.IntFieldUpdateOperationsInput | number
  Status?: Prisma.StringFieldUpdateOperationsInput | string
  Creation?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  CreationID?: Prisma.IntFieldUpdateOperationsInput | number
  Maintenance?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  MaintenanceID?: Prisma.IntFieldUpdateOperationsInput | number
  Product?: Prisma.StringFieldUpdateOperationsInput | string
  ItemCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ProductKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  PropertyGroup?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Description2?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Description3?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  UPC?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  GTIN?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  GS1?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  PLU?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  IMP?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  NAMP?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  SeasonType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  PageTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  StockLabel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  PalletLabel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Picked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  ReqRebox?: Prisma.StringFieldUpdateOperationsInput | string
  HoldCode?: Prisma.StringFieldUpdateOperationsInput | string
  Plants?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Class?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  UOM?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  PackUnit?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  BreakUnit?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  BreakNumber?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  SizeUnit?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  SizeNumber?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  SizeQuantity?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  ERPExempt?: Prisma.BoolFieldUpdateOperationsInput | boolean
  IdentStorage?: Prisma.IntFieldUpdateOperationsInput | number
  ExternalID?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type dProductCountOrderByAggregateInput = {
  Identifier?: Prisma.SortOrder
  Status?: Prisma.SortOrder
  Creation?: Prisma.SortOrder
  CreationID?: Prisma.SortOrder
  Maintenance?: Prisma.SortOrder
  MaintenanceID?: Prisma.SortOrder
  Product?: Prisma.SortOrder
  ItemCode?: Prisma.SortOrder
  ProductKey?: Prisma.SortOrder
  PropertyGroup?: Prisma.SortOrder
  Description?: Prisma.SortOrder
  Description2?: Prisma.SortOrder
  Description3?: Prisma.SortOrder
  UPC?: Prisma.SortOrder
  GTIN?: Prisma.SortOrder
  GS1?: Prisma.SortOrder
  PLU?: Prisma.SortOrder
  IMP?: Prisma.SortOrder
  NAMP?: Prisma.SortOrder
  SeasonType?: Prisma.SortOrder
  PageTitle?: Prisma.SortOrder
  StockLabel?: Prisma.SortOrder
  PalletLabel?: Prisma.SortOrder
  Picked?: Prisma.SortOrder
  ReqRebox?: Prisma.SortOrder
  HoldCode?: Prisma.SortOrder
  Plants?: Prisma.SortOrder
  Class?: Prisma.SortOrder
  UOM?: Prisma.SortOrder
  PackUnit?: Prisma.SortOrder
  BreakUnit?: Prisma.SortOrder
  BreakNumber?: Prisma.SortOrder
  SizeUnit?: Prisma.SortOrder
  SizeNumber?: Prisma.SortOrder
  SizeQuantity?: Prisma.SortOrder
  ERPExempt?: Prisma.SortOrder
  IdentStorage?: Prisma.SortOrder
  ExternalID?: Prisma.SortOrder
}

export type dProductAvgOrderByAggregateInput = {
  Identifier?: Prisma.SortOrder
  CreationID?: Prisma.SortOrder
  MaintenanceID?: Prisma.SortOrder
  BreakNumber?: Prisma.SortOrder
  SizeNumber?: Prisma.SortOrder
  SizeQuantity?: Prisma.SortOrder
  IdentStorage?: Prisma.SortOrder
  ExternalID?: Prisma.SortOrder
}

export type dProductMaxOrderByAggregateInput = {
  Identifier?: Prisma.SortOrder
  Status?: Prisma.SortOrder
  Creation?: Prisma.SortOrder
  CreationID?: Prisma.SortOrder
  Maintenance?: Prisma.SortOrder
  MaintenanceID?: Prisma.SortOrder
  Product?: Prisma.SortOrder
  ItemCode?: Prisma.SortOrder
  ProductKey?: Prisma.SortOrder
  PropertyGroup?: Prisma.SortOrder
  Description?: Prisma.SortOrder
  Description2?: Prisma.SortOrder
  Description3?: Prisma.SortOrder
  UPC?: Prisma.SortOrder
  GTIN?: Prisma.SortOrder
  GS1?: Prisma.SortOrder
  PLU?: Prisma.SortOrder
  IMP?: Prisma.SortOrder
  NAMP?: Prisma.SortOrder
  SeasonType?: Prisma.SortOrder
  PageTitle?: Prisma.SortOrder
  StockLabel?: Prisma.SortOrder
  PalletLabel?: Prisma.SortOrder
  Picked?: Prisma.SortOrder
  ReqRebox?: Prisma.SortOrder
  HoldCode?: Prisma.SortOrder
  Plants?: Prisma.SortOrder
  Class?: Prisma.SortOrder
  UOM?: Prisma.SortOrder
  PackUnit?: Prisma.SortOrder
  BreakUnit?: Prisma.SortOrder
  BreakNumber?: Prisma.SortOrder
  SizeUnit?: Prisma.SortOrder
  SizeNumber?: Prisma.SortOrder
  SizeQuantity?: Prisma.SortOrder
  ERPExempt?: Prisma.SortOrder
  IdentStorage?: Prisma.SortOrder
  ExternalID?: Prisma.SortOrder
}

export type dProductMinOrderByAggregateInput = {
  Identifier?: Prisma.SortOrder
  Status?: Prisma.SortOrder
  Creation?: Prisma.SortOrder
  CreationID?: Prisma.SortOrder
  Maintenance?: Prisma.SortOrder
  MaintenanceID?: Prisma.SortOrder
  Product?: Prisma.SortOrder
  ItemCode?: Prisma.SortOrder
  ProductKey?: Prisma.SortOrder
  PropertyGroup?: Prisma.SortOrder
  Description?: Prisma.SortOrder
  Description2?: Prisma.SortOrder
  Description3?: Prisma.SortOrder
  UPC?: Prisma.SortOrder
  GTIN?: Prisma.SortOrder
  GS1?: Prisma.SortOrder
  PLU?: Prisma.SortOrder
  IMP?: Prisma.SortOrder
  NAMP?: Prisma.SortOrder
  SeasonType?: Prisma.SortOrder
  PageTitle?: Prisma.SortOrder
  StockLabel?: Prisma.SortOrder
  PalletLabel?: Prisma.SortOrder
  Picked?: Prisma.SortOrder
  ReqRebox?: Prisma.SortOrder
  HoldCode?: Prisma.SortOrder
  Plants?: Prisma.SortOrder
  Class?: Prisma.SortOrder
  UOM?: Prisma.SortOrder
  PackUnit?: Prisma.SortOrder
  BreakUnit?: Prisma.SortOrder
  BreakNumber?: Prisma.SortOrder
  SizeUnit?: Prisma.SortOrder
  SizeNumber?: Prisma.SortOrder
  SizeQuantity?: Prisma.SortOrder
  ERPExempt?: Prisma.SortOrder
  IdentStorage?: Prisma.SortOrder
  ExternalID?: Prisma.SortOrder
}

export type dProductSumOrderByAggregateInput = {
  Identifier?: Prisma.SortOrder
  CreationID?: Prisma.SortOrder
  MaintenanceID?: Prisma.SortOrder
  BreakNumber?: Prisma.SortOrder
  SizeNumber?: Prisma.SortOrder
  SizeQuantity?: Prisma.SortOrder
  IdentStorage?: Prisma.SortOrder
  ExternalID?: Prisma.SortOrder
}



export type dProductSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  Identifier?: boolean
  Status?: boolean
  Creation?: boolean
  CreationID?: boolean
  Maintenance?: boolean
  MaintenanceID?: boolean
  Product?: boolean
  ItemCode?: boolean
  ProductKey?: boolean
  PropertyGroup?: boolean
  Description?: boolean
  Description2?: boolean
  Description3?: boolean
  UPC?: boolean
  GTIN?: boolean
  GS1?: boolean
  PLU?: boolean
  IMP?: boolean
  NAMP?: boolean
  SeasonType?: boolean
  PageTitle?: boolean
  StockLabel?: boolean
  PalletLabel?: boolean
  Picked?: boolean
  ReqRebox?: boolean
  HoldCode?: boolean
  Plants?: boolean
  Class?: boolean
  UOM?: boolean
  PackUnit?: boolean
  BreakUnit?: boolean
  BreakNumber?: boolean
  SizeUnit?: boolean
  SizeNumber?: boolean
  SizeQuantity?: boolean
  ERPExempt?: boolean
  IdentStorage?: boolean
  ExternalID?: boolean
}, ExtArgs["result"]["dProduct"]>



export type dProductSelectScalar = {
  Identifier?: boolean
  Status?: boolean
  Creation?: boolean
  CreationID?: boolean
  Maintenance?: boolean
  MaintenanceID?: boolean
  Product?: boolean
  ItemCode?: boolean
  ProductKey?: boolean
  PropertyGroup?: boolean
  Description?: boolean
  Description2?: boolean
  Description3?: boolean
  UPC?: boolean
  GTIN?: boolean
  GS1?: boolean
  PLU?: boolean
  IMP?: boolean
  NAMP?: boolean
  SeasonType?: boolean
  PageTitle?: boolean
  StockLabel?: boolean
  PalletLabel?: boolean
  Picked?: boolean
  ReqRebox?: boolean
  HoldCode?: boolean
  Plants?: boolean
  Class?: boolean
  UOM?: boolean
  PackUnit?: boolean
  BreakUnit?: boolean
  BreakNumber?: boolean
  SizeUnit?: boolean
  SizeNumber?: boolean
  SizeQuantity?: boolean
  ERPExempt?: boolean
  IdentStorage?: boolean
  ExternalID?: boolean
}

export type dProductOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"Identifier" | "Status" | "Creation" | "CreationID" | "Maintenance" | "MaintenanceID" | "Product" | "ItemCode" | "ProductKey" | "PropertyGroup" | "Description" | "Description2" | "Description3" | "UPC" | "GTIN" | "GS1" | "PLU" | "IMP" | "NAMP" | "SeasonType" | "PageTitle" | "StockLabel" | "PalletLabel" | "Picked" | "ReqRebox" | "HoldCode" | "Plants" | "Class" | "UOM" | "PackUnit" | "BreakUnit" | "BreakNumber" | "SizeUnit" | "SizeNumber" | "SizeQuantity" | "ERPExempt" | "IdentStorage" | "ExternalID", ExtArgs["result"]["dProduct"]>

export type $dProductPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "dProduct"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    Identifier: number
    Status: string
    Creation: Date
    CreationID: number
    Maintenance: Date
    MaintenanceID: number
    Product: string
    ItemCode: string | null
    ProductKey: string | null
    PropertyGroup: string | null
    Description: string | null
    Description2: string | null
    Description3: string | null
    UPC: string | null
    GTIN: string | null
    GS1: string | null
    PLU: string | null
    IMP: string | null
    NAMP: string | null
    SeasonType: string | null
    PageTitle: string | null
    StockLabel: string | null
    PalletLabel: string | null
    Picked: boolean
    ReqRebox: string
    HoldCode: string
    Plants: string | null
    Class: string | null
    UOM: string | null
    PackUnit: string | null
    BreakUnit: string | null
    BreakNumber: runtime.Decimal | null
    SizeUnit: string | null
    SizeNumber: runtime.Decimal | null
    SizeQuantity: runtime.Decimal | null
    ERPExempt: boolean
    IdentStorage: number
    ExternalID: number | null
  }, ExtArgs["result"]["dProduct"]>
  composites: {}
}

export type dProductGetPayload<S extends boolean | null | undefined | dProductDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$dProductPayload, S>

export type dProductCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<dProductFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DProductCountAggregateInputType | true
  }

export interface dProductDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['dProduct'], meta: { name: 'dProduct' } }
  /**
   * Find zero or one DProduct that matches the filter.
   * @param {dProductFindUniqueArgs} args - Arguments to find a DProduct
   * @example
   * // Get one DProduct
   * const dProduct = await prisma.dProduct.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends dProductFindUniqueArgs>(args: Prisma.SelectSubset<T, dProductFindUniqueArgs<ExtArgs>>): Prisma.Prisma__dProductClient<runtime.Types.Result.GetResult<Prisma.$dProductPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one DProduct that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {dProductFindUniqueOrThrowArgs} args - Arguments to find a DProduct
   * @example
   * // Get one DProduct
   * const dProduct = await prisma.dProduct.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends dProductFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, dProductFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__dProductClient<runtime.Types.Result.GetResult<Prisma.$dProductPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DProduct that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dProductFindFirstArgs} args - Arguments to find a DProduct
   * @example
   * // Get one DProduct
   * const dProduct = await prisma.dProduct.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends dProductFindFirstArgs>(args?: Prisma.SelectSubset<T, dProductFindFirstArgs<ExtArgs>>): Prisma.Prisma__dProductClient<runtime.Types.Result.GetResult<Prisma.$dProductPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DProduct that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dProductFindFirstOrThrowArgs} args - Arguments to find a DProduct
   * @example
   * // Get one DProduct
   * const dProduct = await prisma.dProduct.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends dProductFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, dProductFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__dProductClient<runtime.Types.Result.GetResult<Prisma.$dProductPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more DProducts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dProductFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all DProducts
   * const dProducts = await prisma.dProduct.findMany()
   * 
   * // Get first 10 DProducts
   * const dProducts = await prisma.dProduct.findMany({ take: 10 })
   * 
   * // Only select the `Identifier`
   * const dProductWithIdentifierOnly = await prisma.dProduct.findMany({ select: { Identifier: true } })
   * 
   */
  findMany<T extends dProductFindManyArgs>(args?: Prisma.SelectSubset<T, dProductFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$dProductPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a DProduct.
   * @param {dProductCreateArgs} args - Arguments to create a DProduct.
   * @example
   * // Create one DProduct
   * const DProduct = await prisma.dProduct.create({
   *   data: {
   *     // ... data to create a DProduct
   *   }
   * })
   * 
   */
  create<T extends dProductCreateArgs>(args: Prisma.SelectSubset<T, dProductCreateArgs<ExtArgs>>): Prisma.Prisma__dProductClient<runtime.Types.Result.GetResult<Prisma.$dProductPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many DProducts.
   * @param {dProductCreateManyArgs} args - Arguments to create many DProducts.
   * @example
   * // Create many DProducts
   * const dProduct = await prisma.dProduct.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends dProductCreateManyArgs>(args?: Prisma.SelectSubset<T, dProductCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a DProduct.
   * @param {dProductDeleteArgs} args - Arguments to delete one DProduct.
   * @example
   * // Delete one DProduct
   * const DProduct = await prisma.dProduct.delete({
   *   where: {
   *     // ... filter to delete one DProduct
   *   }
   * })
   * 
   */
  delete<T extends dProductDeleteArgs>(args: Prisma.SelectSubset<T, dProductDeleteArgs<ExtArgs>>): Prisma.Prisma__dProductClient<runtime.Types.Result.GetResult<Prisma.$dProductPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one DProduct.
   * @param {dProductUpdateArgs} args - Arguments to update one DProduct.
   * @example
   * // Update one DProduct
   * const dProduct = await prisma.dProduct.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends dProductUpdateArgs>(args: Prisma.SelectSubset<T, dProductUpdateArgs<ExtArgs>>): Prisma.Prisma__dProductClient<runtime.Types.Result.GetResult<Prisma.$dProductPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more DProducts.
   * @param {dProductDeleteManyArgs} args - Arguments to filter DProducts to delete.
   * @example
   * // Delete a few DProducts
   * const { count } = await prisma.dProduct.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends dProductDeleteManyArgs>(args?: Prisma.SelectSubset<T, dProductDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DProducts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dProductUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many DProducts
   * const dProduct = await prisma.dProduct.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends dProductUpdateManyArgs>(args: Prisma.SelectSubset<T, dProductUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one DProduct.
   * @param {dProductUpsertArgs} args - Arguments to update or create a DProduct.
   * @example
   * // Update or create a DProduct
   * const dProduct = await prisma.dProduct.upsert({
   *   create: {
   *     // ... data to create a DProduct
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the DProduct we want to update
   *   }
   * })
   */
  upsert<T extends dProductUpsertArgs>(args: Prisma.SelectSubset<T, dProductUpsertArgs<ExtArgs>>): Prisma.Prisma__dProductClient<runtime.Types.Result.GetResult<Prisma.$dProductPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of DProducts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dProductCountArgs} args - Arguments to filter DProducts to count.
   * @example
   * // Count the number of DProducts
   * const count = await prisma.dProduct.count({
   *   where: {
   *     // ... the filter for the DProducts we want to count
   *   }
   * })
  **/
  count<T extends dProductCountArgs>(
    args?: Prisma.Subset<T, dProductCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DProductCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a DProduct.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DProductAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DProductAggregateArgs>(args: Prisma.Subset<T, DProductAggregateArgs>): Prisma.PrismaPromise<GetDProductAggregateType<T>>

  /**
   * Group by DProduct.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dProductGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends dProductGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: dProductGroupByArgs['orderBy'] }
      : { orderBy?: dProductGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, dProductGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDProductGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the dProduct model
 */
readonly fields: dProductFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for dProduct.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__dProductClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the dProduct model
 */
export interface dProductFieldRefs {
  readonly Identifier: Prisma.FieldRef<"dProduct", 'Int'>
  readonly Status: Prisma.FieldRef<"dProduct", 'String'>
  readonly Creation: Prisma.FieldRef<"dProduct", 'DateTime'>
  readonly CreationID: Prisma.FieldRef<"dProduct", 'Int'>
  readonly Maintenance: Prisma.FieldRef<"dProduct", 'DateTime'>
  readonly MaintenanceID: Prisma.FieldRef<"dProduct", 'Int'>
  readonly Product: Prisma.FieldRef<"dProduct", 'String'>
  readonly ItemCode: Prisma.FieldRef<"dProduct", 'String'>
  readonly ProductKey: Prisma.FieldRef<"dProduct", 'String'>
  readonly PropertyGroup: Prisma.FieldRef<"dProduct", 'String'>
  readonly Description: Prisma.FieldRef<"dProduct", 'String'>
  readonly Description2: Prisma.FieldRef<"dProduct", 'String'>
  readonly Description3: Prisma.FieldRef<"dProduct", 'String'>
  readonly UPC: Prisma.FieldRef<"dProduct", 'String'>
  readonly GTIN: Prisma.FieldRef<"dProduct", 'String'>
  readonly GS1: Prisma.FieldRef<"dProduct", 'String'>
  readonly PLU: Prisma.FieldRef<"dProduct", 'String'>
  readonly IMP: Prisma.FieldRef<"dProduct", 'String'>
  readonly NAMP: Prisma.FieldRef<"dProduct", 'String'>
  readonly SeasonType: Prisma.FieldRef<"dProduct", 'String'>
  readonly PageTitle: Prisma.FieldRef<"dProduct", 'String'>
  readonly StockLabel: Prisma.FieldRef<"dProduct", 'String'>
  readonly PalletLabel: Prisma.FieldRef<"dProduct", 'String'>
  readonly Picked: Prisma.FieldRef<"dProduct", 'Boolean'>
  readonly ReqRebox: Prisma.FieldRef<"dProduct", 'String'>
  readonly HoldCode: Prisma.FieldRef<"dProduct", 'String'>
  readonly Plants: Prisma.FieldRef<"dProduct", 'String'>
  readonly Class: Prisma.FieldRef<"dProduct", 'String'>
  readonly UOM: Prisma.FieldRef<"dProduct", 'String'>
  readonly PackUnit: Prisma.FieldRef<"dProduct", 'String'>
  readonly BreakUnit: Prisma.FieldRef<"dProduct", 'String'>
  readonly BreakNumber: Prisma.FieldRef<"dProduct", 'Decimal'>
  readonly SizeUnit: Prisma.FieldRef<"dProduct", 'String'>
  readonly SizeNumber: Prisma.FieldRef<"dProduct", 'Decimal'>
  readonly SizeQuantity: Prisma.FieldRef<"dProduct", 'Decimal'>
  readonly ERPExempt: Prisma.FieldRef<"dProduct", 'Boolean'>
  readonly IdentStorage: Prisma.FieldRef<"dProduct", 'Int'>
  readonly ExternalID: Prisma.FieldRef<"dProduct", 'Int'>
}
    

// Custom InputTypes
/**
 * dProduct findUnique
 */
export type dProductFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dProduct
   */
  select?: Prisma.dProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dProduct
   */
  omit?: Prisma.dProductOmit<ExtArgs> | null
  /**
   * Filter, which dProduct to fetch.
   */
  where: Prisma.dProductWhereUniqueInput
}

/**
 * dProduct findUniqueOrThrow
 */
export type dProductFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dProduct
   */
  select?: Prisma.dProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dProduct
   */
  omit?: Prisma.dProductOmit<ExtArgs> | null
  /**
   * Filter, which dProduct to fetch.
   */
  where: Prisma.dProductWhereUniqueInput
}

/**
 * dProduct findFirst
 */
export type dProductFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dProduct
   */
  select?: Prisma.dProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dProduct
   */
  omit?: Prisma.dProductOmit<ExtArgs> | null
  /**
   * Filter, which dProduct to fetch.
   */
  where?: Prisma.dProductWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of dProducts to fetch.
   */
  orderBy?: Prisma.dProductOrderByWithRelationInput | Prisma.dProductOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for dProducts.
   */
  cursor?: Prisma.dProductWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` dProducts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` dProducts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of dProducts.
   */
  distinct?: Prisma.DProductScalarFieldEnum | Prisma.DProductScalarFieldEnum[]
}

/**
 * dProduct findFirstOrThrow
 */
export type dProductFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dProduct
   */
  select?: Prisma.dProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dProduct
   */
  omit?: Prisma.dProductOmit<ExtArgs> | null
  /**
   * Filter, which dProduct to fetch.
   */
  where?: Prisma.dProductWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of dProducts to fetch.
   */
  orderBy?: Prisma.dProductOrderByWithRelationInput | Prisma.dProductOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for dProducts.
   */
  cursor?: Prisma.dProductWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` dProducts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` dProducts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of dProducts.
   */
  distinct?: Prisma.DProductScalarFieldEnum | Prisma.DProductScalarFieldEnum[]
}

/**
 * dProduct findMany
 */
export type dProductFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dProduct
   */
  select?: Prisma.dProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dProduct
   */
  omit?: Prisma.dProductOmit<ExtArgs> | null
  /**
   * Filter, which dProducts to fetch.
   */
  where?: Prisma.dProductWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of dProducts to fetch.
   */
  orderBy?: Prisma.dProductOrderByWithRelationInput | Prisma.dProductOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing dProducts.
   */
  cursor?: Prisma.dProductWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` dProducts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` dProducts.
   */
  skip?: number
  distinct?: Prisma.DProductScalarFieldEnum | Prisma.DProductScalarFieldEnum[]
}

/**
 * dProduct create
 */
export type dProductCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dProduct
   */
  select?: Prisma.dProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dProduct
   */
  omit?: Prisma.dProductOmit<ExtArgs> | null
  /**
   * The data needed to create a dProduct.
   */
  data: Prisma.XOR<Prisma.dProductCreateInput, Prisma.dProductUncheckedCreateInput>
}

/**
 * dProduct createMany
 */
export type dProductCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many dProducts.
   */
  data: Prisma.dProductCreateManyInput | Prisma.dProductCreateManyInput[]
}

/**
 * dProduct update
 */
export type dProductUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dProduct
   */
  select?: Prisma.dProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dProduct
   */
  omit?: Prisma.dProductOmit<ExtArgs> | null
  /**
   * The data needed to update a dProduct.
   */
  data: Prisma.XOR<Prisma.dProductUpdateInput, Prisma.dProductUncheckedUpdateInput>
  /**
   * Choose, which dProduct to update.
   */
  where: Prisma.dProductWhereUniqueInput
}

/**
 * dProduct updateMany
 */
export type dProductUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update dProducts.
   */
  data: Prisma.XOR<Prisma.dProductUpdateManyMutationInput, Prisma.dProductUncheckedUpdateManyInput>
  /**
   * Filter which dProducts to update
   */
  where?: Prisma.dProductWhereInput
  /**
   * Limit how many dProducts to update.
   */
  limit?: number
}

/**
 * dProduct upsert
 */
export type dProductUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dProduct
   */
  select?: Prisma.dProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dProduct
   */
  omit?: Prisma.dProductOmit<ExtArgs> | null
  /**
   * The filter to search for the dProduct to update in case it exists.
   */
  where: Prisma.dProductWhereUniqueInput
  /**
   * In case the dProduct found by the `where` argument doesn't exist, create a new dProduct with this data.
   */
  create: Prisma.XOR<Prisma.dProductCreateInput, Prisma.dProductUncheckedCreateInput>
  /**
   * In case the dProduct was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.dProductUpdateInput, Prisma.dProductUncheckedUpdateInput>
}

/**
 * dProduct delete
 */
export type dProductDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dProduct
   */
  select?: Prisma.dProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dProduct
   */
  omit?: Prisma.dProductOmit<ExtArgs> | null
  /**
   * Filter which dProduct to delete.
   */
  where: Prisma.dProductWhereUniqueInput
}

/**
 * dProduct deleteMany
 */
export type dProductDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which dProducts to delete
   */
  where?: Prisma.dProductWhereInput
  /**
   * Limit how many dProducts to delete.
   */
  limit?: number
}

/**
 * dProduct without action
 */
export type dProductDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dProduct
   */
  select?: Prisma.dProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dProduct
   */
  omit?: Prisma.dProductOmit<ExtArgs> | null
}
