
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `dPurchaseOrder` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model dPurchaseOrder
 * 
 */
export type dPurchaseOrderModel = runtime.Types.Result.DefaultSelection<Prisma.$dPurchaseOrderPayload>

export type AggregateDPurchaseOrder = {
  _count: DPurchaseOrderCountAggregateOutputType | null
  _avg: DPurchaseOrderAvgAggregateOutputType | null
  _sum: DPurchaseOrderSumAggregateOutputType | null
  _min: DPurchaseOrderMinAggregateOutputType | null
  _max: DPurchaseOrderMaxAggregateOutputType | null
}

export type DPurchaseOrderAvgAggregateOutputType = {
  Identifier: number | null
  CreationID: number | null
  MaintenanceID: number | null
  ExternalID: number | null
  LineID: number | null
  CommitID: number | null
  ItemID: number | null
  Line: number | null
  Quantity: runtime.Decimal | null
  QuantityCommit: runtime.Decimal | null
  Weight: runtime.Decimal | null
  IdentProduct: number | null
  IdentStorage: number | null
  IdentStorageTo: number | null
  IdentSupplier: number | null
  IdentCustomer: number | null
  IdentAddressLocation: number | null
  IdentAddressBill: number | null
  IdentAddressShip: number | null
}

export type DPurchaseOrderSumAggregateOutputType = {
  Identifier: number | null
  CreationID: number | null
  MaintenanceID: number | null
  ExternalID: number | null
  LineID: number | null
  CommitID: number | null
  ItemID: number | null
  Line: number | null
  Quantity: runtime.Decimal | null
  QuantityCommit: runtime.Decimal | null
  Weight: runtime.Decimal | null
  IdentProduct: number | null
  IdentStorage: number | null
  IdentStorageTo: number | null
  IdentSupplier: number | null
  IdentCustomer: number | null
  IdentAddressLocation: number | null
  IdentAddressBill: number | null
  IdentAddressShip: number | null
}

export type DPurchaseOrderMinAggregateOutputType = {
  Identifier: number | null
  Status: string | null
  Creation: Date | null
  CreationID: number | null
  Maintenance: Date | null
  MaintenanceID: number | null
  PurchaseOrder: string | null
  ImportDate: Date | null
  ExportDate: Date | null
  ExternalID: number | null
  LineID: number | null
  CommitID: number | null
  ItemID: number | null
  Type: string | null
  Line: number | null
  ItemNumber: string | null
  Quantity: runtime.Decimal | null
  QuantityCommit: runtime.Decimal | null
  UOM: string | null
  UOMCommit: string | null
  Weight: runtime.Decimal | null
  UOMWeight: string | null
  Lot: string | null
  Storage: string | null
  StorageTo: string | null
  Initial: Date | null
  Expected: Date | null
  Committed: Date | null
  Completed: Date | null
  Supplier: string | null
  Customer: string | null
  Owner: string | null
  IdentProduct: number | null
  IdentStorage: number | null
  IdentStorageTo: number | null
  IdentSupplier: number | null
  IdentCustomer: number | null
  IdentAddressLocation: number | null
  IdentAddressBill: number | null
  IdentAddressShip: number | null
}

export type DPurchaseOrderMaxAggregateOutputType = {
  Identifier: number | null
  Status: string | null
  Creation: Date | null
  CreationID: number | null
  Maintenance: Date | null
  MaintenanceID: number | null
  PurchaseOrder: string | null
  ImportDate: Date | null
  ExportDate: Date | null
  ExternalID: number | null
  LineID: number | null
  CommitID: number | null
  ItemID: number | null
  Type: string | null
  Line: number | null
  ItemNumber: string | null
  Quantity: runtime.Decimal | null
  QuantityCommit: runtime.Decimal | null
  UOM: string | null
  UOMCommit: string | null
  Weight: runtime.Decimal | null
  UOMWeight: string | null
  Lot: string | null
  Storage: string | null
  StorageTo: string | null
  Initial: Date | null
  Expected: Date | null
  Committed: Date | null
  Completed: Date | null
  Supplier: string | null
  Customer: string | null
  Owner: string | null
  IdentProduct: number | null
  IdentStorage: number | null
  IdentStorageTo: number | null
  IdentSupplier: number | null
  IdentCustomer: number | null
  IdentAddressLocation: number | null
  IdentAddressBill: number | null
  IdentAddressShip: number | null
}

export type DPurchaseOrderCountAggregateOutputType = {
  Identifier: number
  Status: number
  Creation: number
  CreationID: number
  Maintenance: number
  MaintenanceID: number
  PurchaseOrder: number
  ImportDate: number
  ExportDate: number
  ExternalID: number
  LineID: number
  CommitID: number
  ItemID: number
  Type: number
  Line: number
  ItemNumber: number
  Quantity: number
  QuantityCommit: number
  UOM: number
  UOMCommit: number
  Weight: number
  UOMWeight: number
  Lot: number
  Storage: number
  StorageTo: number
  Initial: number
  Expected: number
  Committed: number
  Completed: number
  Supplier: number
  Customer: number
  Owner: number
  IdentProduct: number
  IdentStorage: number
  IdentStorageTo: number
  IdentSupplier: number
  IdentCustomer: number
  IdentAddressLocation: number
  IdentAddressBill: number
  IdentAddressShip: number
  _all: number
}


export type DPurchaseOrderAvgAggregateInputType = {
  Identifier?: true
  CreationID?: true
  MaintenanceID?: true
  ExternalID?: true
  LineID?: true
  CommitID?: true
  ItemID?: true
  Line?: true
  Quantity?: true
  QuantityCommit?: true
  Weight?: true
  IdentProduct?: true
  IdentStorage?: true
  IdentStorageTo?: true
  IdentSupplier?: true
  IdentCustomer?: true
  IdentAddressLocation?: true
  IdentAddressBill?: true
  IdentAddressShip?: true
}

export type DPurchaseOrderSumAggregateInputType = {
  Identifier?: true
  CreationID?: true
  MaintenanceID?: true
  ExternalID?: true
  LineID?: true
  CommitID?: true
  ItemID?: true
  Line?: true
  Quantity?: true
  QuantityCommit?: true
  Weight?: true
  IdentProduct?: true
  IdentStorage?: true
  IdentStorageTo?: true
  IdentSupplier?: true
  IdentCustomer?: true
  IdentAddressLocation?: true
  IdentAddressBill?: true
  IdentAddressShip?: true
}

export type DPurchaseOrderMinAggregateInputType = {
  Identifier?: true
  Status?: true
  Creation?: true
  CreationID?: true
  Maintenance?: true
  MaintenanceID?: true
  PurchaseOrder?: true
  ImportDate?: true
  ExportDate?: true
  ExternalID?: true
  LineID?: true
  CommitID?: true
  ItemID?: true
  Type?: true
  Line?: true
  ItemNumber?: true
  Quantity?: true
  QuantityCommit?: true
  UOM?: true
  UOMCommit?: true
  Weight?: true
  UOMWeight?: true
  Lot?: true
  Storage?: true
  StorageTo?: true
  Initial?: true
  Expected?: true
  Committed?: true
  Completed?: true
  Supplier?: true
  Customer?: true
  Owner?: true
  IdentProduct?: true
  IdentStorage?: true
  IdentStorageTo?: true
  IdentSupplier?: true
  IdentCustomer?: true
  IdentAddressLocation?: true
  IdentAddressBill?: true
  IdentAddressShip?: true
}

export type DPurchaseOrderMaxAggregateInputType = {
  Identifier?: true
  Status?: true
  Creation?: true
  CreationID?: true
  Maintenance?: true
  MaintenanceID?: true
  PurchaseOrder?: true
  ImportDate?: true
  ExportDate?: true
  ExternalID?: true
  LineID?: true
  CommitID?: true
  ItemID?: true
  Type?: true
  Line?: true
  ItemNumber?: true
  Quantity?: true
  QuantityCommit?: true
  UOM?: true
  UOMCommit?: true
  Weight?: true
  UOMWeight?: true
  Lot?: true
  Storage?: true
  StorageTo?: true
  Initial?: true
  Expected?: true
  Committed?: true
  Completed?: true
  Supplier?: true
  Customer?: true
  Owner?: true
  IdentProduct?: true
  IdentStorage?: true
  IdentStorageTo?: true
  IdentSupplier?: true
  IdentCustomer?: true
  IdentAddressLocation?: true
  IdentAddressBill?: true
  IdentAddressShip?: true
}

export type DPurchaseOrderCountAggregateInputType = {
  Identifier?: true
  Status?: true
  Creation?: true
  CreationID?: true
  Maintenance?: true
  MaintenanceID?: true
  PurchaseOrder?: true
  ImportDate?: true
  ExportDate?: true
  ExternalID?: true
  LineID?: true
  CommitID?: true
  ItemID?: true
  Type?: true
  Line?: true
  ItemNumber?: true
  Quantity?: true
  QuantityCommit?: true
  UOM?: true
  UOMCommit?: true
  Weight?: true
  UOMWeight?: true
  Lot?: true
  Storage?: true
  StorageTo?: true
  Initial?: true
  Expected?: true
  Committed?: true
  Completed?: true
  Supplier?: true
  Customer?: true
  Owner?: true
  IdentProduct?: true
  IdentStorage?: true
  IdentStorageTo?: true
  IdentSupplier?: true
  IdentCustomer?: true
  IdentAddressLocation?: true
  IdentAddressBill?: true
  IdentAddressShip?: true
  _all?: true
}

export type DPurchaseOrderAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which dPurchaseOrder to aggregate.
   */
  where?: Prisma.dPurchaseOrderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of dPurchaseOrders to fetch.
   */
  orderBy?: Prisma.dPurchaseOrderOrderByWithRelationInput | Prisma.dPurchaseOrderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.dPurchaseOrderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` dPurchaseOrders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` dPurchaseOrders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned dPurchaseOrders
  **/
  _count?: true | DPurchaseOrderCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: DPurchaseOrderAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: DPurchaseOrderSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DPurchaseOrderMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DPurchaseOrderMaxAggregateInputType
}

export type GetDPurchaseOrderAggregateType<T extends DPurchaseOrderAggregateArgs> = {
      [P in keyof T & keyof AggregateDPurchaseOrder]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDPurchaseOrder[P]>
    : Prisma.GetScalarType<T[P], AggregateDPurchaseOrder[P]>
}




export type dPurchaseOrderGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.dPurchaseOrderWhereInput
  orderBy?: Prisma.dPurchaseOrderOrderByWithAggregationInput | Prisma.dPurchaseOrderOrderByWithAggregationInput[]
  by: Prisma.DPurchaseOrderScalarFieldEnum[] | Prisma.DPurchaseOrderScalarFieldEnum
  having?: Prisma.dPurchaseOrderScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DPurchaseOrderCountAggregateInputType | true
  _avg?: DPurchaseOrderAvgAggregateInputType
  _sum?: DPurchaseOrderSumAggregateInputType
  _min?: DPurchaseOrderMinAggregateInputType
  _max?: DPurchaseOrderMaxAggregateInputType
}

export type DPurchaseOrderGroupByOutputType = {
  Identifier: number
  Status: string
  Creation: Date
  CreationID: number
  Maintenance: Date
  MaintenanceID: number
  PurchaseOrder: string
  ImportDate: Date | null
  ExportDate: Date | null
  ExternalID: number | null
  LineID: number | null
  CommitID: number | null
  ItemID: number | null
  Type: string
  Line: number | null
  ItemNumber: string | null
  Quantity: runtime.Decimal | null
  QuantityCommit: runtime.Decimal | null
  UOM: string | null
  UOMCommit: string | null
  Weight: runtime.Decimal | null
  UOMWeight: string | null
  Lot: string | null
  Storage: string | null
  StorageTo: string | null
  Initial: Date
  Expected: Date | null
  Committed: Date | null
  Completed: Date | null
  Supplier: string | null
  Customer: string | null
  Owner: string | null
  IdentProduct: number
  IdentStorage: number
  IdentStorageTo: number
  IdentSupplier: number
  IdentCustomer: number
  IdentAddressLocation: number
  IdentAddressBill: number
  IdentAddressShip: number
  _count: DPurchaseOrderCountAggregateOutputType | null
  _avg: DPurchaseOrderAvgAggregateOutputType | null
  _sum: DPurchaseOrderSumAggregateOutputType | null
  _min: DPurchaseOrderMinAggregateOutputType | null
  _max: DPurchaseOrderMaxAggregateOutputType | null
}

type GetDPurchaseOrderGroupByPayload<T extends dPurchaseOrderGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DPurchaseOrderGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DPurchaseOrderGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DPurchaseOrderGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DPurchaseOrderGroupByOutputType[P]>
      }
    >
  >



export type dPurchaseOrderWhereInput = {
  AND?: Prisma.dPurchaseOrderWhereInput | Prisma.dPurchaseOrderWhereInput[]
  OR?: Prisma.dPurchaseOrderWhereInput[]
  NOT?: Prisma.dPurchaseOrderWhereInput | Prisma.dPurchaseOrderWhereInput[]
  Identifier?: Prisma.IntFilter<"dPurchaseOrder"> | number
  Status?: Prisma.StringFilter<"dPurchaseOrder"> | string
  Creation?: Prisma.DateTimeFilter<"dPurchaseOrder"> | Date | string
  CreationID?: Prisma.IntFilter<"dPurchaseOrder"> | number
  Maintenance?: Prisma.DateTimeFilter<"dPurchaseOrder"> | Date | string
  MaintenanceID?: Prisma.IntFilter<"dPurchaseOrder"> | number
  PurchaseOrder?: Prisma.StringFilter<"dPurchaseOrder"> | string
  ImportDate?: Prisma.DateTimeNullableFilter<"dPurchaseOrder"> | Date | string | null
  ExportDate?: Prisma.DateTimeNullableFilter<"dPurchaseOrder"> | Date | string | null
  ExternalID?: Prisma.IntNullableFilter<"dPurchaseOrder"> | number | null
  LineID?: Prisma.IntNullableFilter<"dPurchaseOrder"> | number | null
  CommitID?: Prisma.IntNullableFilter<"dPurchaseOrder"> | number | null
  ItemID?: Prisma.IntNullableFilter<"dPurchaseOrder"> | number | null
  Type?: Prisma.StringFilter<"dPurchaseOrder"> | string
  Line?: Prisma.IntNullableFilter<"dPurchaseOrder"> | number | null
  ItemNumber?: Prisma.StringNullableFilter<"dPurchaseOrder"> | string | null
  Quantity?: Prisma.DecimalNullableFilter<"dPurchaseOrder"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  QuantityCommit?: Prisma.DecimalNullableFilter<"dPurchaseOrder"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  UOM?: Prisma.StringNullableFilter<"dPurchaseOrder"> | string | null
  UOMCommit?: Prisma.StringNullableFilter<"dPurchaseOrder"> | string | null
  Weight?: Prisma.DecimalNullableFilter<"dPurchaseOrder"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  UOMWeight?: Prisma.StringNullableFilter<"dPurchaseOrder"> | string | null
  Lot?: Prisma.StringNullableFilter<"dPurchaseOrder"> | string | null
  Storage?: Prisma.StringNullableFilter<"dPurchaseOrder"> | string | null
  StorageTo?: Prisma.StringNullableFilter<"dPurchaseOrder"> | string | null
  Initial?: Prisma.DateTimeFilter<"dPurchaseOrder"> | Date | string
  Expected?: Prisma.DateTimeNullableFilter<"dPurchaseOrder"> | Date | string | null
  Committed?: Prisma.DateTimeNullableFilter<"dPurchaseOrder"> | Date | string | null
  Completed?: Prisma.DateTimeNullableFilter<"dPurchaseOrder"> | Date | string | null
  Supplier?: Prisma.StringNullableFilter<"dPurchaseOrder"> | string | null
  Customer?: Prisma.StringNullableFilter<"dPurchaseOrder"> | string | null
  Owner?: Prisma.StringNullableFilter<"dPurchaseOrder"> | string | null
  IdentProduct?: Prisma.IntFilter<"dPurchaseOrder"> | number
  IdentStorage?: Prisma.IntFilter<"dPurchaseOrder"> | number
  IdentStorageTo?: Prisma.IntFilter<"dPurchaseOrder"> | number
  IdentSupplier?: Prisma.IntFilter<"dPurchaseOrder"> | number
  IdentCustomer?: Prisma.IntFilter<"dPurchaseOrder"> | number
  IdentAddressLocation?: Prisma.IntFilter<"dPurchaseOrder"> | number
  IdentAddressBill?: Prisma.IntFilter<"dPurchaseOrder"> | number
  IdentAddressShip?: Prisma.IntFilter<"dPurchaseOrder"> | number
}

export type dPurchaseOrderOrderByWithRelationInput = {
  Identifier?: Prisma.SortOrder
  Status?: Prisma.SortOrder
  Creation?: Prisma.SortOrder
  CreationID?: Prisma.SortOrder
  Maintenance?: Prisma.SortOrder
  MaintenanceID?: Prisma.SortOrder
  PurchaseOrder?: Prisma.SortOrder
  ImportDate?: Prisma.SortOrderInput | Prisma.SortOrder
  ExportDate?: Prisma.SortOrderInput | Prisma.SortOrder
  ExternalID?: Prisma.SortOrderInput | Prisma.SortOrder
  LineID?: Prisma.SortOrderInput | Prisma.SortOrder
  CommitID?: Prisma.SortOrderInput | Prisma.SortOrder
  ItemID?: Prisma.SortOrderInput | Prisma.SortOrder
  Type?: Prisma.SortOrder
  Line?: Prisma.SortOrderInput | Prisma.SortOrder
  ItemNumber?: Prisma.SortOrderInput | Prisma.SortOrder
  Quantity?: Prisma.SortOrderInput | Prisma.SortOrder
  QuantityCommit?: Prisma.SortOrderInput | Prisma.SortOrder
  UOM?: Prisma.SortOrderInput | Prisma.SortOrder
  UOMCommit?: Prisma.SortOrderInput | Prisma.SortOrder
  Weight?: Prisma.SortOrderInput | Prisma.SortOrder
  UOMWeight?: Prisma.SortOrderInput | Prisma.SortOrder
  Lot?: Prisma.SortOrderInput | Prisma.SortOrder
  Storage?: Prisma.SortOrderInput | Prisma.SortOrder
  StorageTo?: Prisma.SortOrderInput | Prisma.SortOrder
  Initial?: Prisma.SortOrder
  Expected?: Prisma.SortOrderInput | Prisma.SortOrder
  Committed?: Prisma.SortOrderInput | Prisma.SortOrder
  Completed?: Prisma.SortOrderInput | Prisma.SortOrder
  Supplier?: Prisma.SortOrderInput | Prisma.SortOrder
  Customer?: Prisma.SortOrderInput | Prisma.SortOrder
  Owner?: Prisma.SortOrderInput | Prisma.SortOrder
  IdentProduct?: Prisma.SortOrder
  IdentStorage?: Prisma.SortOrder
  IdentStorageTo?: Prisma.SortOrder
  IdentSupplier?: Prisma.SortOrder
  IdentCustomer?: Prisma.SortOrder
  IdentAddressLocation?: Prisma.SortOrder
  IdentAddressBill?: Prisma.SortOrder
  IdentAddressShip?: Prisma.SortOrder
}

export type dPurchaseOrderWhereUniqueInput = Prisma.AtLeast<{
  Identifier?: number
  PurchaseOrder_Line_ItemNumber?: Prisma.dPurchaseOrderPurchaseOrderLineItemNumberCompoundUniqueInput
  AND?: Prisma.dPurchaseOrderWhereInput | Prisma.dPurchaseOrderWhereInput[]
  OR?: Prisma.dPurchaseOrderWhereInput[]
  NOT?: Prisma.dPurchaseOrderWhereInput | Prisma.dPurchaseOrderWhereInput[]
  Status?: Prisma.StringFilter<"dPurchaseOrder"> | string
  Creation?: Prisma.DateTimeFilter<"dPurchaseOrder"> | Date | string
  CreationID?: Prisma.IntFilter<"dPurchaseOrder"> | number
  Maintenance?: Prisma.DateTimeFilter<"dPurchaseOrder"> | Date | string
  MaintenanceID?: Prisma.IntFilter<"dPurchaseOrder"> | number
  PurchaseOrder?: Prisma.StringFilter<"dPurchaseOrder"> | string
  ImportDate?: Prisma.DateTimeNullableFilter<"dPurchaseOrder"> | Date | string | null
  ExportDate?: Prisma.DateTimeNullableFilter<"dPurchaseOrder"> | Date | string | null
  ExternalID?: Prisma.IntNullableFilter<"dPurchaseOrder"> | number | null
  LineID?: Prisma.IntNullableFilter<"dPurchaseOrder"> | number | null
  CommitID?: Prisma.IntNullableFilter<"dPurchaseOrder"> | number | null
  ItemID?: Prisma.IntNullableFilter<"dPurchaseOrder"> | number | null
  Type?: Prisma.StringFilter<"dPurchaseOrder"> | string
  Line?: Prisma.IntNullableFilter<"dPurchaseOrder"> | number | null
  ItemNumber?: Prisma.StringNullableFilter<"dPurchaseOrder"> | string | null
  Quantity?: Prisma.DecimalNullableFilter<"dPurchaseOrder"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  QuantityCommit?: Prisma.DecimalNullableFilter<"dPurchaseOrder"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  UOM?: Prisma.StringNullableFilter<"dPurchaseOrder"> | string | null
  UOMCommit?: Prisma.StringNullableFilter<"dPurchaseOrder"> | string | null
  Weight?: Prisma.DecimalNullableFilter<"dPurchaseOrder"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  UOMWeight?: Prisma.StringNullableFilter<"dPurchaseOrder"> | string | null
  Lot?: Prisma.StringNullableFilter<"dPurchaseOrder"> | string | null
  Storage?: Prisma.StringNullableFilter<"dPurchaseOrder"> | string | null
  StorageTo?: Prisma.StringNullableFilter<"dPurchaseOrder"> | string | null
  Initial?: Prisma.DateTimeFilter<"dPurchaseOrder"> | Date | string
  Expected?: Prisma.DateTimeNullableFilter<"dPurchaseOrder"> | Date | string | null
  Committed?: Prisma.DateTimeNullableFilter<"dPurchaseOrder"> | Date | string | null
  Completed?: Prisma.DateTimeNullableFilter<"dPurchaseOrder"> | Date | string | null
  Supplier?: Prisma.StringNullableFilter<"dPurchaseOrder"> | string | null
  Customer?: Prisma.StringNullableFilter<"dPurchaseOrder"> | string | null
  Owner?: Prisma.StringNullableFilter<"dPurchaseOrder"> | string | null
  IdentProduct?: Prisma.IntFilter<"dPurchaseOrder"> | number
  IdentStorage?: Prisma.IntFilter<"dPurchaseOrder"> | number
  IdentStorageTo?: Prisma.IntFilter<"dPurchaseOrder"> | number
  IdentSupplier?: Prisma.IntFilter<"dPurchaseOrder"> | number
  IdentCustomer?: Prisma.IntFilter<"dPurchaseOrder"> | number
  IdentAddressLocation?: Prisma.IntFilter<"dPurchaseOrder"> | number
  IdentAddressBill?: Prisma.IntFilter<"dPurchaseOrder"> | number
  IdentAddressShip?: Prisma.IntFilter<"dPurchaseOrder"> | number
}, "Identifier" | "PurchaseOrder_Line_ItemNumber">

export type dPurchaseOrderOrderByWithAggregationInput = {
  Identifier?: Prisma.SortOrder
  Status?: Prisma.SortOrder
  Creation?: Prisma.SortOrder
  CreationID?: Prisma.SortOrder
  Maintenance?: Prisma.SortOrder
  MaintenanceID?: Prisma.SortOrder
  PurchaseOrder?: Prisma.SortOrder
  ImportDate?: Prisma.SortOrderInput | Prisma.SortOrder
  ExportDate?: Prisma.SortOrderInput | Prisma.SortOrder
  ExternalID?: Prisma.SortOrderInput | Prisma.SortOrder
  LineID?: Prisma.SortOrderInput | Prisma.SortOrder
  CommitID?: Prisma.SortOrderInput | Prisma.SortOrder
  ItemID?: Prisma.SortOrderInput | Prisma.SortOrder
  Type?: Prisma.SortOrder
  Line?: Prisma.SortOrderInput | Prisma.SortOrder
  ItemNumber?: Prisma.SortOrderInput | Prisma.SortOrder
  Quantity?: Prisma.SortOrderInput | Prisma.SortOrder
  QuantityCommit?: Prisma.SortOrderInput | Prisma.SortOrder
  UOM?: Prisma.SortOrderInput | Prisma.SortOrder
  UOMCommit?: Prisma.SortOrderInput | Prisma.SortOrder
  Weight?: Prisma.SortOrderInput | Prisma.SortOrder
  UOMWeight?: Prisma.SortOrderInput | Prisma.SortOrder
  Lot?: Prisma.SortOrderInput | Prisma.SortOrder
  Storage?: Prisma.SortOrderInput | Prisma.SortOrder
  StorageTo?: Prisma.SortOrderInput | Prisma.SortOrder
  Initial?: Prisma.SortOrder
  Expected?: Prisma.SortOrderInput | Prisma.SortOrder
  Committed?: Prisma.SortOrderInput | Prisma.SortOrder
  Completed?: Prisma.SortOrderInput | Prisma.SortOrder
  Supplier?: Prisma.SortOrderInput | Prisma.SortOrder
  Customer?: Prisma.SortOrderInput | Prisma.SortOrder
  Owner?: Prisma.SortOrderInput | Prisma.SortOrder
  IdentProduct?: Prisma.SortOrder
  IdentStorage?: Prisma.SortOrder
  IdentStorageTo?: Prisma.SortOrder
  IdentSupplier?: Prisma.SortOrder
  IdentCustomer?: Prisma.SortOrder
  IdentAddressLocation?: Prisma.SortOrder
  IdentAddressBill?: Prisma.SortOrder
  IdentAddressShip?: Prisma.SortOrder
  _count?: Prisma.dPurchaseOrderCountOrderByAggregateInput
  _avg?: Prisma.dPurchaseOrderAvgOrderByAggregateInput
  _max?: Prisma.dPurchaseOrderMaxOrderByAggregateInput
  _min?: Prisma.dPurchaseOrderMinOrderByAggregateInput
  _sum?: Prisma.dPurchaseOrderSumOrderByAggregateInput
}

export type dPurchaseOrderScalarWhereWithAggregatesInput = {
  AND?: Prisma.dPurchaseOrderScalarWhereWithAggregatesInput | Prisma.dPurchaseOrderScalarWhereWithAggregatesInput[]
  OR?: Prisma.dPurchaseOrderScalarWhereWithAggregatesInput[]
  NOT?: Prisma.dPurchaseOrderScalarWhereWithAggregatesInput | Prisma.dPurchaseOrderScalarWhereWithAggregatesInput[]
  Identifier?: Prisma.IntWithAggregatesFilter<"dPurchaseOrder"> | number
  Status?: Prisma.StringWithAggregatesFilter<"dPurchaseOrder"> | string
  Creation?: Prisma.DateTimeWithAggregatesFilter<"dPurchaseOrder"> | Date | string
  CreationID?: Prisma.IntWithAggregatesFilter<"dPurchaseOrder"> | number
  Maintenance?: Prisma.DateTimeWithAggregatesFilter<"dPurchaseOrder"> | Date | string
  MaintenanceID?: Prisma.IntWithAggregatesFilter<"dPurchaseOrder"> | number
  PurchaseOrder?: Prisma.StringWithAggregatesFilter<"dPurchaseOrder"> | string
  ImportDate?: Prisma.DateTimeNullableWithAggregatesFilter<"dPurchaseOrder"> | Date | string | null
  ExportDate?: Prisma.DateTimeNullableWithAggregatesFilter<"dPurchaseOrder"> | Date | string | null
  ExternalID?: Prisma.IntNullableWithAggregatesFilter<"dPurchaseOrder"> | number | null
  LineID?: Prisma.IntNullableWithAggregatesFilter<"dPurchaseOrder"> | number | null
  CommitID?: Prisma.IntNullableWithAggregatesFilter<"dPurchaseOrder"> | number | null
  ItemID?: Prisma.IntNullableWithAggregatesFilter<"dPurchaseOrder"> | number | null
  Type?: Prisma.StringWithAggregatesFilter<"dPurchaseOrder"> | string
  Line?: Prisma.IntNullableWithAggregatesFilter<"dPurchaseOrder"> | number | null
  ItemNumber?: Prisma.StringNullableWithAggregatesFilter<"dPurchaseOrder"> | string | null
  Quantity?: Prisma.DecimalNullableWithAggregatesFilter<"dPurchaseOrder"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  QuantityCommit?: Prisma.DecimalNullableWithAggregatesFilter<"dPurchaseOrder"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  UOM?: Prisma.StringNullableWithAggregatesFilter<"dPurchaseOrder"> | string | null
  UOMCommit?: Prisma.StringNullableWithAggregatesFilter<"dPurchaseOrder"> | string | null
  Weight?: Prisma.DecimalNullableWithAggregatesFilter<"dPurchaseOrder"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  UOMWeight?: Prisma.StringNullableWithAggregatesFilter<"dPurchaseOrder"> | string | null
  Lot?: Prisma.StringNullableWithAggregatesFilter<"dPurchaseOrder"> | string | null
  Storage?: Prisma.StringNullableWithAggregatesFilter<"dPurchaseOrder"> | string | null
  StorageTo?: Prisma.StringNullableWithAggregatesFilter<"dPurchaseOrder"> | string | null
  Initial?: Prisma.DateTimeWithAggregatesFilter<"dPurchaseOrder"> | Date | string
  Expected?: Prisma.DateTimeNullableWithAggregatesFilter<"dPurchaseOrder"> | Date | string | null
  Committed?: Prisma.DateTimeNullableWithAggregatesFilter<"dPurchaseOrder"> | Date | string | null
  Completed?: Prisma.DateTimeNullableWithAggregatesFilter<"dPurchaseOrder"> | Date | string | null
  Supplier?: Prisma.StringNullableWithAggregatesFilter<"dPurchaseOrder"> | string | null
  Customer?: Prisma.StringNullableWithAggregatesFilter<"dPurchaseOrder"> | string | null
  Owner?: Prisma.StringNullableWithAggregatesFilter<"dPurchaseOrder"> | string | null
  IdentProduct?: Prisma.IntWithAggregatesFilter<"dPurchaseOrder"> | number
  IdentStorage?: Prisma.IntWithAggregatesFilter<"dPurchaseOrder"> | number
  IdentStorageTo?: Prisma.IntWithAggregatesFilter<"dPurchaseOrder"> | number
  IdentSupplier?: Prisma.IntWithAggregatesFilter<"dPurchaseOrder"> | number
  IdentCustomer?: Prisma.IntWithAggregatesFilter<"dPurchaseOrder"> | number
  IdentAddressLocation?: Prisma.IntWithAggregatesFilter<"dPurchaseOrder"> | number
  IdentAddressBill?: Prisma.IntWithAggregatesFilter<"dPurchaseOrder"> | number
  IdentAddressShip?: Prisma.IntWithAggregatesFilter<"dPurchaseOrder"> | number
}

export type dPurchaseOrderCreateInput = {
  Status?: string
  Creation?: Date | string
  CreationID?: number
  Maintenance?: Date | string
  MaintenanceID?: number
  PurchaseOrder: string
  ImportDate?: Date | string | null
  ExportDate?: Date | string | null
  ExternalID?: number | null
  LineID?: number | null
  CommitID?: number | null
  ItemID?: number | null
  Type?: string
  Line?: number | null
  ItemNumber?: string | null
  Quantity?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  QuantityCommit?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  UOM?: string | null
  UOMCommit?: string | null
  Weight?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  UOMWeight?: string | null
  Lot?: string | null
  Storage?: string | null
  StorageTo?: string | null
  Initial?: Date | string
  Expected?: Date | string | null
  Committed?: Date | string | null
  Completed?: Date | string | null
  Supplier?: string | null
  Customer?: string | null
  Owner?: string | null
  IdentProduct?: number
  IdentStorage?: number
  IdentStorageTo?: number
  IdentSupplier?: number
  IdentCustomer?: number
  IdentAddressLocation?: number
  IdentAddressBill?: number
  IdentAddressShip?: number
}

export type dPurchaseOrderUncheckedCreateInput = {
  Identifier?: number
  Status?: string
  Creation?: Date | string
  CreationID?: number
  Maintenance?: Date | string
  MaintenanceID?: number
  PurchaseOrder: string
  ImportDate?: Date | string | null
  ExportDate?: Date | string | null
  ExternalID?: number | null
  LineID?: number | null
  CommitID?: number | null
  ItemID?: number | null
  Type?: string
  Line?: number | null
  ItemNumber?: string | null
  Quantity?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  QuantityCommit?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  UOM?: string | null
  UOMCommit?: string | null
  Weight?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  UOMWeight?: string | null
  Lot?: string | null
  Storage?: string | null
  StorageTo?: string | null
  Initial?: Date | string
  Expected?: Date | string | null
  Committed?: Date | string | null
  Completed?: Date | string | null
  Supplier?: string | null
  Customer?: string | null
  Owner?: string | null
  IdentProduct?: number
  IdentStorage?: number
  IdentStorageTo?: number
  IdentSupplier?: number
  IdentCustomer?: number
  IdentAddressLocation?: number
  IdentAddressBill?: number
  IdentAddressShip?: number
}

export type dPurchaseOrderUpdateInput = {
  Status?: Prisma.StringFieldUpdateOperationsInput | string
  Creation?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  CreationID?: Prisma.IntFieldUpdateOperationsInput | number
  Maintenance?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  MaintenanceID?: Prisma.IntFieldUpdateOperationsInput | number
  PurchaseOrder?: Prisma.StringFieldUpdateOperationsInput | string
  ImportDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  ExportDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  ExternalID?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  LineID?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  CommitID?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  ItemID?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  Type?: Prisma.StringFieldUpdateOperationsInput | string
  Line?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  ItemNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Quantity?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  QuantityCommit?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  UOM?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  UOMCommit?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Weight?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  UOMWeight?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Lot?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Storage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  StorageTo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Initial?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Expected?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  Committed?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  Completed?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  Supplier?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Customer?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Owner?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  IdentProduct?: Prisma.IntFieldUpdateOperationsInput | number
  IdentStorage?: Prisma.IntFieldUpdateOperationsInput | number
  IdentStorageTo?: Prisma.IntFieldUpdateOperationsInput | number
  IdentSupplier?: Prisma.IntFieldUpdateOperationsInput | number
  IdentCustomer?: Prisma.IntFieldUpdateOperationsInput | number
  IdentAddressLocation?: Prisma.IntFieldUpdateOperationsInput | number
  IdentAddressBill?: Prisma.IntFieldUpdateOperationsInput | number
  IdentAddressShip?: Prisma.IntFieldUpdateOperationsInput | number
}

export type dPurchaseOrderUncheckedUpdateInput = {
  Identifier?: Prisma.IntFieldUpdateOperationsInput | number
  Status?: Prisma.StringFieldUpdateOperationsInput | string
  Creation?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  CreationID?: Prisma.IntFieldUpdateOperationsInput | number
  Maintenance?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  MaintenanceID?: Prisma.IntFieldUpdateOperationsInput | number
  PurchaseOrder?: Prisma.StringFieldUpdateOperationsInput | string
  ImportDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  ExportDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  ExternalID?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  LineID?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  CommitID?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  ItemID?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  Type?: Prisma.StringFieldUpdateOperationsInput | string
  Line?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  ItemNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Quantity?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  QuantityCommit?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  UOM?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  UOMCommit?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Weight?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  UOMWeight?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Lot?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Storage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  StorageTo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Initial?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Expected?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  Committed?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  Completed?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  Supplier?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Customer?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Owner?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  IdentProduct?: Prisma.IntFieldUpdateOperationsInput | number
  IdentStorage?: Prisma.IntFieldUpdateOperationsInput | number
  IdentStorageTo?: Prisma.IntFieldUpdateOperationsInput | number
  IdentSupplier?: Prisma.IntFieldUpdateOperationsInput | number
  IdentCustomer?: Prisma.IntFieldUpdateOperationsInput | number
  IdentAddressLocation?: Prisma.IntFieldUpdateOperationsInput | number
  IdentAddressBill?: Prisma.IntFieldUpdateOperationsInput | number
  IdentAddressShip?: Prisma.IntFieldUpdateOperationsInput | number
}

export type dPurchaseOrderCreateManyInput = {
  Status?: string
  Creation?: Date | string
  CreationID?: number
  Maintenance?: Date | string
  MaintenanceID?: number
  PurchaseOrder: string
  ImportDate?: Date | string | null
  ExportDate?: Date | string | null
  ExternalID?: number | null
  LineID?: number | null
  CommitID?: number | null
  ItemID?: number | null
  Type?: string
  Line?: number | null
  ItemNumber?: string | null
  Quantity?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  QuantityCommit?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  UOM?: string | null
  UOMCommit?: string | null
  Weight?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  UOMWeight?: string | null
  Lot?: string | null
  Storage?: string | null
  StorageTo?: string | null
  Initial?: Date | string
  Expected?: Date | string | null
  Committed?: Date | string | null
  Completed?: Date | string | null
  Supplier?: string | null
  Customer?: string | null
  Owner?: string | null
  IdentProduct?: number
  IdentStorage?: number
  IdentStorageTo?: number
  IdentSupplier?: number
  IdentCustomer?: number
  IdentAddressLocation?: number
  IdentAddressBill?: number
  IdentAddressShip?: number
}

export type dPurchaseOrderUpdateManyMutationInput = {
  Status?: Prisma.StringFieldUpdateOperationsInput | string
  Creation?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  CreationID?: Prisma.IntFieldUpdateOperationsInput | number
  Maintenance?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  MaintenanceID?: Prisma.IntFieldUpdateOperationsInput | number
  PurchaseOrder?: Prisma.StringFieldUpdateOperationsInput | string
  ImportDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  ExportDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  ExternalID?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  LineID?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  CommitID?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  ItemID?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  Type?: Prisma.StringFieldUpdateOperationsInput | string
  Line?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  ItemNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Quantity?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  QuantityCommit?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  UOM?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  UOMCommit?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Weight?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  UOMWeight?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Lot?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Storage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  StorageTo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Initial?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Expected?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  Committed?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  Completed?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  Supplier?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Customer?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Owner?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  IdentProduct?: Prisma.IntFieldUpdateOperationsInput | number
  IdentStorage?: Prisma.IntFieldUpdateOperationsInput | number
  IdentStorageTo?: Prisma.IntFieldUpdateOperationsInput | number
  IdentSupplier?: Prisma.IntFieldUpdateOperationsInput | number
  IdentCustomer?: Prisma.IntFieldUpdateOperationsInput | number
  IdentAddressLocation?: Prisma.IntFieldUpdateOperationsInput | number
  IdentAddressBill?: Prisma.IntFieldUpdateOperationsInput | number
  IdentAddressShip?: Prisma.IntFieldUpdateOperationsInput | number
}

export type dPurchaseOrderUncheckedUpdateManyInput = {
  Identifier?: Prisma.IntFieldUpdateOperationsInput | number
  Status?: Prisma.StringFieldUpdateOperationsInput | string
  Creation?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  CreationID?: Prisma.IntFieldUpdateOperationsInput | number
  Maintenance?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  MaintenanceID?: Prisma.IntFieldUpdateOperationsInput | number
  PurchaseOrder?: Prisma.StringFieldUpdateOperationsInput | string
  ImportDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  ExportDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  ExternalID?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  LineID?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  CommitID?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  ItemID?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  Type?: Prisma.StringFieldUpdateOperationsInput | string
  Line?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  ItemNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Quantity?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  QuantityCommit?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  UOM?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  UOMCommit?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Weight?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  UOMWeight?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Lot?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Storage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  StorageTo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Initial?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Expected?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  Committed?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  Completed?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  Supplier?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Customer?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Owner?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  IdentProduct?: Prisma.IntFieldUpdateOperationsInput | number
  IdentStorage?: Prisma.IntFieldUpdateOperationsInput | number
  IdentStorageTo?: Prisma.IntFieldUpdateOperationsInput | number
  IdentSupplier?: Prisma.IntFieldUpdateOperationsInput | number
  IdentCustomer?: Prisma.IntFieldUpdateOperationsInput | number
  IdentAddressLocation?: Prisma.IntFieldUpdateOperationsInput | number
  IdentAddressBill?: Prisma.IntFieldUpdateOperationsInput | number
  IdentAddressShip?: Prisma.IntFieldUpdateOperationsInput | number
}

export type dPurchaseOrderPurchaseOrderLineItemNumberCompoundUniqueInput = {
  PurchaseOrder: string
  Line: number
  ItemNumber: string
}

export type dPurchaseOrderCountOrderByAggregateInput = {
  Identifier?: Prisma.SortOrder
  Status?: Prisma.SortOrder
  Creation?: Prisma.SortOrder
  CreationID?: Prisma.SortOrder
  Maintenance?: Prisma.SortOrder
  MaintenanceID?: Prisma.SortOrder
  PurchaseOrder?: Prisma.SortOrder
  ImportDate?: Prisma.SortOrder
  ExportDate?: Prisma.SortOrder
  ExternalID?: Prisma.SortOrder
  LineID?: Prisma.SortOrder
  CommitID?: Prisma.SortOrder
  ItemID?: Prisma.SortOrder
  Type?: Prisma.SortOrder
  Line?: Prisma.SortOrder
  ItemNumber?: Prisma.SortOrder
  Quantity?: Prisma.SortOrder
  QuantityCommit?: Prisma.SortOrder
  UOM?: Prisma.SortOrder
  UOMCommit?: Prisma.SortOrder
  Weight?: Prisma.SortOrder
  UOMWeight?: Prisma.SortOrder
  Lot?: Prisma.SortOrder
  Storage?: Prisma.SortOrder
  StorageTo?: Prisma.SortOrder
  Initial?: Prisma.SortOrder
  Expected?: Prisma.SortOrder
  Committed?: Prisma.SortOrder
  Completed?: Prisma.SortOrder
  Supplier?: Prisma.SortOrder
  Customer?: Prisma.SortOrder
  Owner?: Prisma.SortOrder
  IdentProduct?: Prisma.SortOrder
  IdentStorage?: Prisma.SortOrder
  IdentStorageTo?: Prisma.SortOrder
  IdentSupplier?: Prisma.SortOrder
  IdentCustomer?: Prisma.SortOrder
  IdentAddressLocation?: Prisma.SortOrder
  IdentAddressBill?: Prisma.SortOrder
  IdentAddressShip?: Prisma.SortOrder
}

export type dPurchaseOrderAvgOrderByAggregateInput = {
  Identifier?: Prisma.SortOrder
  CreationID?: Prisma.SortOrder
  MaintenanceID?: Prisma.SortOrder
  ExternalID?: Prisma.SortOrder
  LineID?: Prisma.SortOrder
  CommitID?: Prisma.SortOrder
  ItemID?: Prisma.SortOrder
  Line?: Prisma.SortOrder
  Quantity?: Prisma.SortOrder
  QuantityCommit?: Prisma.SortOrder
  Weight?: Prisma.SortOrder
  IdentProduct?: Prisma.SortOrder
  IdentStorage?: Prisma.SortOrder
  IdentStorageTo?: Prisma.SortOrder
  IdentSupplier?: Prisma.SortOrder
  IdentCustomer?: Prisma.SortOrder
  IdentAddressLocation?: Prisma.SortOrder
  IdentAddressBill?: Prisma.SortOrder
  IdentAddressShip?: Prisma.SortOrder
}

export type dPurchaseOrderMaxOrderByAggregateInput = {
  Identifier?: Prisma.SortOrder
  Status?: Prisma.SortOrder
  Creation?: Prisma.SortOrder
  CreationID?: Prisma.SortOrder
  Maintenance?: Prisma.SortOrder
  MaintenanceID?: Prisma.SortOrder
  PurchaseOrder?: Prisma.SortOrder
  ImportDate?: Prisma.SortOrder
  ExportDate?: Prisma.SortOrder
  ExternalID?: Prisma.SortOrder
  LineID?: Prisma.SortOrder
  CommitID?: Prisma.SortOrder
  ItemID?: Prisma.SortOrder
  Type?: Prisma.SortOrder
  Line?: Prisma.SortOrder
  ItemNumber?: Prisma.SortOrder
  Quantity?: Prisma.SortOrder
  QuantityCommit?: Prisma.SortOrder
  UOM?: Prisma.SortOrder
  UOMCommit?: Prisma.SortOrder
  Weight?: Prisma.SortOrder
  UOMWeight?: Prisma.SortOrder
  Lot?: Prisma.SortOrder
  Storage?: Prisma.SortOrder
  StorageTo?: Prisma.SortOrder
  Initial?: Prisma.SortOrder
  Expected?: Prisma.SortOrder
  Committed?: Prisma.SortOrder
  Completed?: Prisma.SortOrder
  Supplier?: Prisma.SortOrder
  Customer?: Prisma.SortOrder
  Owner?: Prisma.SortOrder
  IdentProduct?: Prisma.SortOrder
  IdentStorage?: Prisma.SortOrder
  IdentStorageTo?: Prisma.SortOrder
  IdentSupplier?: Prisma.SortOrder
  IdentCustomer?: Prisma.SortOrder
  IdentAddressLocation?: Prisma.SortOrder
  IdentAddressBill?: Prisma.SortOrder
  IdentAddressShip?: Prisma.SortOrder
}

export type dPurchaseOrderMinOrderByAggregateInput = {
  Identifier?: Prisma.SortOrder
  Status?: Prisma.SortOrder
  Creation?: Prisma.SortOrder
  CreationID?: Prisma.SortOrder
  Maintenance?: Prisma.SortOrder
  MaintenanceID?: Prisma.SortOrder
  PurchaseOrder?: Prisma.SortOrder
  ImportDate?: Prisma.SortOrder
  ExportDate?: Prisma.SortOrder
  ExternalID?: Prisma.SortOrder
  LineID?: Prisma.SortOrder
  CommitID?: Prisma.SortOrder
  ItemID?: Prisma.SortOrder
  Type?: Prisma.SortOrder
  Line?: Prisma.SortOrder
  ItemNumber?: Prisma.SortOrder
  Quantity?: Prisma.SortOrder
  QuantityCommit?: Prisma.SortOrder
  UOM?: Prisma.SortOrder
  UOMCommit?: Prisma.SortOrder
  Weight?: Prisma.SortOrder
  UOMWeight?: Prisma.SortOrder
  Lot?: Prisma.SortOrder
  Storage?: Prisma.SortOrder
  StorageTo?: Prisma.SortOrder
  Initial?: Prisma.SortOrder
  Expected?: Prisma.SortOrder
  Committed?: Prisma.SortOrder
  Completed?: Prisma.SortOrder
  Supplier?: Prisma.SortOrder
  Customer?: Prisma.SortOrder
  Owner?: Prisma.SortOrder
  IdentProduct?: Prisma.SortOrder
  IdentStorage?: Prisma.SortOrder
  IdentStorageTo?: Prisma.SortOrder
  IdentSupplier?: Prisma.SortOrder
  IdentCustomer?: Prisma.SortOrder
  IdentAddressLocation?: Prisma.SortOrder
  IdentAddressBill?: Prisma.SortOrder
  IdentAddressShip?: Prisma.SortOrder
}

export type dPurchaseOrderSumOrderByAggregateInput = {
  Identifier?: Prisma.SortOrder
  CreationID?: Prisma.SortOrder
  MaintenanceID?: Prisma.SortOrder
  ExternalID?: Prisma.SortOrder
  LineID?: Prisma.SortOrder
  CommitID?: Prisma.SortOrder
  ItemID?: Prisma.SortOrder
  Line?: Prisma.SortOrder
  Quantity?: Prisma.SortOrder
  QuantityCommit?: Prisma.SortOrder
  Weight?: Prisma.SortOrder
  IdentProduct?: Prisma.SortOrder
  IdentStorage?: Prisma.SortOrder
  IdentStorageTo?: Prisma.SortOrder
  IdentSupplier?: Prisma.SortOrder
  IdentCustomer?: Prisma.SortOrder
  IdentAddressLocation?: Prisma.SortOrder
  IdentAddressBill?: Prisma.SortOrder
  IdentAddressShip?: Prisma.SortOrder
}



export type dPurchaseOrderSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  Identifier?: boolean
  Status?: boolean
  Creation?: boolean
  CreationID?: boolean
  Maintenance?: boolean
  MaintenanceID?: boolean
  PurchaseOrder?: boolean
  ImportDate?: boolean
  ExportDate?: boolean
  ExternalID?: boolean
  LineID?: boolean
  CommitID?: boolean
  ItemID?: boolean
  Type?: boolean
  Line?: boolean
  ItemNumber?: boolean
  Quantity?: boolean
  QuantityCommit?: boolean
  UOM?: boolean
  UOMCommit?: boolean
  Weight?: boolean
  UOMWeight?: boolean
  Lot?: boolean
  Storage?: boolean
  StorageTo?: boolean
  Initial?: boolean
  Expected?: boolean
  Committed?: boolean
  Completed?: boolean
  Supplier?: boolean
  Customer?: boolean
  Owner?: boolean
  IdentProduct?: boolean
  IdentStorage?: boolean
  IdentStorageTo?: boolean
  IdentSupplier?: boolean
  IdentCustomer?: boolean
  IdentAddressLocation?: boolean
  IdentAddressBill?: boolean
  IdentAddressShip?: boolean
}, ExtArgs["result"]["dPurchaseOrder"]>



export type dPurchaseOrderSelectScalar = {
  Identifier?: boolean
  Status?: boolean
  Creation?: boolean
  CreationID?: boolean
  Maintenance?: boolean
  MaintenanceID?: boolean
  PurchaseOrder?: boolean
  ImportDate?: boolean
  ExportDate?: boolean
  ExternalID?: boolean
  LineID?: boolean
  CommitID?: boolean
  ItemID?: boolean
  Type?: boolean
  Line?: boolean
  ItemNumber?: boolean
  Quantity?: boolean
  QuantityCommit?: boolean
  UOM?: boolean
  UOMCommit?: boolean
  Weight?: boolean
  UOMWeight?: boolean
  Lot?: boolean
  Storage?: boolean
  StorageTo?: boolean
  Initial?: boolean
  Expected?: boolean
  Committed?: boolean
  Completed?: boolean
  Supplier?: boolean
  Customer?: boolean
  Owner?: boolean
  IdentProduct?: boolean
  IdentStorage?: boolean
  IdentStorageTo?: boolean
  IdentSupplier?: boolean
  IdentCustomer?: boolean
  IdentAddressLocation?: boolean
  IdentAddressBill?: boolean
  IdentAddressShip?: boolean
}

export type dPurchaseOrderOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"Identifier" | "Status" | "Creation" | "CreationID" | "Maintenance" | "MaintenanceID" | "PurchaseOrder" | "ImportDate" | "ExportDate" | "ExternalID" | "LineID" | "CommitID" | "ItemID" | "Type" | "Line" | "ItemNumber" | "Quantity" | "QuantityCommit" | "UOM" | "UOMCommit" | "Weight" | "UOMWeight" | "Lot" | "Storage" | "StorageTo" | "Initial" | "Expected" | "Committed" | "Completed" | "Supplier" | "Customer" | "Owner" | "IdentProduct" | "IdentStorage" | "IdentStorageTo" | "IdentSupplier" | "IdentCustomer" | "IdentAddressLocation" | "IdentAddressBill" | "IdentAddressShip", ExtArgs["result"]["dPurchaseOrder"]>

export type $dPurchaseOrderPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "dPurchaseOrder"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    Identifier: number
    Status: string
    Creation: Date
    CreationID: number
    Maintenance: Date
    MaintenanceID: number
    PurchaseOrder: string
    ImportDate: Date | null
    ExportDate: Date | null
    ExternalID: number | null
    LineID: number | null
    CommitID: number | null
    ItemID: number | null
    Type: string
    Line: number | null
    ItemNumber: string | null
    Quantity: runtime.Decimal | null
    QuantityCommit: runtime.Decimal | null
    UOM: string | null
    UOMCommit: string | null
    Weight: runtime.Decimal | null
    UOMWeight: string | null
    Lot: string | null
    Storage: string | null
    StorageTo: string | null
    Initial: Date
    Expected: Date | null
    Committed: Date | null
    Completed: Date | null
    Supplier: string | null
    Customer: string | null
    Owner: string | null
    IdentProduct: number
    IdentStorage: number
    IdentStorageTo: number
    IdentSupplier: number
    IdentCustomer: number
    IdentAddressLocation: number
    IdentAddressBill: number
    IdentAddressShip: number
  }, ExtArgs["result"]["dPurchaseOrder"]>
  composites: {}
}

export type dPurchaseOrderGetPayload<S extends boolean | null | undefined | dPurchaseOrderDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$dPurchaseOrderPayload, S>

export type dPurchaseOrderCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<dPurchaseOrderFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DPurchaseOrderCountAggregateInputType | true
  }

export interface dPurchaseOrderDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['dPurchaseOrder'], meta: { name: 'dPurchaseOrder' } }
  /**
   * Find zero or one DPurchaseOrder that matches the filter.
   * @param {dPurchaseOrderFindUniqueArgs} args - Arguments to find a DPurchaseOrder
   * @example
   * // Get one DPurchaseOrder
   * const dPurchaseOrder = await prisma.dPurchaseOrder.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends dPurchaseOrderFindUniqueArgs>(args: Prisma.SelectSubset<T, dPurchaseOrderFindUniqueArgs<ExtArgs>>): Prisma.Prisma__dPurchaseOrderClient<runtime.Types.Result.GetResult<Prisma.$dPurchaseOrderPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one DPurchaseOrder that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {dPurchaseOrderFindUniqueOrThrowArgs} args - Arguments to find a DPurchaseOrder
   * @example
   * // Get one DPurchaseOrder
   * const dPurchaseOrder = await prisma.dPurchaseOrder.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends dPurchaseOrderFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, dPurchaseOrderFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__dPurchaseOrderClient<runtime.Types.Result.GetResult<Prisma.$dPurchaseOrderPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DPurchaseOrder that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dPurchaseOrderFindFirstArgs} args - Arguments to find a DPurchaseOrder
   * @example
   * // Get one DPurchaseOrder
   * const dPurchaseOrder = await prisma.dPurchaseOrder.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends dPurchaseOrderFindFirstArgs>(args?: Prisma.SelectSubset<T, dPurchaseOrderFindFirstArgs<ExtArgs>>): Prisma.Prisma__dPurchaseOrderClient<runtime.Types.Result.GetResult<Prisma.$dPurchaseOrderPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DPurchaseOrder that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dPurchaseOrderFindFirstOrThrowArgs} args - Arguments to find a DPurchaseOrder
   * @example
   * // Get one DPurchaseOrder
   * const dPurchaseOrder = await prisma.dPurchaseOrder.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends dPurchaseOrderFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, dPurchaseOrderFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__dPurchaseOrderClient<runtime.Types.Result.GetResult<Prisma.$dPurchaseOrderPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more DPurchaseOrders that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dPurchaseOrderFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all DPurchaseOrders
   * const dPurchaseOrders = await prisma.dPurchaseOrder.findMany()
   * 
   * // Get first 10 DPurchaseOrders
   * const dPurchaseOrders = await prisma.dPurchaseOrder.findMany({ take: 10 })
   * 
   * // Only select the `Identifier`
   * const dPurchaseOrderWithIdentifierOnly = await prisma.dPurchaseOrder.findMany({ select: { Identifier: true } })
   * 
   */
  findMany<T extends dPurchaseOrderFindManyArgs>(args?: Prisma.SelectSubset<T, dPurchaseOrderFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$dPurchaseOrderPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a DPurchaseOrder.
   * @param {dPurchaseOrderCreateArgs} args - Arguments to create a DPurchaseOrder.
   * @example
   * // Create one DPurchaseOrder
   * const DPurchaseOrder = await prisma.dPurchaseOrder.create({
   *   data: {
   *     // ... data to create a DPurchaseOrder
   *   }
   * })
   * 
   */
  create<T extends dPurchaseOrderCreateArgs>(args: Prisma.SelectSubset<T, dPurchaseOrderCreateArgs<ExtArgs>>): Prisma.Prisma__dPurchaseOrderClient<runtime.Types.Result.GetResult<Prisma.$dPurchaseOrderPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many DPurchaseOrders.
   * @param {dPurchaseOrderCreateManyArgs} args - Arguments to create many DPurchaseOrders.
   * @example
   * // Create many DPurchaseOrders
   * const dPurchaseOrder = await prisma.dPurchaseOrder.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends dPurchaseOrderCreateManyArgs>(args?: Prisma.SelectSubset<T, dPurchaseOrderCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a DPurchaseOrder.
   * @param {dPurchaseOrderDeleteArgs} args - Arguments to delete one DPurchaseOrder.
   * @example
   * // Delete one DPurchaseOrder
   * const DPurchaseOrder = await prisma.dPurchaseOrder.delete({
   *   where: {
   *     // ... filter to delete one DPurchaseOrder
   *   }
   * })
   * 
   */
  delete<T extends dPurchaseOrderDeleteArgs>(args: Prisma.SelectSubset<T, dPurchaseOrderDeleteArgs<ExtArgs>>): Prisma.Prisma__dPurchaseOrderClient<runtime.Types.Result.GetResult<Prisma.$dPurchaseOrderPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one DPurchaseOrder.
   * @param {dPurchaseOrderUpdateArgs} args - Arguments to update one DPurchaseOrder.
   * @example
   * // Update one DPurchaseOrder
   * const dPurchaseOrder = await prisma.dPurchaseOrder.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends dPurchaseOrderUpdateArgs>(args: Prisma.SelectSubset<T, dPurchaseOrderUpdateArgs<ExtArgs>>): Prisma.Prisma__dPurchaseOrderClient<runtime.Types.Result.GetResult<Prisma.$dPurchaseOrderPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more DPurchaseOrders.
   * @param {dPurchaseOrderDeleteManyArgs} args - Arguments to filter DPurchaseOrders to delete.
   * @example
   * // Delete a few DPurchaseOrders
   * const { count } = await prisma.dPurchaseOrder.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends dPurchaseOrderDeleteManyArgs>(args?: Prisma.SelectSubset<T, dPurchaseOrderDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DPurchaseOrders.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dPurchaseOrderUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many DPurchaseOrders
   * const dPurchaseOrder = await prisma.dPurchaseOrder.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends dPurchaseOrderUpdateManyArgs>(args: Prisma.SelectSubset<T, dPurchaseOrderUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one DPurchaseOrder.
   * @param {dPurchaseOrderUpsertArgs} args - Arguments to update or create a DPurchaseOrder.
   * @example
   * // Update or create a DPurchaseOrder
   * const dPurchaseOrder = await prisma.dPurchaseOrder.upsert({
   *   create: {
   *     // ... data to create a DPurchaseOrder
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the DPurchaseOrder we want to update
   *   }
   * })
   */
  upsert<T extends dPurchaseOrderUpsertArgs>(args: Prisma.SelectSubset<T, dPurchaseOrderUpsertArgs<ExtArgs>>): Prisma.Prisma__dPurchaseOrderClient<runtime.Types.Result.GetResult<Prisma.$dPurchaseOrderPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of DPurchaseOrders.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dPurchaseOrderCountArgs} args - Arguments to filter DPurchaseOrders to count.
   * @example
   * // Count the number of DPurchaseOrders
   * const count = await prisma.dPurchaseOrder.count({
   *   where: {
   *     // ... the filter for the DPurchaseOrders we want to count
   *   }
   * })
  **/
  count<T extends dPurchaseOrderCountArgs>(
    args?: Prisma.Subset<T, dPurchaseOrderCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DPurchaseOrderCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a DPurchaseOrder.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DPurchaseOrderAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DPurchaseOrderAggregateArgs>(args: Prisma.Subset<T, DPurchaseOrderAggregateArgs>): Prisma.PrismaPromise<GetDPurchaseOrderAggregateType<T>>

  /**
   * Group by DPurchaseOrder.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dPurchaseOrderGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends dPurchaseOrderGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: dPurchaseOrderGroupByArgs['orderBy'] }
      : { orderBy?: dPurchaseOrderGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, dPurchaseOrderGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDPurchaseOrderGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the dPurchaseOrder model
 */
readonly fields: dPurchaseOrderFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for dPurchaseOrder.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__dPurchaseOrderClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the dPurchaseOrder model
 */
export interface dPurchaseOrderFieldRefs {
  readonly Identifier: Prisma.FieldRef<"dPurchaseOrder", 'Int'>
  readonly Status: Prisma.FieldRef<"dPurchaseOrder", 'String'>
  readonly Creation: Prisma.FieldRef<"dPurchaseOrder", 'DateTime'>
  readonly CreationID: Prisma.FieldRef<"dPurchaseOrder", 'Int'>
  readonly Maintenance: Prisma.FieldRef<"dPurchaseOrder", 'DateTime'>
  readonly MaintenanceID: Prisma.FieldRef<"dPurchaseOrder", 'Int'>
  readonly PurchaseOrder: Prisma.FieldRef<"dPurchaseOrder", 'String'>
  readonly ImportDate: Prisma.FieldRef<"dPurchaseOrder", 'DateTime'>
  readonly ExportDate: Prisma.FieldRef<"dPurchaseOrder", 'DateTime'>
  readonly ExternalID: Prisma.FieldRef<"dPurchaseOrder", 'Int'>
  readonly LineID: Prisma.FieldRef<"dPurchaseOrder", 'Int'>
  readonly CommitID: Prisma.FieldRef<"dPurchaseOrder", 'Int'>
  readonly ItemID: Prisma.FieldRef<"dPurchaseOrder", 'Int'>
  readonly Type: Prisma.FieldRef<"dPurchaseOrder", 'String'>
  readonly Line: Prisma.FieldRef<"dPurchaseOrder", 'Int'>
  readonly ItemNumber: Prisma.FieldRef<"dPurchaseOrder", 'String'>
  readonly Quantity: Prisma.FieldRef<"dPurchaseOrder", 'Decimal'>
  readonly QuantityCommit: Prisma.FieldRef<"dPurchaseOrder", 'Decimal'>
  readonly UOM: Prisma.FieldRef<"dPurchaseOrder", 'String'>
  readonly UOMCommit: Prisma.FieldRef<"dPurchaseOrder", 'String'>
  readonly Weight: Prisma.FieldRef<"dPurchaseOrder", 'Decimal'>
  readonly UOMWeight: Prisma.FieldRef<"dPurchaseOrder", 'String'>
  readonly Lot: Prisma.FieldRef<"dPurchaseOrder", 'String'>
  readonly Storage: Prisma.FieldRef<"dPurchaseOrder", 'String'>
  readonly StorageTo: Prisma.FieldRef<"dPurchaseOrder", 'String'>
  readonly Initial: Prisma.FieldRef<"dPurchaseOrder", 'DateTime'>
  readonly Expected: Prisma.FieldRef<"dPurchaseOrder", 'DateTime'>
  readonly Committed: Prisma.FieldRef<"dPurchaseOrder", 'DateTime'>
  readonly Completed: Prisma.FieldRef<"dPurchaseOrder", 'DateTime'>
  readonly Supplier: Prisma.FieldRef<"dPurchaseOrder", 'String'>
  readonly Customer: Prisma.FieldRef<"dPurchaseOrder", 'String'>
  readonly Owner: Prisma.FieldRef<"dPurchaseOrder", 'String'>
  readonly IdentProduct: Prisma.FieldRef<"dPurchaseOrder", 'Int'>
  readonly IdentStorage: Prisma.FieldRef<"dPurchaseOrder", 'Int'>
  readonly IdentStorageTo: Prisma.FieldRef<"dPurchaseOrder", 'Int'>
  readonly IdentSupplier: Prisma.FieldRef<"dPurchaseOrder", 'Int'>
  readonly IdentCustomer: Prisma.FieldRef<"dPurchaseOrder", 'Int'>
  readonly IdentAddressLocation: Prisma.FieldRef<"dPurchaseOrder", 'Int'>
  readonly IdentAddressBill: Prisma.FieldRef<"dPurchaseOrder", 'Int'>
  readonly IdentAddressShip: Prisma.FieldRef<"dPurchaseOrder", 'Int'>
}
    

// Custom InputTypes
/**
 * dPurchaseOrder findUnique
 */
export type dPurchaseOrderFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dPurchaseOrder
   */
  select?: Prisma.dPurchaseOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dPurchaseOrder
   */
  omit?: Prisma.dPurchaseOrderOmit<ExtArgs> | null
  /**
   * Filter, which dPurchaseOrder to fetch.
   */
  where: Prisma.dPurchaseOrderWhereUniqueInput
}

/**
 * dPurchaseOrder findUniqueOrThrow
 */
export type dPurchaseOrderFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dPurchaseOrder
   */
  select?: Prisma.dPurchaseOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dPurchaseOrder
   */
  omit?: Prisma.dPurchaseOrderOmit<ExtArgs> | null
  /**
   * Filter, which dPurchaseOrder to fetch.
   */
  where: Prisma.dPurchaseOrderWhereUniqueInput
}

/**
 * dPurchaseOrder findFirst
 */
export type dPurchaseOrderFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dPurchaseOrder
   */
  select?: Prisma.dPurchaseOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dPurchaseOrder
   */
  omit?: Prisma.dPurchaseOrderOmit<ExtArgs> | null
  /**
   * Filter, which dPurchaseOrder to fetch.
   */
  where?: Prisma.dPurchaseOrderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of dPurchaseOrders to fetch.
   */
  orderBy?: Prisma.dPurchaseOrderOrderByWithRelationInput | Prisma.dPurchaseOrderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for dPurchaseOrders.
   */
  cursor?: Prisma.dPurchaseOrderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` dPurchaseOrders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` dPurchaseOrders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of dPurchaseOrders.
   */
  distinct?: Prisma.DPurchaseOrderScalarFieldEnum | Prisma.DPurchaseOrderScalarFieldEnum[]
}

/**
 * dPurchaseOrder findFirstOrThrow
 */
export type dPurchaseOrderFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dPurchaseOrder
   */
  select?: Prisma.dPurchaseOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dPurchaseOrder
   */
  omit?: Prisma.dPurchaseOrderOmit<ExtArgs> | null
  /**
   * Filter, which dPurchaseOrder to fetch.
   */
  where?: Prisma.dPurchaseOrderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of dPurchaseOrders to fetch.
   */
  orderBy?: Prisma.dPurchaseOrderOrderByWithRelationInput | Prisma.dPurchaseOrderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for dPurchaseOrders.
   */
  cursor?: Prisma.dPurchaseOrderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` dPurchaseOrders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` dPurchaseOrders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of dPurchaseOrders.
   */
  distinct?: Prisma.DPurchaseOrderScalarFieldEnum | Prisma.DPurchaseOrderScalarFieldEnum[]
}

/**
 * dPurchaseOrder findMany
 */
export type dPurchaseOrderFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dPurchaseOrder
   */
  select?: Prisma.dPurchaseOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dPurchaseOrder
   */
  omit?: Prisma.dPurchaseOrderOmit<ExtArgs> | null
  /**
   * Filter, which dPurchaseOrders to fetch.
   */
  where?: Prisma.dPurchaseOrderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of dPurchaseOrders to fetch.
   */
  orderBy?: Prisma.dPurchaseOrderOrderByWithRelationInput | Prisma.dPurchaseOrderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing dPurchaseOrders.
   */
  cursor?: Prisma.dPurchaseOrderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` dPurchaseOrders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` dPurchaseOrders.
   */
  skip?: number
  distinct?: Prisma.DPurchaseOrderScalarFieldEnum | Prisma.DPurchaseOrderScalarFieldEnum[]
}

/**
 * dPurchaseOrder create
 */
export type dPurchaseOrderCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dPurchaseOrder
   */
  select?: Prisma.dPurchaseOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dPurchaseOrder
   */
  omit?: Prisma.dPurchaseOrderOmit<ExtArgs> | null
  /**
   * The data needed to create a dPurchaseOrder.
   */
  data: Prisma.XOR<Prisma.dPurchaseOrderCreateInput, Prisma.dPurchaseOrderUncheckedCreateInput>
}

/**
 * dPurchaseOrder createMany
 */
export type dPurchaseOrderCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many dPurchaseOrders.
   */
  data: Prisma.dPurchaseOrderCreateManyInput | Prisma.dPurchaseOrderCreateManyInput[]
}

/**
 * dPurchaseOrder update
 */
export type dPurchaseOrderUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dPurchaseOrder
   */
  select?: Prisma.dPurchaseOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dPurchaseOrder
   */
  omit?: Prisma.dPurchaseOrderOmit<ExtArgs> | null
  /**
   * The data needed to update a dPurchaseOrder.
   */
  data: Prisma.XOR<Prisma.dPurchaseOrderUpdateInput, Prisma.dPurchaseOrderUncheckedUpdateInput>
  /**
   * Choose, which dPurchaseOrder to update.
   */
  where: Prisma.dPurchaseOrderWhereUniqueInput
}

/**
 * dPurchaseOrder updateMany
 */
export type dPurchaseOrderUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update dPurchaseOrders.
   */
  data: Prisma.XOR<Prisma.dPurchaseOrderUpdateManyMutationInput, Prisma.dPurchaseOrderUncheckedUpdateManyInput>
  /**
   * Filter which dPurchaseOrders to update
   */
  where?: Prisma.dPurchaseOrderWhereInput
  /**
   * Limit how many dPurchaseOrders to update.
   */
  limit?: number
}

/**
 * dPurchaseOrder upsert
 */
export type dPurchaseOrderUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dPurchaseOrder
   */
  select?: Prisma.dPurchaseOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dPurchaseOrder
   */
  omit?: Prisma.dPurchaseOrderOmit<ExtArgs> | null
  /**
   * The filter to search for the dPurchaseOrder to update in case it exists.
   */
  where: Prisma.dPurchaseOrderWhereUniqueInput
  /**
   * In case the dPurchaseOrder found by the `where` argument doesn't exist, create a new dPurchaseOrder with this data.
   */
  create: Prisma.XOR<Prisma.dPurchaseOrderCreateInput, Prisma.dPurchaseOrderUncheckedCreateInput>
  /**
   * In case the dPurchaseOrder was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.dPurchaseOrderUpdateInput, Prisma.dPurchaseOrderUncheckedUpdateInput>
}

/**
 * dPurchaseOrder delete
 */
export type dPurchaseOrderDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dPurchaseOrder
   */
  select?: Prisma.dPurchaseOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dPurchaseOrder
   */
  omit?: Prisma.dPurchaseOrderOmit<ExtArgs> | null
  /**
   * Filter which dPurchaseOrder to delete.
   */
  where: Prisma.dPurchaseOrderWhereUniqueInput
}

/**
 * dPurchaseOrder deleteMany
 */
export type dPurchaseOrderDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which dPurchaseOrders to delete
   */
  where?: Prisma.dPurchaseOrderWhereInput
  /**
   * Limit how many dPurchaseOrders to delete.
   */
  limit?: number
}

/**
 * dPurchaseOrder without action
 */
export type dPurchaseOrderDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dPurchaseOrder
   */
  select?: Prisma.dPurchaseOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dPurchaseOrder
   */
  omit?: Prisma.dPurchaseOrderOmit<ExtArgs> | null
}
