
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `dSalesOrder` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model dSalesOrder
 * 
 */
export type dSalesOrderModel = runtime.Types.Result.DefaultSelection<Prisma.$dSalesOrderPayload>

export type AggregateDSalesOrder = {
  _count: DSalesOrderCountAggregateOutputType | null
  _avg: DSalesOrderAvgAggregateOutputType | null
  _sum: DSalesOrderSumAggregateOutputType | null
  _min: DSalesOrderMinAggregateOutputType | null
  _max: DSalesOrderMaxAggregateOutputType | null
}

export type DSalesOrderAvgAggregateOutputType = {
  Identifier: number | null
  CreationID: number | null
  MaintenanceID: number | null
  ExternalID: number | null
  LineID: number | null
  CommitID: number | null
  ItemID: number | null
  Line: number | null
  Quantity: runtime.Decimal | null
  QuantityCommit: runtime.Decimal | null
  Weight: runtime.Decimal | null
  IdentProduct: number | null
  IdentStorage: number | null
  IdentStorageTo: number | null
  IdentCustomer: number | null
  IdentAddressLocation: number | null
  IdentAddressBill: number | null
  IdentAddressShip: number | null
  IdentAddressShipper: number | null
  IdentAddressCarrier: number | null
  IdentAddressDestination: number | null
  IdentAddressDistribution: number | null
}

export type DSalesOrderSumAggregateOutputType = {
  Identifier: number | null
  CreationID: number | null
  MaintenanceID: number | null
  ExternalID: number | null
  LineID: number | null
  CommitID: number | null
  ItemID: number | null
  Line: number | null
  Quantity: runtime.Decimal | null
  QuantityCommit: runtime.Decimal | null
  Weight: runtime.Decimal | null
  IdentProduct: number | null
  IdentStorage: number | null
  IdentStorageTo: number | null
  IdentCustomer: number | null
  IdentAddressLocation: number | null
  IdentAddressBill: number | null
  IdentAddressShip: number | null
  IdentAddressShipper: number | null
  IdentAddressCarrier: number | null
  IdentAddressDestination: number | null
  IdentAddressDistribution: number | null
}

export type DSalesOrderMinAggregateOutputType = {
  Identifier: number | null
  Status: string | null
  Creation: Date | null
  CreationID: number | null
  Maintenance: Date | null
  MaintenanceID: number | null
  SalesOrder: string | null
  ImportDate: Date | null
  ExportDate: Date | null
  ExternalID: number | null
  LineID: number | null
  CommitID: number | null
  ItemID: number | null
  Type: string | null
  Line: number | null
  ItemNumber: string | null
  Quantity: runtime.Decimal | null
  QuantityCommit: runtime.Decimal | null
  UOM: string | null
  UOMCommit: string | null
  Weight: runtime.Decimal | null
  UOMWeight: string | null
  Lot: string | null
  Storage: string | null
  StorageTo: string | null
  Initial: Date | null
  Expected: Date | null
  Committed: Date | null
  Completed: Date | null
  PurchaseOrder: string | null
  Customer: string | null
  Owner: string | null
  IdentProduct: number | null
  IdentStorage: number | null
  IdentStorageTo: number | null
  IdentCustomer: number | null
  IdentAddressLocation: number | null
  IdentAddressBill: number | null
  IdentAddressShip: number | null
  IdentAddressShipper: number | null
  IdentAddressCarrier: number | null
  IdentAddressDestination: number | null
  IdentAddressDistribution: number | null
}

export type DSalesOrderMaxAggregateOutputType = {
  Identifier: number | null
  Status: string | null
  Creation: Date | null
  CreationID: number | null
  Maintenance: Date | null
  MaintenanceID: number | null
  SalesOrder: string | null
  ImportDate: Date | null
  ExportDate: Date | null
  ExternalID: number | null
  LineID: number | null
  CommitID: number | null
  ItemID: number | null
  Type: string | null
  Line: number | null
  ItemNumber: string | null
  Quantity: runtime.Decimal | null
  QuantityCommit: runtime.Decimal | null
  UOM: string | null
  UOMCommit: string | null
  Weight: runtime.Decimal | null
  UOMWeight: string | null
  Lot: string | null
  Storage: string | null
  StorageTo: string | null
  Initial: Date | null
  Expected: Date | null
  Committed: Date | null
  Completed: Date | null
  PurchaseOrder: string | null
  Customer: string | null
  Owner: string | null
  IdentProduct: number | null
  IdentStorage: number | null
  IdentStorageTo: number | null
  IdentCustomer: number | null
  IdentAddressLocation: number | null
  IdentAddressBill: number | null
  IdentAddressShip: number | null
  IdentAddressShipper: number | null
  IdentAddressCarrier: number | null
  IdentAddressDestination: number | null
  IdentAddressDistribution: number | null
}

export type DSalesOrderCountAggregateOutputType = {
  Identifier: number
  Status: number
  Creation: number
  CreationID: number
  Maintenance: number
  MaintenanceID: number
  SalesOrder: number
  ImportDate: number
  ExportDate: number
  ExternalID: number
  LineID: number
  CommitID: number
  ItemID: number
  Type: number
  Line: number
  ItemNumber: number
  Quantity: number
  QuantityCommit: number
  UOM: number
  UOMCommit: number
  Weight: number
  UOMWeight: number
  Lot: number
  Storage: number
  StorageTo: number
  Initial: number
  Expected: number
  Committed: number
  Completed: number
  PurchaseOrder: number
  Customer: number
  Owner: number
  IdentProduct: number
  IdentStorage: number
  IdentStorageTo: number
  IdentCustomer: number
  IdentAddressLocation: number
  IdentAddressBill: number
  IdentAddressShip: number
  IdentAddressShipper: number
  IdentAddressCarrier: number
  IdentAddressDestination: number
  IdentAddressDistribution: number
  _all: number
}


export type DSalesOrderAvgAggregateInputType = {
  Identifier?: true
  CreationID?: true
  MaintenanceID?: true
  ExternalID?: true
  LineID?: true
  CommitID?: true
  ItemID?: true
  Line?: true
  Quantity?: true
  QuantityCommit?: true
  Weight?: true
  IdentProduct?: true
  IdentStorage?: true
  IdentStorageTo?: true
  IdentCustomer?: true
  IdentAddressLocation?: true
  IdentAddressBill?: true
  IdentAddressShip?: true
  IdentAddressShipper?: true
  IdentAddressCarrier?: true
  IdentAddressDestination?: true
  IdentAddressDistribution?: true
}

export type DSalesOrderSumAggregateInputType = {
  Identifier?: true
  CreationID?: true
  MaintenanceID?: true
  ExternalID?: true
  LineID?: true
  CommitID?: true
  ItemID?: true
  Line?: true
  Quantity?: true
  QuantityCommit?: true
  Weight?: true
  IdentProduct?: true
  IdentStorage?: true
  IdentStorageTo?: true
  IdentCustomer?: true
  IdentAddressLocation?: true
  IdentAddressBill?: true
  IdentAddressShip?: true
  IdentAddressShipper?: true
  IdentAddressCarrier?: true
  IdentAddressDestination?: true
  IdentAddressDistribution?: true
}

export type DSalesOrderMinAggregateInputType = {
  Identifier?: true
  Status?: true
  Creation?: true
  CreationID?: true
  Maintenance?: true
  MaintenanceID?: true
  SalesOrder?: true
  ImportDate?: true
  ExportDate?: true
  ExternalID?: true
  LineID?: true
  CommitID?: true
  ItemID?: true
  Type?: true
  Line?: true
  ItemNumber?: true
  Quantity?: true
  QuantityCommit?: true
  UOM?: true
  UOMCommit?: true
  Weight?: true
  UOMWeight?: true
  Lot?: true
  Storage?: true
  StorageTo?: true
  Initial?: true
  Expected?: true
  Committed?: true
  Completed?: true
  PurchaseOrder?: true
  Customer?: true
  Owner?: true
  IdentProduct?: true
  IdentStorage?: true
  IdentStorageTo?: true
  IdentCustomer?: true
  IdentAddressLocation?: true
  IdentAddressBill?: true
  IdentAddressShip?: true
  IdentAddressShipper?: true
  IdentAddressCarrier?: true
  IdentAddressDestination?: true
  IdentAddressDistribution?: true
}

export type DSalesOrderMaxAggregateInputType = {
  Identifier?: true
  Status?: true
  Creation?: true
  CreationID?: true
  Maintenance?: true
  MaintenanceID?: true
  SalesOrder?: true
  ImportDate?: true
  ExportDate?: true
  ExternalID?: true
  LineID?: true
  CommitID?: true
  ItemID?: true
  Type?: true
  Line?: true
  ItemNumber?: true
  Quantity?: true
  QuantityCommit?: true
  UOM?: true
  UOMCommit?: true
  Weight?: true
  UOMWeight?: true
  Lot?: true
  Storage?: true
  StorageTo?: true
  Initial?: true
  Expected?: true
  Committed?: true
  Completed?: true
  PurchaseOrder?: true
  Customer?: true
  Owner?: true
  IdentProduct?: true
  IdentStorage?: true
  IdentStorageTo?: true
  IdentCustomer?: true
  IdentAddressLocation?: true
  IdentAddressBill?: true
  IdentAddressShip?: true
  IdentAddressShipper?: true
  IdentAddressCarrier?: true
  IdentAddressDestination?: true
  IdentAddressDistribution?: true
}

export type DSalesOrderCountAggregateInputType = {
  Identifier?: true
  Status?: true
  Creation?: true
  CreationID?: true
  Maintenance?: true
  MaintenanceID?: true
  SalesOrder?: true
  ImportDate?: true
  ExportDate?: true
  ExternalID?: true
  LineID?: true
  CommitID?: true
  ItemID?: true
  Type?: true
  Line?: true
  ItemNumber?: true
  Quantity?: true
  QuantityCommit?: true
  UOM?: true
  UOMCommit?: true
  Weight?: true
  UOMWeight?: true
  Lot?: true
  Storage?: true
  StorageTo?: true
  Initial?: true
  Expected?: true
  Committed?: true
  Completed?: true
  PurchaseOrder?: true
  Customer?: true
  Owner?: true
  IdentProduct?: true
  IdentStorage?: true
  IdentStorageTo?: true
  IdentCustomer?: true
  IdentAddressLocation?: true
  IdentAddressBill?: true
  IdentAddressShip?: true
  IdentAddressShipper?: true
  IdentAddressCarrier?: true
  IdentAddressDestination?: true
  IdentAddressDistribution?: true
  _all?: true
}

export type DSalesOrderAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which dSalesOrder to aggregate.
   */
  where?: Prisma.dSalesOrderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of dSalesOrders to fetch.
   */
  orderBy?: Prisma.dSalesOrderOrderByWithRelationInput | Prisma.dSalesOrderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.dSalesOrderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` dSalesOrders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` dSalesOrders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned dSalesOrders
  **/
  _count?: true | DSalesOrderCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: DSalesOrderAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: DSalesOrderSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DSalesOrderMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DSalesOrderMaxAggregateInputType
}

export type GetDSalesOrderAggregateType<T extends DSalesOrderAggregateArgs> = {
      [P in keyof T & keyof AggregateDSalesOrder]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDSalesOrder[P]>
    : Prisma.GetScalarType<T[P], AggregateDSalesOrder[P]>
}




export type dSalesOrderGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.dSalesOrderWhereInput
  orderBy?: Prisma.dSalesOrderOrderByWithAggregationInput | Prisma.dSalesOrderOrderByWithAggregationInput[]
  by: Prisma.DSalesOrderScalarFieldEnum[] | Prisma.DSalesOrderScalarFieldEnum
  having?: Prisma.dSalesOrderScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DSalesOrderCountAggregateInputType | true
  _avg?: DSalesOrderAvgAggregateInputType
  _sum?: DSalesOrderSumAggregateInputType
  _min?: DSalesOrderMinAggregateInputType
  _max?: DSalesOrderMaxAggregateInputType
}

export type DSalesOrderGroupByOutputType = {
  Identifier: number
  Status: string
  Creation: Date
  CreationID: number
  Maintenance: Date
  MaintenanceID: number
  SalesOrder: string
  ImportDate: Date | null
  ExportDate: Date | null
  ExternalID: number | null
  LineID: number | null
  CommitID: number | null
  ItemID: number | null
  Type: string
  Line: number | null
  ItemNumber: string | null
  Quantity: runtime.Decimal | null
  QuantityCommit: runtime.Decimal | null
  UOM: string | null
  UOMCommit: string | null
  Weight: runtime.Decimal | null
  UOMWeight: string | null
  Lot: string | null
  Storage: string | null
  StorageTo: string | null
  Initial: Date
  Expected: Date | null
  Committed: Date | null
  Completed: Date | null
  PurchaseOrder: string | null
  Customer: string | null
  Owner: string | null
  IdentProduct: number
  IdentStorage: number
  IdentStorageTo: number
  IdentCustomer: number
  IdentAddressLocation: number
  IdentAddressBill: number
  IdentAddressShip: number
  IdentAddressShipper: number
  IdentAddressCarrier: number
  IdentAddressDestination: number
  IdentAddressDistribution: number
  _count: DSalesOrderCountAggregateOutputType | null
  _avg: DSalesOrderAvgAggregateOutputType | null
  _sum: DSalesOrderSumAggregateOutputType | null
  _min: DSalesOrderMinAggregateOutputType | null
  _max: DSalesOrderMaxAggregateOutputType | null
}

type GetDSalesOrderGroupByPayload<T extends dSalesOrderGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DSalesOrderGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DSalesOrderGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DSalesOrderGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DSalesOrderGroupByOutputType[P]>
      }
    >
  >



export type dSalesOrderWhereInput = {
  AND?: Prisma.dSalesOrderWhereInput | Prisma.dSalesOrderWhereInput[]
  OR?: Prisma.dSalesOrderWhereInput[]
  NOT?: Prisma.dSalesOrderWhereInput | Prisma.dSalesOrderWhereInput[]
  Identifier?: Prisma.IntFilter<"dSalesOrder"> | number
  Status?: Prisma.StringFilter<"dSalesOrder"> | string
  Creation?: Prisma.DateTimeFilter<"dSalesOrder"> | Date | string
  CreationID?: Prisma.IntFilter<"dSalesOrder"> | number
  Maintenance?: Prisma.DateTimeFilter<"dSalesOrder"> | Date | string
  MaintenanceID?: Prisma.IntFilter<"dSalesOrder"> | number
  SalesOrder?: Prisma.StringFilter<"dSalesOrder"> | string
  ImportDate?: Prisma.DateTimeNullableFilter<"dSalesOrder"> | Date | string | null
  ExportDate?: Prisma.DateTimeNullableFilter<"dSalesOrder"> | Date | string | null
  ExternalID?: Prisma.IntNullableFilter<"dSalesOrder"> | number | null
  LineID?: Prisma.IntNullableFilter<"dSalesOrder"> | number | null
  CommitID?: Prisma.IntNullableFilter<"dSalesOrder"> | number | null
  ItemID?: Prisma.IntNullableFilter<"dSalesOrder"> | number | null
  Type?: Prisma.StringFilter<"dSalesOrder"> | string
  Line?: Prisma.IntNullableFilter<"dSalesOrder"> | number | null
  ItemNumber?: Prisma.StringNullableFilter<"dSalesOrder"> | string | null
  Quantity?: Prisma.DecimalNullableFilter<"dSalesOrder"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  QuantityCommit?: Prisma.DecimalNullableFilter<"dSalesOrder"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  UOM?: Prisma.StringNullableFilter<"dSalesOrder"> | string | null
  UOMCommit?: Prisma.StringNullableFilter<"dSalesOrder"> | string | null
  Weight?: Prisma.DecimalNullableFilter<"dSalesOrder"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  UOMWeight?: Prisma.StringNullableFilter<"dSalesOrder"> | string | null
  Lot?: Prisma.StringNullableFilter<"dSalesOrder"> | string | null
  Storage?: Prisma.StringNullableFilter<"dSalesOrder"> | string | null
  StorageTo?: Prisma.StringNullableFilter<"dSalesOrder"> | string | null
  Initial?: Prisma.DateTimeFilter<"dSalesOrder"> | Date | string
  Expected?: Prisma.DateTimeNullableFilter<"dSalesOrder"> | Date | string | null
  Committed?: Prisma.DateTimeNullableFilter<"dSalesOrder"> | Date | string | null
  Completed?: Prisma.DateTimeNullableFilter<"dSalesOrder"> | Date | string | null
  PurchaseOrder?: Prisma.StringNullableFilter<"dSalesOrder"> | string | null
  Customer?: Prisma.StringNullableFilter<"dSalesOrder"> | string | null
  Owner?: Prisma.StringNullableFilter<"dSalesOrder"> | string | null
  IdentProduct?: Prisma.IntFilter<"dSalesOrder"> | number
  IdentStorage?: Prisma.IntFilter<"dSalesOrder"> | number
  IdentStorageTo?: Prisma.IntFilter<"dSalesOrder"> | number
  IdentCustomer?: Prisma.IntFilter<"dSalesOrder"> | number
  IdentAddressLocation?: Prisma.IntFilter<"dSalesOrder"> | number
  IdentAddressBill?: Prisma.IntFilter<"dSalesOrder"> | number
  IdentAddressShip?: Prisma.IntFilter<"dSalesOrder"> | number
  IdentAddressShipper?: Prisma.IntFilter<"dSalesOrder"> | number
  IdentAddressCarrier?: Prisma.IntFilter<"dSalesOrder"> | number
  IdentAddressDestination?: Prisma.IntFilter<"dSalesOrder"> | number
  IdentAddressDistribution?: Prisma.IntFilter<"dSalesOrder"> | number
}

export type dSalesOrderOrderByWithRelationInput = {
  Identifier?: Prisma.SortOrder
  Status?: Prisma.SortOrder
  Creation?: Prisma.SortOrder
  CreationID?: Prisma.SortOrder
  Maintenance?: Prisma.SortOrder
  MaintenanceID?: Prisma.SortOrder
  SalesOrder?: Prisma.SortOrder
  ImportDate?: Prisma.SortOrderInput | Prisma.SortOrder
  ExportDate?: Prisma.SortOrderInput | Prisma.SortOrder
  ExternalID?: Prisma.SortOrderInput | Prisma.SortOrder
  LineID?: Prisma.SortOrderInput | Prisma.SortOrder
  CommitID?: Prisma.SortOrderInput | Prisma.SortOrder
  ItemID?: Prisma.SortOrderInput | Prisma.SortOrder
  Type?: Prisma.SortOrder
  Line?: Prisma.SortOrderInput | Prisma.SortOrder
  ItemNumber?: Prisma.SortOrderInput | Prisma.SortOrder
  Quantity?: Prisma.SortOrderInput | Prisma.SortOrder
  QuantityCommit?: Prisma.SortOrderInput | Prisma.SortOrder
  UOM?: Prisma.SortOrderInput | Prisma.SortOrder
  UOMCommit?: Prisma.SortOrderInput | Prisma.SortOrder
  Weight?: Prisma.SortOrderInput | Prisma.SortOrder
  UOMWeight?: Prisma.SortOrderInput | Prisma.SortOrder
  Lot?: Prisma.SortOrderInput | Prisma.SortOrder
  Storage?: Prisma.SortOrderInput | Prisma.SortOrder
  StorageTo?: Prisma.SortOrderInput | Prisma.SortOrder
  Initial?: Prisma.SortOrder
  Expected?: Prisma.SortOrderInput | Prisma.SortOrder
  Committed?: Prisma.SortOrderInput | Prisma.SortOrder
  Completed?: Prisma.SortOrderInput | Prisma.SortOrder
  PurchaseOrder?: Prisma.SortOrderInput | Prisma.SortOrder
  Customer?: Prisma.SortOrderInput | Prisma.SortOrder
  Owner?: Prisma.SortOrderInput | Prisma.SortOrder
  IdentProduct?: Prisma.SortOrder
  IdentStorage?: Prisma.SortOrder
  IdentStorageTo?: Prisma.SortOrder
  IdentCustomer?: Prisma.SortOrder
  IdentAddressLocation?: Prisma.SortOrder
  IdentAddressBill?: Prisma.SortOrder
  IdentAddressShip?: Prisma.SortOrder
  IdentAddressShipper?: Prisma.SortOrder
  IdentAddressCarrier?: Prisma.SortOrder
  IdentAddressDestination?: Prisma.SortOrder
  IdentAddressDistribution?: Prisma.SortOrder
}

export type dSalesOrderWhereUniqueInput = Prisma.AtLeast<{
  Identifier?: number
  SalesOrder_Line_ItemNumber?: Prisma.dSalesOrderSalesOrderLineItemNumberCompoundUniqueInput
  AND?: Prisma.dSalesOrderWhereInput | Prisma.dSalesOrderWhereInput[]
  OR?: Prisma.dSalesOrderWhereInput[]
  NOT?: Prisma.dSalesOrderWhereInput | Prisma.dSalesOrderWhereInput[]
  Status?: Prisma.StringFilter<"dSalesOrder"> | string
  Creation?: Prisma.DateTimeFilter<"dSalesOrder"> | Date | string
  CreationID?: Prisma.IntFilter<"dSalesOrder"> | number
  Maintenance?: Prisma.DateTimeFilter<"dSalesOrder"> | Date | string
  MaintenanceID?: Prisma.IntFilter<"dSalesOrder"> | number
  SalesOrder?: Prisma.StringFilter<"dSalesOrder"> | string
  ImportDate?: Prisma.DateTimeNullableFilter<"dSalesOrder"> | Date | string | null
  ExportDate?: Prisma.DateTimeNullableFilter<"dSalesOrder"> | Date | string | null
  ExternalID?: Prisma.IntNullableFilter<"dSalesOrder"> | number | null
  LineID?: Prisma.IntNullableFilter<"dSalesOrder"> | number | null
  CommitID?: Prisma.IntNullableFilter<"dSalesOrder"> | number | null
  ItemID?: Prisma.IntNullableFilter<"dSalesOrder"> | number | null
  Type?: Prisma.StringFilter<"dSalesOrder"> | string
  Line?: Prisma.IntNullableFilter<"dSalesOrder"> | number | null
  ItemNumber?: Prisma.StringNullableFilter<"dSalesOrder"> | string | null
  Quantity?: Prisma.DecimalNullableFilter<"dSalesOrder"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  QuantityCommit?: Prisma.DecimalNullableFilter<"dSalesOrder"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  UOM?: Prisma.StringNullableFilter<"dSalesOrder"> | string | null
  UOMCommit?: Prisma.StringNullableFilter<"dSalesOrder"> | string | null
  Weight?: Prisma.DecimalNullableFilter<"dSalesOrder"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  UOMWeight?: Prisma.StringNullableFilter<"dSalesOrder"> | string | null
  Lot?: Prisma.StringNullableFilter<"dSalesOrder"> | string | null
  Storage?: Prisma.StringNullableFilter<"dSalesOrder"> | string | null
  StorageTo?: Prisma.StringNullableFilter<"dSalesOrder"> | string | null
  Initial?: Prisma.DateTimeFilter<"dSalesOrder"> | Date | string
  Expected?: Prisma.DateTimeNullableFilter<"dSalesOrder"> | Date | string | null
  Committed?: Prisma.DateTimeNullableFilter<"dSalesOrder"> | Date | string | null
  Completed?: Prisma.DateTimeNullableFilter<"dSalesOrder"> | Date | string | null
  PurchaseOrder?: Prisma.StringNullableFilter<"dSalesOrder"> | string | null
  Customer?: Prisma.StringNullableFilter<"dSalesOrder"> | string | null
  Owner?: Prisma.StringNullableFilter<"dSalesOrder"> | string | null
  IdentProduct?: Prisma.IntFilter<"dSalesOrder"> | number
  IdentStorage?: Prisma.IntFilter<"dSalesOrder"> | number
  IdentStorageTo?: Prisma.IntFilter<"dSalesOrder"> | number
  IdentCustomer?: Prisma.IntFilter<"dSalesOrder"> | number
  IdentAddressLocation?: Prisma.IntFilter<"dSalesOrder"> | number
  IdentAddressBill?: Prisma.IntFilter<"dSalesOrder"> | number
  IdentAddressShip?: Prisma.IntFilter<"dSalesOrder"> | number
  IdentAddressShipper?: Prisma.IntFilter<"dSalesOrder"> | number
  IdentAddressCarrier?: Prisma.IntFilter<"dSalesOrder"> | number
  IdentAddressDestination?: Prisma.IntFilter<"dSalesOrder"> | number
  IdentAddressDistribution?: Prisma.IntFilter<"dSalesOrder"> | number
}, "Identifier" | "SalesOrder_Line_ItemNumber">

export type dSalesOrderOrderByWithAggregationInput = {
  Identifier?: Prisma.SortOrder
  Status?: Prisma.SortOrder
  Creation?: Prisma.SortOrder
  CreationID?: Prisma.SortOrder
  Maintenance?: Prisma.SortOrder
  MaintenanceID?: Prisma.SortOrder
  SalesOrder?: Prisma.SortOrder
  ImportDate?: Prisma.SortOrderInput | Prisma.SortOrder
  ExportDate?: Prisma.SortOrderInput | Prisma.SortOrder
  ExternalID?: Prisma.SortOrderInput | Prisma.SortOrder
  LineID?: Prisma.SortOrderInput | Prisma.SortOrder
  CommitID?: Prisma.SortOrderInput | Prisma.SortOrder
  ItemID?: Prisma.SortOrderInput | Prisma.SortOrder
  Type?: Prisma.SortOrder
  Line?: Prisma.SortOrderInput | Prisma.SortOrder
  ItemNumber?: Prisma.SortOrderInput | Prisma.SortOrder
  Quantity?: Prisma.SortOrderInput | Prisma.SortOrder
  QuantityCommit?: Prisma.SortOrderInput | Prisma.SortOrder
  UOM?: Prisma.SortOrderInput | Prisma.SortOrder
  UOMCommit?: Prisma.SortOrderInput | Prisma.SortOrder
  Weight?: Prisma.SortOrderInput | Prisma.SortOrder
  UOMWeight?: Prisma.SortOrderInput | Prisma.SortOrder
  Lot?: Prisma.SortOrderInput | Prisma.SortOrder
  Storage?: Prisma.SortOrderInput | Prisma.SortOrder
  StorageTo?: Prisma.SortOrderInput | Prisma.SortOrder
  Initial?: Prisma.SortOrder
  Expected?: Prisma.SortOrderInput | Prisma.SortOrder
  Committed?: Prisma.SortOrderInput | Prisma.SortOrder
  Completed?: Prisma.SortOrderInput | Prisma.SortOrder
  PurchaseOrder?: Prisma.SortOrderInput | Prisma.SortOrder
  Customer?: Prisma.SortOrderInput | Prisma.SortOrder
  Owner?: Prisma.SortOrderInput | Prisma.SortOrder
  IdentProduct?: Prisma.SortOrder
  IdentStorage?: Prisma.SortOrder
  IdentStorageTo?: Prisma.SortOrder
  IdentCustomer?: Prisma.SortOrder
  IdentAddressLocation?: Prisma.SortOrder
  IdentAddressBill?: Prisma.SortOrder
  IdentAddressShip?: Prisma.SortOrder
  IdentAddressShipper?: Prisma.SortOrder
  IdentAddressCarrier?: Prisma.SortOrder
  IdentAddressDestination?: Prisma.SortOrder
  IdentAddressDistribution?: Prisma.SortOrder
  _count?: Prisma.dSalesOrderCountOrderByAggregateInput
  _avg?: Prisma.dSalesOrderAvgOrderByAggregateInput
  _max?: Prisma.dSalesOrderMaxOrderByAggregateInput
  _min?: Prisma.dSalesOrderMinOrderByAggregateInput
  _sum?: Prisma.dSalesOrderSumOrderByAggregateInput
}

export type dSalesOrderScalarWhereWithAggregatesInput = {
  AND?: Prisma.dSalesOrderScalarWhereWithAggregatesInput | Prisma.dSalesOrderScalarWhereWithAggregatesInput[]
  OR?: Prisma.dSalesOrderScalarWhereWithAggregatesInput[]
  NOT?: Prisma.dSalesOrderScalarWhereWithAggregatesInput | Prisma.dSalesOrderScalarWhereWithAggregatesInput[]
  Identifier?: Prisma.IntWithAggregatesFilter<"dSalesOrder"> | number
  Status?: Prisma.StringWithAggregatesFilter<"dSalesOrder"> | string
  Creation?: Prisma.DateTimeWithAggregatesFilter<"dSalesOrder"> | Date | string
  CreationID?: Prisma.IntWithAggregatesFilter<"dSalesOrder"> | number
  Maintenance?: Prisma.DateTimeWithAggregatesFilter<"dSalesOrder"> | Date | string
  MaintenanceID?: Prisma.IntWithAggregatesFilter<"dSalesOrder"> | number
  SalesOrder?: Prisma.StringWithAggregatesFilter<"dSalesOrder"> | string
  ImportDate?: Prisma.DateTimeNullableWithAggregatesFilter<"dSalesOrder"> | Date | string | null
  ExportDate?: Prisma.DateTimeNullableWithAggregatesFilter<"dSalesOrder"> | Date | string | null
  ExternalID?: Prisma.IntNullableWithAggregatesFilter<"dSalesOrder"> | number | null
  LineID?: Prisma.IntNullableWithAggregatesFilter<"dSalesOrder"> | number | null
  CommitID?: Prisma.IntNullableWithAggregatesFilter<"dSalesOrder"> | number | null
  ItemID?: Prisma.IntNullableWithAggregatesFilter<"dSalesOrder"> | number | null
  Type?: Prisma.StringWithAggregatesFilter<"dSalesOrder"> | string
  Line?: Prisma.IntNullableWithAggregatesFilter<"dSalesOrder"> | number | null
  ItemNumber?: Prisma.StringNullableWithAggregatesFilter<"dSalesOrder"> | string | null
  Quantity?: Prisma.DecimalNullableWithAggregatesFilter<"dSalesOrder"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  QuantityCommit?: Prisma.DecimalNullableWithAggregatesFilter<"dSalesOrder"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  UOM?: Prisma.StringNullableWithAggregatesFilter<"dSalesOrder"> | string | null
  UOMCommit?: Prisma.StringNullableWithAggregatesFilter<"dSalesOrder"> | string | null
  Weight?: Prisma.DecimalNullableWithAggregatesFilter<"dSalesOrder"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  UOMWeight?: Prisma.StringNullableWithAggregatesFilter<"dSalesOrder"> | string | null
  Lot?: Prisma.StringNullableWithAggregatesFilter<"dSalesOrder"> | string | null
  Storage?: Prisma.StringNullableWithAggregatesFilter<"dSalesOrder"> | string | null
  StorageTo?: Prisma.StringNullableWithAggregatesFilter<"dSalesOrder"> | string | null
  Initial?: Prisma.DateTimeWithAggregatesFilter<"dSalesOrder"> | Date | string
  Expected?: Prisma.DateTimeNullableWithAggregatesFilter<"dSalesOrder"> | Date | string | null
  Committed?: Prisma.DateTimeNullableWithAggregatesFilter<"dSalesOrder"> | Date | string | null
  Completed?: Prisma.DateTimeNullableWithAggregatesFilter<"dSalesOrder"> | Date | string | null
  PurchaseOrder?: Prisma.StringNullableWithAggregatesFilter<"dSalesOrder"> | string | null
  Customer?: Prisma.StringNullableWithAggregatesFilter<"dSalesOrder"> | string | null
  Owner?: Prisma.StringNullableWithAggregatesFilter<"dSalesOrder"> | string | null
  IdentProduct?: Prisma.IntWithAggregatesFilter<"dSalesOrder"> | number
  IdentStorage?: Prisma.IntWithAggregatesFilter<"dSalesOrder"> | number
  IdentStorageTo?: Prisma.IntWithAggregatesFilter<"dSalesOrder"> | number
  IdentCustomer?: Prisma.IntWithAggregatesFilter<"dSalesOrder"> | number
  IdentAddressLocation?: Prisma.IntWithAggregatesFilter<"dSalesOrder"> | number
  IdentAddressBill?: Prisma.IntWithAggregatesFilter<"dSalesOrder"> | number
  IdentAddressShip?: Prisma.IntWithAggregatesFilter<"dSalesOrder"> | number
  IdentAddressShipper?: Prisma.IntWithAggregatesFilter<"dSalesOrder"> | number
  IdentAddressCarrier?: Prisma.IntWithAggregatesFilter<"dSalesOrder"> | number
  IdentAddressDestination?: Prisma.IntWithAggregatesFilter<"dSalesOrder"> | number
  IdentAddressDistribution?: Prisma.IntWithAggregatesFilter<"dSalesOrder"> | number
}

export type dSalesOrderCreateInput = {
  Status?: string
  Creation?: Date | string
  CreationID?: number
  Maintenance?: Date | string
  MaintenanceID?: number
  SalesOrder: string
  ImportDate?: Date | string | null
  ExportDate?: Date | string | null
  ExternalID?: number | null
  LineID?: number | null
  CommitID?: number | null
  ItemID?: number | null
  Type?: string
  Line?: number | null
  ItemNumber?: string | null
  Quantity?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  QuantityCommit?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  UOM?: string | null
  UOMCommit?: string | null
  Weight?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  UOMWeight?: string | null
  Lot?: string | null
  Storage?: string | null
  StorageTo?: string | null
  Initial?: Date | string
  Expected?: Date | string | null
  Committed?: Date | string | null
  Completed?: Date | string | null
  PurchaseOrder?: string | null
  Customer?: string | null
  Owner?: string | null
  IdentProduct?: number
  IdentStorage?: number
  IdentStorageTo?: number
  IdentCustomer?: number
  IdentAddressLocation?: number
  IdentAddressBill?: number
  IdentAddressShip?: number
  IdentAddressShipper?: number
  IdentAddressCarrier?: number
  IdentAddressDestination?: number
  IdentAddressDistribution?: number
}

export type dSalesOrderUncheckedCreateInput = {
  Identifier?: number
  Status?: string
  Creation?: Date | string
  CreationID?: number
  Maintenance?: Date | string
  MaintenanceID?: number
  SalesOrder: string
  ImportDate?: Date | string | null
  ExportDate?: Date | string | null
  ExternalID?: number | null
  LineID?: number | null
  CommitID?: number | null
  ItemID?: number | null
  Type?: string
  Line?: number | null
  ItemNumber?: string | null
  Quantity?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  QuantityCommit?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  UOM?: string | null
  UOMCommit?: string | null
  Weight?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  UOMWeight?: string | null
  Lot?: string | null
  Storage?: string | null
  StorageTo?: string | null
  Initial?: Date | string
  Expected?: Date | string | null
  Committed?: Date | string | null
  Completed?: Date | string | null
  PurchaseOrder?: string | null
  Customer?: string | null
  Owner?: string | null
  IdentProduct?: number
  IdentStorage?: number
  IdentStorageTo?: number
  IdentCustomer?: number
  IdentAddressLocation?: number
  IdentAddressBill?: number
  IdentAddressShip?: number
  IdentAddressShipper?: number
  IdentAddressCarrier?: number
  IdentAddressDestination?: number
  IdentAddressDistribution?: number
}

export type dSalesOrderUpdateInput = {
  Status?: Prisma.StringFieldUpdateOperationsInput | string
  Creation?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  CreationID?: Prisma.IntFieldUpdateOperationsInput | number
  Maintenance?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  MaintenanceID?: Prisma.IntFieldUpdateOperationsInput | number
  SalesOrder?: Prisma.StringFieldUpdateOperationsInput | string
  ImportDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  ExportDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  ExternalID?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  LineID?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  CommitID?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  ItemID?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  Type?: Prisma.StringFieldUpdateOperationsInput | string
  Line?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  ItemNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Quantity?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  QuantityCommit?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  UOM?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  UOMCommit?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Weight?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  UOMWeight?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Lot?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Storage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  StorageTo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Initial?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Expected?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  Committed?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  Completed?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  PurchaseOrder?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Customer?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Owner?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  IdentProduct?: Prisma.IntFieldUpdateOperationsInput | number
  IdentStorage?: Prisma.IntFieldUpdateOperationsInput | number
  IdentStorageTo?: Prisma.IntFieldUpdateOperationsInput | number
  IdentCustomer?: Prisma.IntFieldUpdateOperationsInput | number
  IdentAddressLocation?: Prisma.IntFieldUpdateOperationsInput | number
  IdentAddressBill?: Prisma.IntFieldUpdateOperationsInput | number
  IdentAddressShip?: Prisma.IntFieldUpdateOperationsInput | number
  IdentAddressShipper?: Prisma.IntFieldUpdateOperationsInput | number
  IdentAddressCarrier?: Prisma.IntFieldUpdateOperationsInput | number
  IdentAddressDestination?: Prisma.IntFieldUpdateOperationsInput | number
  IdentAddressDistribution?: Prisma.IntFieldUpdateOperationsInput | number
}

export type dSalesOrderUncheckedUpdateInput = {
  Identifier?: Prisma.IntFieldUpdateOperationsInput | number
  Status?: Prisma.StringFieldUpdateOperationsInput | string
  Creation?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  CreationID?: Prisma.IntFieldUpdateOperationsInput | number
  Maintenance?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  MaintenanceID?: Prisma.IntFieldUpdateOperationsInput | number
  SalesOrder?: Prisma.StringFieldUpdateOperationsInput | string
  ImportDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  ExportDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  ExternalID?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  LineID?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  CommitID?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  ItemID?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  Type?: Prisma.StringFieldUpdateOperationsInput | string
  Line?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  ItemNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Quantity?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  QuantityCommit?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  UOM?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  UOMCommit?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Weight?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  UOMWeight?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Lot?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Storage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  StorageTo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Initial?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Expected?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  Committed?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  Completed?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  PurchaseOrder?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Customer?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Owner?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  IdentProduct?: Prisma.IntFieldUpdateOperationsInput | number
  IdentStorage?: Prisma.IntFieldUpdateOperationsInput | number
  IdentStorageTo?: Prisma.IntFieldUpdateOperationsInput | number
  IdentCustomer?: Prisma.IntFieldUpdateOperationsInput | number
  IdentAddressLocation?: Prisma.IntFieldUpdateOperationsInput | number
  IdentAddressBill?: Prisma.IntFieldUpdateOperationsInput | number
  IdentAddressShip?: Prisma.IntFieldUpdateOperationsInput | number
  IdentAddressShipper?: Prisma.IntFieldUpdateOperationsInput | number
  IdentAddressCarrier?: Prisma.IntFieldUpdateOperationsInput | number
  IdentAddressDestination?: Prisma.IntFieldUpdateOperationsInput | number
  IdentAddressDistribution?: Prisma.IntFieldUpdateOperationsInput | number
}

export type dSalesOrderCreateManyInput = {
  Status?: string
  Creation?: Date | string
  CreationID?: number
  Maintenance?: Date | string
  MaintenanceID?: number
  SalesOrder: string
  ImportDate?: Date | string | null
  ExportDate?: Date | string | null
  ExternalID?: number | null
  LineID?: number | null
  CommitID?: number | null
  ItemID?: number | null
  Type?: string
  Line?: number | null
  ItemNumber?: string | null
  Quantity?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  QuantityCommit?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  UOM?: string | null
  UOMCommit?: string | null
  Weight?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  UOMWeight?: string | null
  Lot?: string | null
  Storage?: string | null
  StorageTo?: string | null
  Initial?: Date | string
  Expected?: Date | string | null
  Committed?: Date | string | null
  Completed?: Date | string | null
  PurchaseOrder?: string | null
  Customer?: string | null
  Owner?: string | null
  IdentProduct?: number
  IdentStorage?: number
  IdentStorageTo?: number
  IdentCustomer?: number
  IdentAddressLocation?: number
  IdentAddressBill?: number
  IdentAddressShip?: number
  IdentAddressShipper?: number
  IdentAddressCarrier?: number
  IdentAddressDestination?: number
  IdentAddressDistribution?: number
}

export type dSalesOrderUpdateManyMutationInput = {
  Status?: Prisma.StringFieldUpdateOperationsInput | string
  Creation?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  CreationID?: Prisma.IntFieldUpdateOperationsInput | number
  Maintenance?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  MaintenanceID?: Prisma.IntFieldUpdateOperationsInput | number
  SalesOrder?: Prisma.StringFieldUpdateOperationsInput | string
  ImportDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  ExportDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  ExternalID?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  LineID?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  CommitID?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  ItemID?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  Type?: Prisma.StringFieldUpdateOperationsInput | string
  Line?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  ItemNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Quantity?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  QuantityCommit?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  UOM?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  UOMCommit?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Weight?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  UOMWeight?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Lot?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Storage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  StorageTo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Initial?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Expected?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  Committed?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  Completed?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  PurchaseOrder?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Customer?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Owner?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  IdentProduct?: Prisma.IntFieldUpdateOperationsInput | number
  IdentStorage?: Prisma.IntFieldUpdateOperationsInput | number
  IdentStorageTo?: Prisma.IntFieldUpdateOperationsInput | number
  IdentCustomer?: Prisma.IntFieldUpdateOperationsInput | number
  IdentAddressLocation?: Prisma.IntFieldUpdateOperationsInput | number
  IdentAddressBill?: Prisma.IntFieldUpdateOperationsInput | number
  IdentAddressShip?: Prisma.IntFieldUpdateOperationsInput | number
  IdentAddressShipper?: Prisma.IntFieldUpdateOperationsInput | number
  IdentAddressCarrier?: Prisma.IntFieldUpdateOperationsInput | number
  IdentAddressDestination?: Prisma.IntFieldUpdateOperationsInput | number
  IdentAddressDistribution?: Prisma.IntFieldUpdateOperationsInput | number
}

export type dSalesOrderUncheckedUpdateManyInput = {
  Identifier?: Prisma.IntFieldUpdateOperationsInput | number
  Status?: Prisma.StringFieldUpdateOperationsInput | string
  Creation?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  CreationID?: Prisma.IntFieldUpdateOperationsInput | number
  Maintenance?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  MaintenanceID?: Prisma.IntFieldUpdateOperationsInput | number
  SalesOrder?: Prisma.StringFieldUpdateOperationsInput | string
  ImportDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  ExportDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  ExternalID?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  LineID?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  CommitID?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  ItemID?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  Type?: Prisma.StringFieldUpdateOperationsInput | string
  Line?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  ItemNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Quantity?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  QuantityCommit?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  UOM?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  UOMCommit?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Weight?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  UOMWeight?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Lot?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Storage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  StorageTo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Initial?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Expected?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  Committed?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  Completed?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  PurchaseOrder?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Customer?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Owner?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  IdentProduct?: Prisma.IntFieldUpdateOperationsInput | number
  IdentStorage?: Prisma.IntFieldUpdateOperationsInput | number
  IdentStorageTo?: Prisma.IntFieldUpdateOperationsInput | number
  IdentCustomer?: Prisma.IntFieldUpdateOperationsInput | number
  IdentAddressLocation?: Prisma.IntFieldUpdateOperationsInput | number
  IdentAddressBill?: Prisma.IntFieldUpdateOperationsInput | number
  IdentAddressShip?: Prisma.IntFieldUpdateOperationsInput | number
  IdentAddressShipper?: Prisma.IntFieldUpdateOperationsInput | number
  IdentAddressCarrier?: Prisma.IntFieldUpdateOperationsInput | number
  IdentAddressDestination?: Prisma.IntFieldUpdateOperationsInput | number
  IdentAddressDistribution?: Prisma.IntFieldUpdateOperationsInput | number
}

export type dSalesOrderSalesOrderLineItemNumberCompoundUniqueInput = {
  SalesOrder: string
  Line: number
  ItemNumber: string
}

export type dSalesOrderCountOrderByAggregateInput = {
  Identifier?: Prisma.SortOrder
  Status?: Prisma.SortOrder
  Creation?: Prisma.SortOrder
  CreationID?: Prisma.SortOrder
  Maintenance?: Prisma.SortOrder
  MaintenanceID?: Prisma.SortOrder
  SalesOrder?: Prisma.SortOrder
  ImportDate?: Prisma.SortOrder
  ExportDate?: Prisma.SortOrder
  ExternalID?: Prisma.SortOrder
  LineID?: Prisma.SortOrder
  CommitID?: Prisma.SortOrder
  ItemID?: Prisma.SortOrder
  Type?: Prisma.SortOrder
  Line?: Prisma.SortOrder
  ItemNumber?: Prisma.SortOrder
  Quantity?: Prisma.SortOrder
  QuantityCommit?: Prisma.SortOrder
  UOM?: Prisma.SortOrder
  UOMCommit?: Prisma.SortOrder
  Weight?: Prisma.SortOrder
  UOMWeight?: Prisma.SortOrder
  Lot?: Prisma.SortOrder
  Storage?: Prisma.SortOrder
  StorageTo?: Prisma.SortOrder
  Initial?: Prisma.SortOrder
  Expected?: Prisma.SortOrder
  Committed?: Prisma.SortOrder
  Completed?: Prisma.SortOrder
  PurchaseOrder?: Prisma.SortOrder
  Customer?: Prisma.SortOrder
  Owner?: Prisma.SortOrder
  IdentProduct?: Prisma.SortOrder
  IdentStorage?: Prisma.SortOrder
  IdentStorageTo?: Prisma.SortOrder
  IdentCustomer?: Prisma.SortOrder
  IdentAddressLocation?: Prisma.SortOrder
  IdentAddressBill?: Prisma.SortOrder
  IdentAddressShip?: Prisma.SortOrder
  IdentAddressShipper?: Prisma.SortOrder
  IdentAddressCarrier?: Prisma.SortOrder
  IdentAddressDestination?: Prisma.SortOrder
  IdentAddressDistribution?: Prisma.SortOrder
}

export type dSalesOrderAvgOrderByAggregateInput = {
  Identifier?: Prisma.SortOrder
  CreationID?: Prisma.SortOrder
  MaintenanceID?: Prisma.SortOrder
  ExternalID?: Prisma.SortOrder
  LineID?: Prisma.SortOrder
  CommitID?: Prisma.SortOrder
  ItemID?: Prisma.SortOrder
  Line?: Prisma.SortOrder
  Quantity?: Prisma.SortOrder
  QuantityCommit?: Prisma.SortOrder
  Weight?: Prisma.SortOrder
  IdentProduct?: Prisma.SortOrder
  IdentStorage?: Prisma.SortOrder
  IdentStorageTo?: Prisma.SortOrder
  IdentCustomer?: Prisma.SortOrder
  IdentAddressLocation?: Prisma.SortOrder
  IdentAddressBill?: Prisma.SortOrder
  IdentAddressShip?: Prisma.SortOrder
  IdentAddressShipper?: Prisma.SortOrder
  IdentAddressCarrier?: Prisma.SortOrder
  IdentAddressDestination?: Prisma.SortOrder
  IdentAddressDistribution?: Prisma.SortOrder
}

export type dSalesOrderMaxOrderByAggregateInput = {
  Identifier?: Prisma.SortOrder
  Status?: Prisma.SortOrder
  Creation?: Prisma.SortOrder
  CreationID?: Prisma.SortOrder
  Maintenance?: Prisma.SortOrder
  MaintenanceID?: Prisma.SortOrder
  SalesOrder?: Prisma.SortOrder
  ImportDate?: Prisma.SortOrder
  ExportDate?: Prisma.SortOrder
  ExternalID?: Prisma.SortOrder
  LineID?: Prisma.SortOrder
  CommitID?: Prisma.SortOrder
  ItemID?: Prisma.SortOrder
  Type?: Prisma.SortOrder
  Line?: Prisma.SortOrder
  ItemNumber?: Prisma.SortOrder
  Quantity?: Prisma.SortOrder
  QuantityCommit?: Prisma.SortOrder
  UOM?: Prisma.SortOrder
  UOMCommit?: Prisma.SortOrder
  Weight?: Prisma.SortOrder
  UOMWeight?: Prisma.SortOrder
  Lot?: Prisma.SortOrder
  Storage?: Prisma.SortOrder
  StorageTo?: Prisma.SortOrder
  Initial?: Prisma.SortOrder
  Expected?: Prisma.SortOrder
  Committed?: Prisma.SortOrder
  Completed?: Prisma.SortOrder
  PurchaseOrder?: Prisma.SortOrder
  Customer?: Prisma.SortOrder
  Owner?: Prisma.SortOrder
  IdentProduct?: Prisma.SortOrder
  IdentStorage?: Prisma.SortOrder
  IdentStorageTo?: Prisma.SortOrder
  IdentCustomer?: Prisma.SortOrder
  IdentAddressLocation?: Prisma.SortOrder
  IdentAddressBill?: Prisma.SortOrder
  IdentAddressShip?: Prisma.SortOrder
  IdentAddressShipper?: Prisma.SortOrder
  IdentAddressCarrier?: Prisma.SortOrder
  IdentAddressDestination?: Prisma.SortOrder
  IdentAddressDistribution?: Prisma.SortOrder
}

export type dSalesOrderMinOrderByAggregateInput = {
  Identifier?: Prisma.SortOrder
  Status?: Prisma.SortOrder
  Creation?: Prisma.SortOrder
  CreationID?: Prisma.SortOrder
  Maintenance?: Prisma.SortOrder
  MaintenanceID?: Prisma.SortOrder
  SalesOrder?: Prisma.SortOrder
  ImportDate?: Prisma.SortOrder
  ExportDate?: Prisma.SortOrder
  ExternalID?: Prisma.SortOrder
  LineID?: Prisma.SortOrder
  CommitID?: Prisma.SortOrder
  ItemID?: Prisma.SortOrder
  Type?: Prisma.SortOrder
  Line?: Prisma.SortOrder
  ItemNumber?: Prisma.SortOrder
  Quantity?: Prisma.SortOrder
  QuantityCommit?: Prisma.SortOrder
  UOM?: Prisma.SortOrder
  UOMCommit?: Prisma.SortOrder
  Weight?: Prisma.SortOrder
  UOMWeight?: Prisma.SortOrder
  Lot?: Prisma.SortOrder
  Storage?: Prisma.SortOrder
  StorageTo?: Prisma.SortOrder
  Initial?: Prisma.SortOrder
  Expected?: Prisma.SortOrder
  Committed?: Prisma.SortOrder
  Completed?: Prisma.SortOrder
  PurchaseOrder?: Prisma.SortOrder
  Customer?: Prisma.SortOrder
  Owner?: Prisma.SortOrder
  IdentProduct?: Prisma.SortOrder
  IdentStorage?: Prisma.SortOrder
  IdentStorageTo?: Prisma.SortOrder
  IdentCustomer?: Prisma.SortOrder
  IdentAddressLocation?: Prisma.SortOrder
  IdentAddressBill?: Prisma.SortOrder
  IdentAddressShip?: Prisma.SortOrder
  IdentAddressShipper?: Prisma.SortOrder
  IdentAddressCarrier?: Prisma.SortOrder
  IdentAddressDestination?: Prisma.SortOrder
  IdentAddressDistribution?: Prisma.SortOrder
}

export type dSalesOrderSumOrderByAggregateInput = {
  Identifier?: Prisma.SortOrder
  CreationID?: Prisma.SortOrder
  MaintenanceID?: Prisma.SortOrder
  ExternalID?: Prisma.SortOrder
  LineID?: Prisma.SortOrder
  CommitID?: Prisma.SortOrder
  ItemID?: Prisma.SortOrder
  Line?: Prisma.SortOrder
  Quantity?: Prisma.SortOrder
  QuantityCommit?: Prisma.SortOrder
  Weight?: Prisma.SortOrder
  IdentProduct?: Prisma.SortOrder
  IdentStorage?: Prisma.SortOrder
  IdentStorageTo?: Prisma.SortOrder
  IdentCustomer?: Prisma.SortOrder
  IdentAddressLocation?: Prisma.SortOrder
  IdentAddressBill?: Prisma.SortOrder
  IdentAddressShip?: Prisma.SortOrder
  IdentAddressShipper?: Prisma.SortOrder
  IdentAddressCarrier?: Prisma.SortOrder
  IdentAddressDestination?: Prisma.SortOrder
  IdentAddressDistribution?: Prisma.SortOrder
}



export type dSalesOrderSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  Identifier?: boolean
  Status?: boolean
  Creation?: boolean
  CreationID?: boolean
  Maintenance?: boolean
  MaintenanceID?: boolean
  SalesOrder?: boolean
  ImportDate?: boolean
  ExportDate?: boolean
  ExternalID?: boolean
  LineID?: boolean
  CommitID?: boolean
  ItemID?: boolean
  Type?: boolean
  Line?: boolean
  ItemNumber?: boolean
  Quantity?: boolean
  QuantityCommit?: boolean
  UOM?: boolean
  UOMCommit?: boolean
  Weight?: boolean
  UOMWeight?: boolean
  Lot?: boolean
  Storage?: boolean
  StorageTo?: boolean
  Initial?: boolean
  Expected?: boolean
  Committed?: boolean
  Completed?: boolean
  PurchaseOrder?: boolean
  Customer?: boolean
  Owner?: boolean
  IdentProduct?: boolean
  IdentStorage?: boolean
  IdentStorageTo?: boolean
  IdentCustomer?: boolean
  IdentAddressLocation?: boolean
  IdentAddressBill?: boolean
  IdentAddressShip?: boolean
  IdentAddressShipper?: boolean
  IdentAddressCarrier?: boolean
  IdentAddressDestination?: boolean
  IdentAddressDistribution?: boolean
}, ExtArgs["result"]["dSalesOrder"]>



export type dSalesOrderSelectScalar = {
  Identifier?: boolean
  Status?: boolean
  Creation?: boolean
  CreationID?: boolean
  Maintenance?: boolean
  MaintenanceID?: boolean
  SalesOrder?: boolean
  ImportDate?: boolean
  ExportDate?: boolean
  ExternalID?: boolean
  LineID?: boolean
  CommitID?: boolean
  ItemID?: boolean
  Type?: boolean
  Line?: boolean
  ItemNumber?: boolean
  Quantity?: boolean
  QuantityCommit?: boolean
  UOM?: boolean
  UOMCommit?: boolean
  Weight?: boolean
  UOMWeight?: boolean
  Lot?: boolean
  Storage?: boolean
  StorageTo?: boolean
  Initial?: boolean
  Expected?: boolean
  Committed?: boolean
  Completed?: boolean
  PurchaseOrder?: boolean
  Customer?: boolean
  Owner?: boolean
  IdentProduct?: boolean
  IdentStorage?: boolean
  IdentStorageTo?: boolean
  IdentCustomer?: boolean
  IdentAddressLocation?: boolean
  IdentAddressBill?: boolean
  IdentAddressShip?: boolean
  IdentAddressShipper?: boolean
  IdentAddressCarrier?: boolean
  IdentAddressDestination?: boolean
  IdentAddressDistribution?: boolean
}

export type dSalesOrderOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"Identifier" | "Status" | "Creation" | "CreationID" | "Maintenance" | "MaintenanceID" | "SalesOrder" | "ImportDate" | "ExportDate" | "ExternalID" | "LineID" | "CommitID" | "ItemID" | "Type" | "Line" | "ItemNumber" | "Quantity" | "QuantityCommit" | "UOM" | "UOMCommit" | "Weight" | "UOMWeight" | "Lot" | "Storage" | "StorageTo" | "Initial" | "Expected" | "Committed" | "Completed" | "PurchaseOrder" | "Customer" | "Owner" | "IdentProduct" | "IdentStorage" | "IdentStorageTo" | "IdentCustomer" | "IdentAddressLocation" | "IdentAddressBill" | "IdentAddressShip" | "IdentAddressShipper" | "IdentAddressCarrier" | "IdentAddressDestination" | "IdentAddressDistribution", ExtArgs["result"]["dSalesOrder"]>

export type $dSalesOrderPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "dSalesOrder"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    Identifier: number
    Status: string
    Creation: Date
    CreationID: number
    Maintenance: Date
    MaintenanceID: number
    SalesOrder: string
    ImportDate: Date | null
    ExportDate: Date | null
    ExternalID: number | null
    LineID: number | null
    CommitID: number | null
    ItemID: number | null
    Type: string
    Line: number | null
    ItemNumber: string | null
    Quantity: runtime.Decimal | null
    QuantityCommit: runtime.Decimal | null
    UOM: string | null
    UOMCommit: string | null
    Weight: runtime.Decimal | null
    UOMWeight: string | null
    Lot: string | null
    Storage: string | null
    StorageTo: string | null
    Initial: Date
    Expected: Date | null
    Committed: Date | null
    Completed: Date | null
    PurchaseOrder: string | null
    Customer: string | null
    Owner: string | null
    IdentProduct: number
    IdentStorage: number
    IdentStorageTo: number
    IdentCustomer: number
    IdentAddressLocation: number
    IdentAddressBill: number
    IdentAddressShip: number
    IdentAddressShipper: number
    IdentAddressCarrier: number
    IdentAddressDestination: number
    IdentAddressDistribution: number
  }, ExtArgs["result"]["dSalesOrder"]>
  composites: {}
}

export type dSalesOrderGetPayload<S extends boolean | null | undefined | dSalesOrderDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$dSalesOrderPayload, S>

export type dSalesOrderCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<dSalesOrderFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DSalesOrderCountAggregateInputType | true
  }

export interface dSalesOrderDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['dSalesOrder'], meta: { name: 'dSalesOrder' } }
  /**
   * Find zero or one DSalesOrder that matches the filter.
   * @param {dSalesOrderFindUniqueArgs} args - Arguments to find a DSalesOrder
   * @example
   * // Get one DSalesOrder
   * const dSalesOrder = await prisma.dSalesOrder.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends dSalesOrderFindUniqueArgs>(args: Prisma.SelectSubset<T, dSalesOrderFindUniqueArgs<ExtArgs>>): Prisma.Prisma__dSalesOrderClient<runtime.Types.Result.GetResult<Prisma.$dSalesOrderPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one DSalesOrder that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {dSalesOrderFindUniqueOrThrowArgs} args - Arguments to find a DSalesOrder
   * @example
   * // Get one DSalesOrder
   * const dSalesOrder = await prisma.dSalesOrder.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends dSalesOrderFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, dSalesOrderFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__dSalesOrderClient<runtime.Types.Result.GetResult<Prisma.$dSalesOrderPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DSalesOrder that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dSalesOrderFindFirstArgs} args - Arguments to find a DSalesOrder
   * @example
   * // Get one DSalesOrder
   * const dSalesOrder = await prisma.dSalesOrder.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends dSalesOrderFindFirstArgs>(args?: Prisma.SelectSubset<T, dSalesOrderFindFirstArgs<ExtArgs>>): Prisma.Prisma__dSalesOrderClient<runtime.Types.Result.GetResult<Prisma.$dSalesOrderPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DSalesOrder that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dSalesOrderFindFirstOrThrowArgs} args - Arguments to find a DSalesOrder
   * @example
   * // Get one DSalesOrder
   * const dSalesOrder = await prisma.dSalesOrder.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends dSalesOrderFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, dSalesOrderFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__dSalesOrderClient<runtime.Types.Result.GetResult<Prisma.$dSalesOrderPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more DSalesOrders that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dSalesOrderFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all DSalesOrders
   * const dSalesOrders = await prisma.dSalesOrder.findMany()
   * 
   * // Get first 10 DSalesOrders
   * const dSalesOrders = await prisma.dSalesOrder.findMany({ take: 10 })
   * 
   * // Only select the `Identifier`
   * const dSalesOrderWithIdentifierOnly = await prisma.dSalesOrder.findMany({ select: { Identifier: true } })
   * 
   */
  findMany<T extends dSalesOrderFindManyArgs>(args?: Prisma.SelectSubset<T, dSalesOrderFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$dSalesOrderPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a DSalesOrder.
   * @param {dSalesOrderCreateArgs} args - Arguments to create a DSalesOrder.
   * @example
   * // Create one DSalesOrder
   * const DSalesOrder = await prisma.dSalesOrder.create({
   *   data: {
   *     // ... data to create a DSalesOrder
   *   }
   * })
   * 
   */
  create<T extends dSalesOrderCreateArgs>(args: Prisma.SelectSubset<T, dSalesOrderCreateArgs<ExtArgs>>): Prisma.Prisma__dSalesOrderClient<runtime.Types.Result.GetResult<Prisma.$dSalesOrderPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many DSalesOrders.
   * @param {dSalesOrderCreateManyArgs} args - Arguments to create many DSalesOrders.
   * @example
   * // Create many DSalesOrders
   * const dSalesOrder = await prisma.dSalesOrder.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends dSalesOrderCreateManyArgs>(args?: Prisma.SelectSubset<T, dSalesOrderCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a DSalesOrder.
   * @param {dSalesOrderDeleteArgs} args - Arguments to delete one DSalesOrder.
   * @example
   * // Delete one DSalesOrder
   * const DSalesOrder = await prisma.dSalesOrder.delete({
   *   where: {
   *     // ... filter to delete one DSalesOrder
   *   }
   * })
   * 
   */
  delete<T extends dSalesOrderDeleteArgs>(args: Prisma.SelectSubset<T, dSalesOrderDeleteArgs<ExtArgs>>): Prisma.Prisma__dSalesOrderClient<runtime.Types.Result.GetResult<Prisma.$dSalesOrderPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one DSalesOrder.
   * @param {dSalesOrderUpdateArgs} args - Arguments to update one DSalesOrder.
   * @example
   * // Update one DSalesOrder
   * const dSalesOrder = await prisma.dSalesOrder.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends dSalesOrderUpdateArgs>(args: Prisma.SelectSubset<T, dSalesOrderUpdateArgs<ExtArgs>>): Prisma.Prisma__dSalesOrderClient<runtime.Types.Result.GetResult<Prisma.$dSalesOrderPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more DSalesOrders.
   * @param {dSalesOrderDeleteManyArgs} args - Arguments to filter DSalesOrders to delete.
   * @example
   * // Delete a few DSalesOrders
   * const { count } = await prisma.dSalesOrder.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends dSalesOrderDeleteManyArgs>(args?: Prisma.SelectSubset<T, dSalesOrderDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DSalesOrders.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dSalesOrderUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many DSalesOrders
   * const dSalesOrder = await prisma.dSalesOrder.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends dSalesOrderUpdateManyArgs>(args: Prisma.SelectSubset<T, dSalesOrderUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one DSalesOrder.
   * @param {dSalesOrderUpsertArgs} args - Arguments to update or create a DSalesOrder.
   * @example
   * // Update or create a DSalesOrder
   * const dSalesOrder = await prisma.dSalesOrder.upsert({
   *   create: {
   *     // ... data to create a DSalesOrder
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the DSalesOrder we want to update
   *   }
   * })
   */
  upsert<T extends dSalesOrderUpsertArgs>(args: Prisma.SelectSubset<T, dSalesOrderUpsertArgs<ExtArgs>>): Prisma.Prisma__dSalesOrderClient<runtime.Types.Result.GetResult<Prisma.$dSalesOrderPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of DSalesOrders.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dSalesOrderCountArgs} args - Arguments to filter DSalesOrders to count.
   * @example
   * // Count the number of DSalesOrders
   * const count = await prisma.dSalesOrder.count({
   *   where: {
   *     // ... the filter for the DSalesOrders we want to count
   *   }
   * })
  **/
  count<T extends dSalesOrderCountArgs>(
    args?: Prisma.Subset<T, dSalesOrderCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DSalesOrderCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a DSalesOrder.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DSalesOrderAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DSalesOrderAggregateArgs>(args: Prisma.Subset<T, DSalesOrderAggregateArgs>): Prisma.PrismaPromise<GetDSalesOrderAggregateType<T>>

  /**
   * Group by DSalesOrder.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dSalesOrderGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends dSalesOrderGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: dSalesOrderGroupByArgs['orderBy'] }
      : { orderBy?: dSalesOrderGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, dSalesOrderGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDSalesOrderGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the dSalesOrder model
 */
readonly fields: dSalesOrderFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for dSalesOrder.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__dSalesOrderClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the dSalesOrder model
 */
export interface dSalesOrderFieldRefs {
  readonly Identifier: Prisma.FieldRef<"dSalesOrder", 'Int'>
  readonly Status: Prisma.FieldRef<"dSalesOrder", 'String'>
  readonly Creation: Prisma.FieldRef<"dSalesOrder", 'DateTime'>
  readonly CreationID: Prisma.FieldRef<"dSalesOrder", 'Int'>
  readonly Maintenance: Prisma.FieldRef<"dSalesOrder", 'DateTime'>
  readonly MaintenanceID: Prisma.FieldRef<"dSalesOrder", 'Int'>
  readonly SalesOrder: Prisma.FieldRef<"dSalesOrder", 'String'>
  readonly ImportDate: Prisma.FieldRef<"dSalesOrder", 'DateTime'>
  readonly ExportDate: Prisma.FieldRef<"dSalesOrder", 'DateTime'>
  readonly ExternalID: Prisma.FieldRef<"dSalesOrder", 'Int'>
  readonly LineID: Prisma.FieldRef<"dSalesOrder", 'Int'>
  readonly CommitID: Prisma.FieldRef<"dSalesOrder", 'Int'>
  readonly ItemID: Prisma.FieldRef<"dSalesOrder", 'Int'>
  readonly Type: Prisma.FieldRef<"dSalesOrder", 'String'>
  readonly Line: Prisma.FieldRef<"dSalesOrder", 'Int'>
  readonly ItemNumber: Prisma.FieldRef<"dSalesOrder", 'String'>
  readonly Quantity: Prisma.FieldRef<"dSalesOrder", 'Decimal'>
  readonly QuantityCommit: Prisma.FieldRef<"dSalesOrder", 'Decimal'>
  readonly UOM: Prisma.FieldRef<"dSalesOrder", 'String'>
  readonly UOMCommit: Prisma.FieldRef<"dSalesOrder", 'String'>
  readonly Weight: Prisma.FieldRef<"dSalesOrder", 'Decimal'>
  readonly UOMWeight: Prisma.FieldRef<"dSalesOrder", 'String'>
  readonly Lot: Prisma.FieldRef<"dSalesOrder", 'String'>
  readonly Storage: Prisma.FieldRef<"dSalesOrder", 'String'>
  readonly StorageTo: Prisma.FieldRef<"dSalesOrder", 'String'>
  readonly Initial: Prisma.FieldRef<"dSalesOrder", 'DateTime'>
  readonly Expected: Prisma.FieldRef<"dSalesOrder", 'DateTime'>
  readonly Committed: Prisma.FieldRef<"dSalesOrder", 'DateTime'>
  readonly Completed: Prisma.FieldRef<"dSalesOrder", 'DateTime'>
  readonly PurchaseOrder: Prisma.FieldRef<"dSalesOrder", 'String'>
  readonly Customer: Prisma.FieldRef<"dSalesOrder", 'String'>
  readonly Owner: Prisma.FieldRef<"dSalesOrder", 'String'>
  readonly IdentProduct: Prisma.FieldRef<"dSalesOrder", 'Int'>
  readonly IdentStorage: Prisma.FieldRef<"dSalesOrder", 'Int'>
  readonly IdentStorageTo: Prisma.FieldRef<"dSalesOrder", 'Int'>
  readonly IdentCustomer: Prisma.FieldRef<"dSalesOrder", 'Int'>
  readonly IdentAddressLocation: Prisma.FieldRef<"dSalesOrder", 'Int'>
  readonly IdentAddressBill: Prisma.FieldRef<"dSalesOrder", 'Int'>
  readonly IdentAddressShip: Prisma.FieldRef<"dSalesOrder", 'Int'>
  readonly IdentAddressShipper: Prisma.FieldRef<"dSalesOrder", 'Int'>
  readonly IdentAddressCarrier: Prisma.FieldRef<"dSalesOrder", 'Int'>
  readonly IdentAddressDestination: Prisma.FieldRef<"dSalesOrder", 'Int'>
  readonly IdentAddressDistribution: Prisma.FieldRef<"dSalesOrder", 'Int'>
}
    

// Custom InputTypes
/**
 * dSalesOrder findUnique
 */
export type dSalesOrderFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dSalesOrder
   */
  select?: Prisma.dSalesOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dSalesOrder
   */
  omit?: Prisma.dSalesOrderOmit<ExtArgs> | null
  /**
   * Filter, which dSalesOrder to fetch.
   */
  where: Prisma.dSalesOrderWhereUniqueInput
}

/**
 * dSalesOrder findUniqueOrThrow
 */
export type dSalesOrderFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dSalesOrder
   */
  select?: Prisma.dSalesOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dSalesOrder
   */
  omit?: Prisma.dSalesOrderOmit<ExtArgs> | null
  /**
   * Filter, which dSalesOrder to fetch.
   */
  where: Prisma.dSalesOrderWhereUniqueInput
}

/**
 * dSalesOrder findFirst
 */
export type dSalesOrderFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dSalesOrder
   */
  select?: Prisma.dSalesOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dSalesOrder
   */
  omit?: Prisma.dSalesOrderOmit<ExtArgs> | null
  /**
   * Filter, which dSalesOrder to fetch.
   */
  where?: Prisma.dSalesOrderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of dSalesOrders to fetch.
   */
  orderBy?: Prisma.dSalesOrderOrderByWithRelationInput | Prisma.dSalesOrderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for dSalesOrders.
   */
  cursor?: Prisma.dSalesOrderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` dSalesOrders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` dSalesOrders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of dSalesOrders.
   */
  distinct?: Prisma.DSalesOrderScalarFieldEnum | Prisma.DSalesOrderScalarFieldEnum[]
}

/**
 * dSalesOrder findFirstOrThrow
 */
export type dSalesOrderFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dSalesOrder
   */
  select?: Prisma.dSalesOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dSalesOrder
   */
  omit?: Prisma.dSalesOrderOmit<ExtArgs> | null
  /**
   * Filter, which dSalesOrder to fetch.
   */
  where?: Prisma.dSalesOrderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of dSalesOrders to fetch.
   */
  orderBy?: Prisma.dSalesOrderOrderByWithRelationInput | Prisma.dSalesOrderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for dSalesOrders.
   */
  cursor?: Prisma.dSalesOrderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` dSalesOrders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` dSalesOrders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of dSalesOrders.
   */
  distinct?: Prisma.DSalesOrderScalarFieldEnum | Prisma.DSalesOrderScalarFieldEnum[]
}

/**
 * dSalesOrder findMany
 */
export type dSalesOrderFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dSalesOrder
   */
  select?: Prisma.dSalesOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dSalesOrder
   */
  omit?: Prisma.dSalesOrderOmit<ExtArgs> | null
  /**
   * Filter, which dSalesOrders to fetch.
   */
  where?: Prisma.dSalesOrderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of dSalesOrders to fetch.
   */
  orderBy?: Prisma.dSalesOrderOrderByWithRelationInput | Prisma.dSalesOrderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing dSalesOrders.
   */
  cursor?: Prisma.dSalesOrderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` dSalesOrders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` dSalesOrders.
   */
  skip?: number
  distinct?: Prisma.DSalesOrderScalarFieldEnum | Prisma.DSalesOrderScalarFieldEnum[]
}

/**
 * dSalesOrder create
 */
export type dSalesOrderCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dSalesOrder
   */
  select?: Prisma.dSalesOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dSalesOrder
   */
  omit?: Prisma.dSalesOrderOmit<ExtArgs> | null
  /**
   * The data needed to create a dSalesOrder.
   */
  data: Prisma.XOR<Prisma.dSalesOrderCreateInput, Prisma.dSalesOrderUncheckedCreateInput>
}

/**
 * dSalesOrder createMany
 */
export type dSalesOrderCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many dSalesOrders.
   */
  data: Prisma.dSalesOrderCreateManyInput | Prisma.dSalesOrderCreateManyInput[]
}

/**
 * dSalesOrder update
 */
export type dSalesOrderUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dSalesOrder
   */
  select?: Prisma.dSalesOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dSalesOrder
   */
  omit?: Prisma.dSalesOrderOmit<ExtArgs> | null
  /**
   * The data needed to update a dSalesOrder.
   */
  data: Prisma.XOR<Prisma.dSalesOrderUpdateInput, Prisma.dSalesOrderUncheckedUpdateInput>
  /**
   * Choose, which dSalesOrder to update.
   */
  where: Prisma.dSalesOrderWhereUniqueInput
}

/**
 * dSalesOrder updateMany
 */
export type dSalesOrderUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update dSalesOrders.
   */
  data: Prisma.XOR<Prisma.dSalesOrderUpdateManyMutationInput, Prisma.dSalesOrderUncheckedUpdateManyInput>
  /**
   * Filter which dSalesOrders to update
   */
  where?: Prisma.dSalesOrderWhereInput
  /**
   * Limit how many dSalesOrders to update.
   */
  limit?: number
}

/**
 * dSalesOrder upsert
 */
export type dSalesOrderUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dSalesOrder
   */
  select?: Prisma.dSalesOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dSalesOrder
   */
  omit?: Prisma.dSalesOrderOmit<ExtArgs> | null
  /**
   * The filter to search for the dSalesOrder to update in case it exists.
   */
  where: Prisma.dSalesOrderWhereUniqueInput
  /**
   * In case the dSalesOrder found by the `where` argument doesn't exist, create a new dSalesOrder with this data.
   */
  create: Prisma.XOR<Prisma.dSalesOrderCreateInput, Prisma.dSalesOrderUncheckedCreateInput>
  /**
   * In case the dSalesOrder was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.dSalesOrderUpdateInput, Prisma.dSalesOrderUncheckedUpdateInput>
}

/**
 * dSalesOrder delete
 */
export type dSalesOrderDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dSalesOrder
   */
  select?: Prisma.dSalesOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dSalesOrder
   */
  omit?: Prisma.dSalesOrderOmit<ExtArgs> | null
  /**
   * Filter which dSalesOrder to delete.
   */
  where: Prisma.dSalesOrderWhereUniqueInput
}

/**
 * dSalesOrder deleteMany
 */
export type dSalesOrderDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which dSalesOrders to delete
   */
  where?: Prisma.dSalesOrderWhereInput
  /**
   * Limit how many dSalesOrders to delete.
   */
  limit?: number
}

/**
 * dSalesOrder without action
 */
export type dSalesOrderDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dSalesOrder
   */
  select?: Prisma.dSalesOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dSalesOrder
   */
  omit?: Prisma.dSalesOrderOmit<ExtArgs> | null
}
