
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `dStation` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model dStation
 * 
 */
export type dStationModel = runtime.Types.Result.DefaultSelection<Prisma.$dStationPayload>

export type AggregateDStation = {
  _count: DStationCountAggregateOutputType | null
  _avg: DStationAvgAggregateOutputType | null
  _sum: DStationSumAggregateOutputType | null
  _min: DStationMinAggregateOutputType | null
  _max: DStationMaxAggregateOutputType | null
}

export type DStationAvgAggregateOutputType = {
  Identifier: number | null
  CreationID: number | null
  MaintenanceID: number | null
  StationNumber: number | null
  StationPort: number | null
  IdentAddress: number | null
}

export type DStationSumAggregateOutputType = {
  Identifier: number | null
  CreationID: number | null
  MaintenanceID: number | null
  StationNumber: number | null
  StationPort: number | null
  IdentAddress: number | null
}

export type DStationMinAggregateOutputType = {
  Identifier: number | null
  Status: string | null
  Creation: Date | null
  CreationID: number | null
  Maintenance: Date | null
  MaintenanceID: number | null
  StationType: string | null
  StationID: string | null
  StationName: string | null
  StationMachine: string | null
  StationMenu: string | null
  StationNumber: number | null
  StationIP: string | null
  StationPort: number | null
  IdentAddress: number | null
  LotCode: string | null
  TransferProgram: Date | null
  TransferTable: Date | null
  Comment1: string | null
  Comment2: string | null
  Comment3: string | null
  Comment4: string | null
  Comment5: string | null
  Comment6: string | null
}

export type DStationMaxAggregateOutputType = {
  Identifier: number | null
  Status: string | null
  Creation: Date | null
  CreationID: number | null
  Maintenance: Date | null
  MaintenanceID: number | null
  StationType: string | null
  StationID: string | null
  StationName: string | null
  StationMachine: string | null
  StationMenu: string | null
  StationNumber: number | null
  StationIP: string | null
  StationPort: number | null
  IdentAddress: number | null
  LotCode: string | null
  TransferProgram: Date | null
  TransferTable: Date | null
  Comment1: string | null
  Comment2: string | null
  Comment3: string | null
  Comment4: string | null
  Comment5: string | null
  Comment6: string | null
}

export type DStationCountAggregateOutputType = {
  Identifier: number
  Status: number
  Creation: number
  CreationID: number
  Maintenance: number
  MaintenanceID: number
  StationType: number
  StationID: number
  StationName: number
  StationMachine: number
  StationMenu: number
  StationNumber: number
  StationIP: number
  StationPort: number
  IdentAddress: number
  LotCode: number
  TransferProgram: number
  TransferTable: number
  Comment1: number
  Comment2: number
  Comment3: number
  Comment4: number
  Comment5: number
  Comment6: number
  _all: number
}


export type DStationAvgAggregateInputType = {
  Identifier?: true
  CreationID?: true
  MaintenanceID?: true
  StationNumber?: true
  StationPort?: true
  IdentAddress?: true
}

export type DStationSumAggregateInputType = {
  Identifier?: true
  CreationID?: true
  MaintenanceID?: true
  StationNumber?: true
  StationPort?: true
  IdentAddress?: true
}

export type DStationMinAggregateInputType = {
  Identifier?: true
  Status?: true
  Creation?: true
  CreationID?: true
  Maintenance?: true
  MaintenanceID?: true
  StationType?: true
  StationID?: true
  StationName?: true
  StationMachine?: true
  StationMenu?: true
  StationNumber?: true
  StationIP?: true
  StationPort?: true
  IdentAddress?: true
  LotCode?: true
  TransferProgram?: true
  TransferTable?: true
  Comment1?: true
  Comment2?: true
  Comment3?: true
  Comment4?: true
  Comment5?: true
  Comment6?: true
}

export type DStationMaxAggregateInputType = {
  Identifier?: true
  Status?: true
  Creation?: true
  CreationID?: true
  Maintenance?: true
  MaintenanceID?: true
  StationType?: true
  StationID?: true
  StationName?: true
  StationMachine?: true
  StationMenu?: true
  StationNumber?: true
  StationIP?: true
  StationPort?: true
  IdentAddress?: true
  LotCode?: true
  TransferProgram?: true
  TransferTable?: true
  Comment1?: true
  Comment2?: true
  Comment3?: true
  Comment4?: true
  Comment5?: true
  Comment6?: true
}

export type DStationCountAggregateInputType = {
  Identifier?: true
  Status?: true
  Creation?: true
  CreationID?: true
  Maintenance?: true
  MaintenanceID?: true
  StationType?: true
  StationID?: true
  StationName?: true
  StationMachine?: true
  StationMenu?: true
  StationNumber?: true
  StationIP?: true
  StationPort?: true
  IdentAddress?: true
  LotCode?: true
  TransferProgram?: true
  TransferTable?: true
  Comment1?: true
  Comment2?: true
  Comment3?: true
  Comment4?: true
  Comment5?: true
  Comment6?: true
  _all?: true
}

export type DStationAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which dStation to aggregate.
   */
  where?: Prisma.dStationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of dStations to fetch.
   */
  orderBy?: Prisma.dStationOrderByWithRelationInput | Prisma.dStationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.dStationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` dStations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` dStations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned dStations
  **/
  _count?: true | DStationCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: DStationAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: DStationSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DStationMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DStationMaxAggregateInputType
}

export type GetDStationAggregateType<T extends DStationAggregateArgs> = {
      [P in keyof T & keyof AggregateDStation]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDStation[P]>
    : Prisma.GetScalarType<T[P], AggregateDStation[P]>
}




export type dStationGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.dStationWhereInput
  orderBy?: Prisma.dStationOrderByWithAggregationInput | Prisma.dStationOrderByWithAggregationInput[]
  by: Prisma.DStationScalarFieldEnum[] | Prisma.DStationScalarFieldEnum
  having?: Prisma.dStationScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DStationCountAggregateInputType | true
  _avg?: DStationAvgAggregateInputType
  _sum?: DStationSumAggregateInputType
  _min?: DStationMinAggregateInputType
  _max?: DStationMaxAggregateInputType
}

export type DStationGroupByOutputType = {
  Identifier: number
  Status: string
  Creation: Date
  CreationID: number
  Maintenance: Date
  MaintenanceID: number
  StationType: string
  StationID: string
  StationName: string | null
  StationMachine: string | null
  StationMenu: string | null
  StationNumber: number
  StationIP: string | null
  StationPort: number
  IdentAddress: number
  LotCode: string | null
  TransferProgram: Date
  TransferTable: Date
  Comment1: string | null
  Comment2: string | null
  Comment3: string | null
  Comment4: string | null
  Comment5: string | null
  Comment6: string | null
  _count: DStationCountAggregateOutputType | null
  _avg: DStationAvgAggregateOutputType | null
  _sum: DStationSumAggregateOutputType | null
  _min: DStationMinAggregateOutputType | null
  _max: DStationMaxAggregateOutputType | null
}

type GetDStationGroupByPayload<T extends dStationGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DStationGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DStationGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DStationGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DStationGroupByOutputType[P]>
      }
    >
  >



export type dStationWhereInput = {
  AND?: Prisma.dStationWhereInput | Prisma.dStationWhereInput[]
  OR?: Prisma.dStationWhereInput[]
  NOT?: Prisma.dStationWhereInput | Prisma.dStationWhereInput[]
  Identifier?: Prisma.IntFilter<"dStation"> | number
  Status?: Prisma.StringFilter<"dStation"> | string
  Creation?: Prisma.DateTimeFilter<"dStation"> | Date | string
  CreationID?: Prisma.IntFilter<"dStation"> | number
  Maintenance?: Prisma.DateTimeFilter<"dStation"> | Date | string
  MaintenanceID?: Prisma.IntFilter<"dStation"> | number
  StationType?: Prisma.StringFilter<"dStation"> | string
  StationID?: Prisma.StringFilter<"dStation"> | string
  StationName?: Prisma.StringNullableFilter<"dStation"> | string | null
  StationMachine?: Prisma.StringNullableFilter<"dStation"> | string | null
  StationMenu?: Prisma.StringNullableFilter<"dStation"> | string | null
  StationNumber?: Prisma.IntFilter<"dStation"> | number
  StationIP?: Prisma.StringNullableFilter<"dStation"> | string | null
  StationPort?: Prisma.IntFilter<"dStation"> | number
  IdentAddress?: Prisma.IntFilter<"dStation"> | number
  LotCode?: Prisma.StringNullableFilter<"dStation"> | string | null
  TransferProgram?: Prisma.DateTimeFilter<"dStation"> | Date | string
  TransferTable?: Prisma.DateTimeFilter<"dStation"> | Date | string
  Comment1?: Prisma.StringNullableFilter<"dStation"> | string | null
  Comment2?: Prisma.StringNullableFilter<"dStation"> | string | null
  Comment3?: Prisma.StringNullableFilter<"dStation"> | string | null
  Comment4?: Prisma.StringNullableFilter<"dStation"> | string | null
  Comment5?: Prisma.StringNullableFilter<"dStation"> | string | null
  Comment6?: Prisma.StringNullableFilter<"dStation"> | string | null
}

export type dStationOrderByWithRelationInput = {
  Identifier?: Prisma.SortOrder
  Status?: Prisma.SortOrder
  Creation?: Prisma.SortOrder
  CreationID?: Prisma.SortOrder
  Maintenance?: Prisma.SortOrder
  MaintenanceID?: Prisma.SortOrder
  StationType?: Prisma.SortOrder
  StationID?: Prisma.SortOrder
  StationName?: Prisma.SortOrderInput | Prisma.SortOrder
  StationMachine?: Prisma.SortOrderInput | Prisma.SortOrder
  StationMenu?: Prisma.SortOrderInput | Prisma.SortOrder
  StationNumber?: Prisma.SortOrder
  StationIP?: Prisma.SortOrderInput | Prisma.SortOrder
  StationPort?: Prisma.SortOrder
  IdentAddress?: Prisma.SortOrder
  LotCode?: Prisma.SortOrderInput | Prisma.SortOrder
  TransferProgram?: Prisma.SortOrder
  TransferTable?: Prisma.SortOrder
  Comment1?: Prisma.SortOrderInput | Prisma.SortOrder
  Comment2?: Prisma.SortOrderInput | Prisma.SortOrder
  Comment3?: Prisma.SortOrderInput | Prisma.SortOrder
  Comment4?: Prisma.SortOrderInput | Prisma.SortOrder
  Comment5?: Prisma.SortOrderInput | Prisma.SortOrder
  Comment6?: Prisma.SortOrderInput | Prisma.SortOrder
}

export type dStationWhereUniqueInput = Prisma.AtLeast<{
  Identifier?: number
  StationID?: string
  StationName?: string
  AND?: Prisma.dStationWhereInput | Prisma.dStationWhereInput[]
  OR?: Prisma.dStationWhereInput[]
  NOT?: Prisma.dStationWhereInput | Prisma.dStationWhereInput[]
  Status?: Prisma.StringFilter<"dStation"> | string
  Creation?: Prisma.DateTimeFilter<"dStation"> | Date | string
  CreationID?: Prisma.IntFilter<"dStation"> | number
  Maintenance?: Prisma.DateTimeFilter<"dStation"> | Date | string
  MaintenanceID?: Prisma.IntFilter<"dStation"> | number
  StationType?: Prisma.StringFilter<"dStation"> | string
  StationMachine?: Prisma.StringNullableFilter<"dStation"> | string | null
  StationMenu?: Prisma.StringNullableFilter<"dStation"> | string | null
  StationNumber?: Prisma.IntFilter<"dStation"> | number
  StationIP?: Prisma.StringNullableFilter<"dStation"> | string | null
  StationPort?: Prisma.IntFilter<"dStation"> | number
  IdentAddress?: Prisma.IntFilter<"dStation"> | number
  LotCode?: Prisma.StringNullableFilter<"dStation"> | string | null
  TransferProgram?: Prisma.DateTimeFilter<"dStation"> | Date | string
  TransferTable?: Prisma.DateTimeFilter<"dStation"> | Date | string
  Comment1?: Prisma.StringNullableFilter<"dStation"> | string | null
  Comment2?: Prisma.StringNullableFilter<"dStation"> | string | null
  Comment3?: Prisma.StringNullableFilter<"dStation"> | string | null
  Comment4?: Prisma.StringNullableFilter<"dStation"> | string | null
  Comment5?: Prisma.StringNullableFilter<"dStation"> | string | null
  Comment6?: Prisma.StringNullableFilter<"dStation"> | string | null
}, "Identifier" | "StationID" | "StationName">

export type dStationOrderByWithAggregationInput = {
  Identifier?: Prisma.SortOrder
  Status?: Prisma.SortOrder
  Creation?: Prisma.SortOrder
  CreationID?: Prisma.SortOrder
  Maintenance?: Prisma.SortOrder
  MaintenanceID?: Prisma.SortOrder
  StationType?: Prisma.SortOrder
  StationID?: Prisma.SortOrder
  StationName?: Prisma.SortOrderInput | Prisma.SortOrder
  StationMachine?: Prisma.SortOrderInput | Prisma.SortOrder
  StationMenu?: Prisma.SortOrderInput | Prisma.SortOrder
  StationNumber?: Prisma.SortOrder
  StationIP?: Prisma.SortOrderInput | Prisma.SortOrder
  StationPort?: Prisma.SortOrder
  IdentAddress?: Prisma.SortOrder
  LotCode?: Prisma.SortOrderInput | Prisma.SortOrder
  TransferProgram?: Prisma.SortOrder
  TransferTable?: Prisma.SortOrder
  Comment1?: Prisma.SortOrderInput | Prisma.SortOrder
  Comment2?: Prisma.SortOrderInput | Prisma.SortOrder
  Comment3?: Prisma.SortOrderInput | Prisma.SortOrder
  Comment4?: Prisma.SortOrderInput | Prisma.SortOrder
  Comment5?: Prisma.SortOrderInput | Prisma.SortOrder
  Comment6?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.dStationCountOrderByAggregateInput
  _avg?: Prisma.dStationAvgOrderByAggregateInput
  _max?: Prisma.dStationMaxOrderByAggregateInput
  _min?: Prisma.dStationMinOrderByAggregateInput
  _sum?: Prisma.dStationSumOrderByAggregateInput
}

export type dStationScalarWhereWithAggregatesInput = {
  AND?: Prisma.dStationScalarWhereWithAggregatesInput | Prisma.dStationScalarWhereWithAggregatesInput[]
  OR?: Prisma.dStationScalarWhereWithAggregatesInput[]
  NOT?: Prisma.dStationScalarWhereWithAggregatesInput | Prisma.dStationScalarWhereWithAggregatesInput[]
  Identifier?: Prisma.IntWithAggregatesFilter<"dStation"> | number
  Status?: Prisma.StringWithAggregatesFilter<"dStation"> | string
  Creation?: Prisma.DateTimeWithAggregatesFilter<"dStation"> | Date | string
  CreationID?: Prisma.IntWithAggregatesFilter<"dStation"> | number
  Maintenance?: Prisma.DateTimeWithAggregatesFilter<"dStation"> | Date | string
  MaintenanceID?: Prisma.IntWithAggregatesFilter<"dStation"> | number
  StationType?: Prisma.StringWithAggregatesFilter<"dStation"> | string
  StationID?: Prisma.StringWithAggregatesFilter<"dStation"> | string
  StationName?: Prisma.StringNullableWithAggregatesFilter<"dStation"> | string | null
  StationMachine?: Prisma.StringNullableWithAggregatesFilter<"dStation"> | string | null
  StationMenu?: Prisma.StringNullableWithAggregatesFilter<"dStation"> | string | null
  StationNumber?: Prisma.IntWithAggregatesFilter<"dStation"> | number
  StationIP?: Prisma.StringNullableWithAggregatesFilter<"dStation"> | string | null
  StationPort?: Prisma.IntWithAggregatesFilter<"dStation"> | number
  IdentAddress?: Prisma.IntWithAggregatesFilter<"dStation"> | number
  LotCode?: Prisma.StringNullableWithAggregatesFilter<"dStation"> | string | null
  TransferProgram?: Prisma.DateTimeWithAggregatesFilter<"dStation"> | Date | string
  TransferTable?: Prisma.DateTimeWithAggregatesFilter<"dStation"> | Date | string
  Comment1?: Prisma.StringNullableWithAggregatesFilter<"dStation"> | string | null
  Comment2?: Prisma.StringNullableWithAggregatesFilter<"dStation"> | string | null
  Comment3?: Prisma.StringNullableWithAggregatesFilter<"dStation"> | string | null
  Comment4?: Prisma.StringNullableWithAggregatesFilter<"dStation"> | string | null
  Comment5?: Prisma.StringNullableWithAggregatesFilter<"dStation"> | string | null
  Comment6?: Prisma.StringNullableWithAggregatesFilter<"dStation"> | string | null
}

export type dStationCreateInput = {
  Status?: string
  Creation?: Date | string
  CreationID?: number
  Maintenance?: Date | string
  MaintenanceID?: number
  StationType: string
  StationID: string
  StationName?: string | null
  StationMachine?: string | null
  StationMenu?: string | null
  StationNumber?: number
  StationIP?: string | null
  StationPort?: number
  IdentAddress?: number
  LotCode?: string | null
  TransferProgram?: Date | string
  TransferTable?: Date | string
  Comment1?: string | null
  Comment2?: string | null
  Comment3?: string | null
  Comment4?: string | null
  Comment5?: string | null
  Comment6?: string | null
}

export type dStationUncheckedCreateInput = {
  Identifier?: number
  Status?: string
  Creation?: Date | string
  CreationID?: number
  Maintenance?: Date | string
  MaintenanceID?: number
  StationType: string
  StationID: string
  StationName?: string | null
  StationMachine?: string | null
  StationMenu?: string | null
  StationNumber?: number
  StationIP?: string | null
  StationPort?: number
  IdentAddress?: number
  LotCode?: string | null
  TransferProgram?: Date | string
  TransferTable?: Date | string
  Comment1?: string | null
  Comment2?: string | null
  Comment3?: string | null
  Comment4?: string | null
  Comment5?: string | null
  Comment6?: string | null
}

export type dStationUpdateInput = {
  Status?: Prisma.StringFieldUpdateOperationsInput | string
  Creation?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  CreationID?: Prisma.IntFieldUpdateOperationsInput | number
  Maintenance?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  MaintenanceID?: Prisma.IntFieldUpdateOperationsInput | number
  StationType?: Prisma.StringFieldUpdateOperationsInput | string
  StationID?: Prisma.StringFieldUpdateOperationsInput | string
  StationName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  StationMachine?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  StationMenu?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  StationNumber?: Prisma.IntFieldUpdateOperationsInput | number
  StationIP?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  StationPort?: Prisma.IntFieldUpdateOperationsInput | number
  IdentAddress?: Prisma.IntFieldUpdateOperationsInput | number
  LotCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  TransferProgram?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  TransferTable?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Comment1?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Comment2?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Comment3?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Comment4?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Comment5?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Comment6?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type dStationUncheckedUpdateInput = {
  Identifier?: Prisma.IntFieldUpdateOperationsInput | number
  Status?: Prisma.StringFieldUpdateOperationsInput | string
  Creation?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  CreationID?: Prisma.IntFieldUpdateOperationsInput | number
  Maintenance?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  MaintenanceID?: Prisma.IntFieldUpdateOperationsInput | number
  StationType?: Prisma.StringFieldUpdateOperationsInput | string
  StationID?: Prisma.StringFieldUpdateOperationsInput | string
  StationName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  StationMachine?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  StationMenu?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  StationNumber?: Prisma.IntFieldUpdateOperationsInput | number
  StationIP?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  StationPort?: Prisma.IntFieldUpdateOperationsInput | number
  IdentAddress?: Prisma.IntFieldUpdateOperationsInput | number
  LotCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  TransferProgram?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  TransferTable?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Comment1?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Comment2?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Comment3?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Comment4?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Comment5?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Comment6?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type dStationCreateManyInput = {
  Status?: string
  Creation?: Date | string
  CreationID?: number
  Maintenance?: Date | string
  MaintenanceID?: number
  StationType: string
  StationID: string
  StationName?: string | null
  StationMachine?: string | null
  StationMenu?: string | null
  StationNumber?: number
  StationIP?: string | null
  StationPort?: number
  IdentAddress?: number
  LotCode?: string | null
  TransferProgram?: Date | string
  TransferTable?: Date | string
  Comment1?: string | null
  Comment2?: string | null
  Comment3?: string | null
  Comment4?: string | null
  Comment5?: string | null
  Comment6?: string | null
}

export type dStationUpdateManyMutationInput = {
  Status?: Prisma.StringFieldUpdateOperationsInput | string
  Creation?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  CreationID?: Prisma.IntFieldUpdateOperationsInput | number
  Maintenance?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  MaintenanceID?: Prisma.IntFieldUpdateOperationsInput | number
  StationType?: Prisma.StringFieldUpdateOperationsInput | string
  StationID?: Prisma.StringFieldUpdateOperationsInput | string
  StationName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  StationMachine?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  StationMenu?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  StationNumber?: Prisma.IntFieldUpdateOperationsInput | number
  StationIP?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  StationPort?: Prisma.IntFieldUpdateOperationsInput | number
  IdentAddress?: Prisma.IntFieldUpdateOperationsInput | number
  LotCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  TransferProgram?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  TransferTable?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Comment1?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Comment2?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Comment3?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Comment4?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Comment5?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Comment6?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type dStationUncheckedUpdateManyInput = {
  Identifier?: Prisma.IntFieldUpdateOperationsInput | number
  Status?: Prisma.StringFieldUpdateOperationsInput | string
  Creation?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  CreationID?: Prisma.IntFieldUpdateOperationsInput | number
  Maintenance?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  MaintenanceID?: Prisma.IntFieldUpdateOperationsInput | number
  StationType?: Prisma.StringFieldUpdateOperationsInput | string
  StationID?: Prisma.StringFieldUpdateOperationsInput | string
  StationName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  StationMachine?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  StationMenu?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  StationNumber?: Prisma.IntFieldUpdateOperationsInput | number
  StationIP?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  StationPort?: Prisma.IntFieldUpdateOperationsInput | number
  IdentAddress?: Prisma.IntFieldUpdateOperationsInput | number
  LotCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  TransferProgram?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  TransferTable?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Comment1?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Comment2?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Comment3?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Comment4?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Comment5?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Comment6?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type dStationCountOrderByAggregateInput = {
  Identifier?: Prisma.SortOrder
  Status?: Prisma.SortOrder
  Creation?: Prisma.SortOrder
  CreationID?: Prisma.SortOrder
  Maintenance?: Prisma.SortOrder
  MaintenanceID?: Prisma.SortOrder
  StationType?: Prisma.SortOrder
  StationID?: Prisma.SortOrder
  StationName?: Prisma.SortOrder
  StationMachine?: Prisma.SortOrder
  StationMenu?: Prisma.SortOrder
  StationNumber?: Prisma.SortOrder
  StationIP?: Prisma.SortOrder
  StationPort?: Prisma.SortOrder
  IdentAddress?: Prisma.SortOrder
  LotCode?: Prisma.SortOrder
  TransferProgram?: Prisma.SortOrder
  TransferTable?: Prisma.SortOrder
  Comment1?: Prisma.SortOrder
  Comment2?: Prisma.SortOrder
  Comment3?: Prisma.SortOrder
  Comment4?: Prisma.SortOrder
  Comment5?: Prisma.SortOrder
  Comment6?: Prisma.SortOrder
}

export type dStationAvgOrderByAggregateInput = {
  Identifier?: Prisma.SortOrder
  CreationID?: Prisma.SortOrder
  MaintenanceID?: Prisma.SortOrder
  StationNumber?: Prisma.SortOrder
  StationPort?: Prisma.SortOrder
  IdentAddress?: Prisma.SortOrder
}

export type dStationMaxOrderByAggregateInput = {
  Identifier?: Prisma.SortOrder
  Status?: Prisma.SortOrder
  Creation?: Prisma.SortOrder
  CreationID?: Prisma.SortOrder
  Maintenance?: Prisma.SortOrder
  MaintenanceID?: Prisma.SortOrder
  StationType?: Prisma.SortOrder
  StationID?: Prisma.SortOrder
  StationName?: Prisma.SortOrder
  StationMachine?: Prisma.SortOrder
  StationMenu?: Prisma.SortOrder
  StationNumber?: Prisma.SortOrder
  StationIP?: Prisma.SortOrder
  StationPort?: Prisma.SortOrder
  IdentAddress?: Prisma.SortOrder
  LotCode?: Prisma.SortOrder
  TransferProgram?: Prisma.SortOrder
  TransferTable?: Prisma.SortOrder
  Comment1?: Prisma.SortOrder
  Comment2?: Prisma.SortOrder
  Comment3?: Prisma.SortOrder
  Comment4?: Prisma.SortOrder
  Comment5?: Prisma.SortOrder
  Comment6?: Prisma.SortOrder
}

export type dStationMinOrderByAggregateInput = {
  Identifier?: Prisma.SortOrder
  Status?: Prisma.SortOrder
  Creation?: Prisma.SortOrder
  CreationID?: Prisma.SortOrder
  Maintenance?: Prisma.SortOrder
  MaintenanceID?: Prisma.SortOrder
  StationType?: Prisma.SortOrder
  StationID?: Prisma.SortOrder
  StationName?: Prisma.SortOrder
  StationMachine?: Prisma.SortOrder
  StationMenu?: Prisma.SortOrder
  StationNumber?: Prisma.SortOrder
  StationIP?: Prisma.SortOrder
  StationPort?: Prisma.SortOrder
  IdentAddress?: Prisma.SortOrder
  LotCode?: Prisma.SortOrder
  TransferProgram?: Prisma.SortOrder
  TransferTable?: Prisma.SortOrder
  Comment1?: Prisma.SortOrder
  Comment2?: Prisma.SortOrder
  Comment3?: Prisma.SortOrder
  Comment4?: Prisma.SortOrder
  Comment5?: Prisma.SortOrder
  Comment6?: Prisma.SortOrder
}

export type dStationSumOrderByAggregateInput = {
  Identifier?: Prisma.SortOrder
  CreationID?: Prisma.SortOrder
  MaintenanceID?: Prisma.SortOrder
  StationNumber?: Prisma.SortOrder
  StationPort?: Prisma.SortOrder
  IdentAddress?: Prisma.SortOrder
}



export type dStationSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  Identifier?: boolean
  Status?: boolean
  Creation?: boolean
  CreationID?: boolean
  Maintenance?: boolean
  MaintenanceID?: boolean
  StationType?: boolean
  StationID?: boolean
  StationName?: boolean
  StationMachine?: boolean
  StationMenu?: boolean
  StationNumber?: boolean
  StationIP?: boolean
  StationPort?: boolean
  IdentAddress?: boolean
  LotCode?: boolean
  TransferProgram?: boolean
  TransferTable?: boolean
  Comment1?: boolean
  Comment2?: boolean
  Comment3?: boolean
  Comment4?: boolean
  Comment5?: boolean
  Comment6?: boolean
}, ExtArgs["result"]["dStation"]>



export type dStationSelectScalar = {
  Identifier?: boolean
  Status?: boolean
  Creation?: boolean
  CreationID?: boolean
  Maintenance?: boolean
  MaintenanceID?: boolean
  StationType?: boolean
  StationID?: boolean
  StationName?: boolean
  StationMachine?: boolean
  StationMenu?: boolean
  StationNumber?: boolean
  StationIP?: boolean
  StationPort?: boolean
  IdentAddress?: boolean
  LotCode?: boolean
  TransferProgram?: boolean
  TransferTable?: boolean
  Comment1?: boolean
  Comment2?: boolean
  Comment3?: boolean
  Comment4?: boolean
  Comment5?: boolean
  Comment6?: boolean
}

export type dStationOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"Identifier" | "Status" | "Creation" | "CreationID" | "Maintenance" | "MaintenanceID" | "StationType" | "StationID" | "StationName" | "StationMachine" | "StationMenu" | "StationNumber" | "StationIP" | "StationPort" | "IdentAddress" | "LotCode" | "TransferProgram" | "TransferTable" | "Comment1" | "Comment2" | "Comment3" | "Comment4" | "Comment5" | "Comment6", ExtArgs["result"]["dStation"]>

export type $dStationPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "dStation"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    Identifier: number
    Status: string
    Creation: Date
    CreationID: number
    Maintenance: Date
    MaintenanceID: number
    StationType: string
    StationID: string
    StationName: string | null
    StationMachine: string | null
    StationMenu: string | null
    StationNumber: number
    StationIP: string | null
    StationPort: number
    IdentAddress: number
    LotCode: string | null
    TransferProgram: Date
    TransferTable: Date
    Comment1: string | null
    Comment2: string | null
    Comment3: string | null
    Comment4: string | null
    Comment5: string | null
    Comment6: string | null
  }, ExtArgs["result"]["dStation"]>
  composites: {}
}

export type dStationGetPayload<S extends boolean | null | undefined | dStationDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$dStationPayload, S>

export type dStationCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<dStationFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DStationCountAggregateInputType | true
  }

export interface dStationDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['dStation'], meta: { name: 'dStation' } }
  /**
   * Find zero or one DStation that matches the filter.
   * @param {dStationFindUniqueArgs} args - Arguments to find a DStation
   * @example
   * // Get one DStation
   * const dStation = await prisma.dStation.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends dStationFindUniqueArgs>(args: Prisma.SelectSubset<T, dStationFindUniqueArgs<ExtArgs>>): Prisma.Prisma__dStationClient<runtime.Types.Result.GetResult<Prisma.$dStationPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one DStation that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {dStationFindUniqueOrThrowArgs} args - Arguments to find a DStation
   * @example
   * // Get one DStation
   * const dStation = await prisma.dStation.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends dStationFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, dStationFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__dStationClient<runtime.Types.Result.GetResult<Prisma.$dStationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DStation that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dStationFindFirstArgs} args - Arguments to find a DStation
   * @example
   * // Get one DStation
   * const dStation = await prisma.dStation.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends dStationFindFirstArgs>(args?: Prisma.SelectSubset<T, dStationFindFirstArgs<ExtArgs>>): Prisma.Prisma__dStationClient<runtime.Types.Result.GetResult<Prisma.$dStationPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DStation that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dStationFindFirstOrThrowArgs} args - Arguments to find a DStation
   * @example
   * // Get one DStation
   * const dStation = await prisma.dStation.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends dStationFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, dStationFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__dStationClient<runtime.Types.Result.GetResult<Prisma.$dStationPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more DStations that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dStationFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all DStations
   * const dStations = await prisma.dStation.findMany()
   * 
   * // Get first 10 DStations
   * const dStations = await prisma.dStation.findMany({ take: 10 })
   * 
   * // Only select the `Identifier`
   * const dStationWithIdentifierOnly = await prisma.dStation.findMany({ select: { Identifier: true } })
   * 
   */
  findMany<T extends dStationFindManyArgs>(args?: Prisma.SelectSubset<T, dStationFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$dStationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a DStation.
   * @param {dStationCreateArgs} args - Arguments to create a DStation.
   * @example
   * // Create one DStation
   * const DStation = await prisma.dStation.create({
   *   data: {
   *     // ... data to create a DStation
   *   }
   * })
   * 
   */
  create<T extends dStationCreateArgs>(args: Prisma.SelectSubset<T, dStationCreateArgs<ExtArgs>>): Prisma.Prisma__dStationClient<runtime.Types.Result.GetResult<Prisma.$dStationPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many DStations.
   * @param {dStationCreateManyArgs} args - Arguments to create many DStations.
   * @example
   * // Create many DStations
   * const dStation = await prisma.dStation.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends dStationCreateManyArgs>(args?: Prisma.SelectSubset<T, dStationCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a DStation.
   * @param {dStationDeleteArgs} args - Arguments to delete one DStation.
   * @example
   * // Delete one DStation
   * const DStation = await prisma.dStation.delete({
   *   where: {
   *     // ... filter to delete one DStation
   *   }
   * })
   * 
   */
  delete<T extends dStationDeleteArgs>(args: Prisma.SelectSubset<T, dStationDeleteArgs<ExtArgs>>): Prisma.Prisma__dStationClient<runtime.Types.Result.GetResult<Prisma.$dStationPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one DStation.
   * @param {dStationUpdateArgs} args - Arguments to update one DStation.
   * @example
   * // Update one DStation
   * const dStation = await prisma.dStation.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends dStationUpdateArgs>(args: Prisma.SelectSubset<T, dStationUpdateArgs<ExtArgs>>): Prisma.Prisma__dStationClient<runtime.Types.Result.GetResult<Prisma.$dStationPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more DStations.
   * @param {dStationDeleteManyArgs} args - Arguments to filter DStations to delete.
   * @example
   * // Delete a few DStations
   * const { count } = await prisma.dStation.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends dStationDeleteManyArgs>(args?: Prisma.SelectSubset<T, dStationDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DStations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dStationUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many DStations
   * const dStation = await prisma.dStation.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends dStationUpdateManyArgs>(args: Prisma.SelectSubset<T, dStationUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one DStation.
   * @param {dStationUpsertArgs} args - Arguments to update or create a DStation.
   * @example
   * // Update or create a DStation
   * const dStation = await prisma.dStation.upsert({
   *   create: {
   *     // ... data to create a DStation
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the DStation we want to update
   *   }
   * })
   */
  upsert<T extends dStationUpsertArgs>(args: Prisma.SelectSubset<T, dStationUpsertArgs<ExtArgs>>): Prisma.Prisma__dStationClient<runtime.Types.Result.GetResult<Prisma.$dStationPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of DStations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dStationCountArgs} args - Arguments to filter DStations to count.
   * @example
   * // Count the number of DStations
   * const count = await prisma.dStation.count({
   *   where: {
   *     // ... the filter for the DStations we want to count
   *   }
   * })
  **/
  count<T extends dStationCountArgs>(
    args?: Prisma.Subset<T, dStationCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DStationCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a DStation.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DStationAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DStationAggregateArgs>(args: Prisma.Subset<T, DStationAggregateArgs>): Prisma.PrismaPromise<GetDStationAggregateType<T>>

  /**
   * Group by DStation.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dStationGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends dStationGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: dStationGroupByArgs['orderBy'] }
      : { orderBy?: dStationGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, dStationGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDStationGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the dStation model
 */
readonly fields: dStationFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for dStation.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__dStationClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the dStation model
 */
export interface dStationFieldRefs {
  readonly Identifier: Prisma.FieldRef<"dStation", 'Int'>
  readonly Status: Prisma.FieldRef<"dStation", 'String'>
  readonly Creation: Prisma.FieldRef<"dStation", 'DateTime'>
  readonly CreationID: Prisma.FieldRef<"dStation", 'Int'>
  readonly Maintenance: Prisma.FieldRef<"dStation", 'DateTime'>
  readonly MaintenanceID: Prisma.FieldRef<"dStation", 'Int'>
  readonly StationType: Prisma.FieldRef<"dStation", 'String'>
  readonly StationID: Prisma.FieldRef<"dStation", 'String'>
  readonly StationName: Prisma.FieldRef<"dStation", 'String'>
  readonly StationMachine: Prisma.FieldRef<"dStation", 'String'>
  readonly StationMenu: Prisma.FieldRef<"dStation", 'String'>
  readonly StationNumber: Prisma.FieldRef<"dStation", 'Int'>
  readonly StationIP: Prisma.FieldRef<"dStation", 'String'>
  readonly StationPort: Prisma.FieldRef<"dStation", 'Int'>
  readonly IdentAddress: Prisma.FieldRef<"dStation", 'Int'>
  readonly LotCode: Prisma.FieldRef<"dStation", 'String'>
  readonly TransferProgram: Prisma.FieldRef<"dStation", 'DateTime'>
  readonly TransferTable: Prisma.FieldRef<"dStation", 'DateTime'>
  readonly Comment1: Prisma.FieldRef<"dStation", 'String'>
  readonly Comment2: Prisma.FieldRef<"dStation", 'String'>
  readonly Comment3: Prisma.FieldRef<"dStation", 'String'>
  readonly Comment4: Prisma.FieldRef<"dStation", 'String'>
  readonly Comment5: Prisma.FieldRef<"dStation", 'String'>
  readonly Comment6: Prisma.FieldRef<"dStation", 'String'>
}
    

// Custom InputTypes
/**
 * dStation findUnique
 */
export type dStationFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dStation
   */
  select?: Prisma.dStationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dStation
   */
  omit?: Prisma.dStationOmit<ExtArgs> | null
  /**
   * Filter, which dStation to fetch.
   */
  where: Prisma.dStationWhereUniqueInput
}

/**
 * dStation findUniqueOrThrow
 */
export type dStationFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dStation
   */
  select?: Prisma.dStationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dStation
   */
  omit?: Prisma.dStationOmit<ExtArgs> | null
  /**
   * Filter, which dStation to fetch.
   */
  where: Prisma.dStationWhereUniqueInput
}

/**
 * dStation findFirst
 */
export type dStationFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dStation
   */
  select?: Prisma.dStationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dStation
   */
  omit?: Prisma.dStationOmit<ExtArgs> | null
  /**
   * Filter, which dStation to fetch.
   */
  where?: Prisma.dStationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of dStations to fetch.
   */
  orderBy?: Prisma.dStationOrderByWithRelationInput | Prisma.dStationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for dStations.
   */
  cursor?: Prisma.dStationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` dStations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` dStations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of dStations.
   */
  distinct?: Prisma.DStationScalarFieldEnum | Prisma.DStationScalarFieldEnum[]
}

/**
 * dStation findFirstOrThrow
 */
export type dStationFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dStation
   */
  select?: Prisma.dStationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dStation
   */
  omit?: Prisma.dStationOmit<ExtArgs> | null
  /**
   * Filter, which dStation to fetch.
   */
  where?: Prisma.dStationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of dStations to fetch.
   */
  orderBy?: Prisma.dStationOrderByWithRelationInput | Prisma.dStationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for dStations.
   */
  cursor?: Prisma.dStationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` dStations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` dStations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of dStations.
   */
  distinct?: Prisma.DStationScalarFieldEnum | Prisma.DStationScalarFieldEnum[]
}

/**
 * dStation findMany
 */
export type dStationFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dStation
   */
  select?: Prisma.dStationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dStation
   */
  omit?: Prisma.dStationOmit<ExtArgs> | null
  /**
   * Filter, which dStations to fetch.
   */
  where?: Prisma.dStationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of dStations to fetch.
   */
  orderBy?: Prisma.dStationOrderByWithRelationInput | Prisma.dStationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing dStations.
   */
  cursor?: Prisma.dStationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` dStations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` dStations.
   */
  skip?: number
  distinct?: Prisma.DStationScalarFieldEnum | Prisma.DStationScalarFieldEnum[]
}

/**
 * dStation create
 */
export type dStationCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dStation
   */
  select?: Prisma.dStationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dStation
   */
  omit?: Prisma.dStationOmit<ExtArgs> | null
  /**
   * The data needed to create a dStation.
   */
  data: Prisma.XOR<Prisma.dStationCreateInput, Prisma.dStationUncheckedCreateInput>
}

/**
 * dStation createMany
 */
export type dStationCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many dStations.
   */
  data: Prisma.dStationCreateManyInput | Prisma.dStationCreateManyInput[]
}

/**
 * dStation update
 */
export type dStationUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dStation
   */
  select?: Prisma.dStationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dStation
   */
  omit?: Prisma.dStationOmit<ExtArgs> | null
  /**
   * The data needed to update a dStation.
   */
  data: Prisma.XOR<Prisma.dStationUpdateInput, Prisma.dStationUncheckedUpdateInput>
  /**
   * Choose, which dStation to update.
   */
  where: Prisma.dStationWhereUniqueInput
}

/**
 * dStation updateMany
 */
export type dStationUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update dStations.
   */
  data: Prisma.XOR<Prisma.dStationUpdateManyMutationInput, Prisma.dStationUncheckedUpdateManyInput>
  /**
   * Filter which dStations to update
   */
  where?: Prisma.dStationWhereInput
  /**
   * Limit how many dStations to update.
   */
  limit?: number
}

/**
 * dStation upsert
 */
export type dStationUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dStation
   */
  select?: Prisma.dStationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dStation
   */
  omit?: Prisma.dStationOmit<ExtArgs> | null
  /**
   * The filter to search for the dStation to update in case it exists.
   */
  where: Prisma.dStationWhereUniqueInput
  /**
   * In case the dStation found by the `where` argument doesn't exist, create a new dStation with this data.
   */
  create: Prisma.XOR<Prisma.dStationCreateInput, Prisma.dStationUncheckedCreateInput>
  /**
   * In case the dStation was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.dStationUpdateInput, Prisma.dStationUncheckedUpdateInput>
}

/**
 * dStation delete
 */
export type dStationDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dStation
   */
  select?: Prisma.dStationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dStation
   */
  omit?: Prisma.dStationOmit<ExtArgs> | null
  /**
   * Filter which dStation to delete.
   */
  where: Prisma.dStationWhereUniqueInput
}

/**
 * dStation deleteMany
 */
export type dStationDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which dStations to delete
   */
  where?: Prisma.dStationWhereInput
  /**
   * Limit how many dStations to delete.
   */
  limit?: number
}

/**
 * dStation without action
 */
export type dStationDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dStation
   */
  select?: Prisma.dStationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dStation
   */
  omit?: Prisma.dStationOmit<ExtArgs> | null
}
