
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `dStockPropertyPivot` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model dStockPropertyPivot
 * 
 */
export type dStockPropertyPivotModel = runtime.Types.Result.DefaultSelection<Prisma.$dStockPropertyPivotPayload>

export type AggregateDStockPropertyPivot = {
  _count: DStockPropertyPivotCountAggregateOutputType | null
  _avg: DStockPropertyPivotAvgAggregateOutputType | null
  _sum: DStockPropertyPivotSumAggregateOutputType | null
  _min: DStockPropertyPivotMinAggregateOutputType | null
  _max: DStockPropertyPivotMaxAggregateOutputType | null
}

export type DStockPropertyPivotAvgAggregateOutputType = {
  Identifier: number | null
  CreationID: number | null
  MaintenanceID: number | null
  IdentStock: number | null
  IdentStockPropertyGEAR: number | null
  IdentStockPropertyGRADE: number | null
  IdentStockPropertyCONDITION: number | null
  IdentStockPropertyPACKAGE: number | null
  IdentStockPropertyBOAT: number | null
  IdentStockPropertyUSER: number | null
  IdentStockPropertyPORT: number | null
  IdentStockPropertyALLERGY: number | null
  IdentPropertyGEAR: number | null
  IdentPropertyGRADE: number | null
  IdentPropertyCONDITION: number | null
  IdentPropertyPACKAGE: number | null
  IdentPropertyBOAT: number | null
  IdentPropertyUSER: number | null
  IdentPropertyPORT: number | null
  IdentPropertyALLERGY: number | null
}

export type DStockPropertyPivotSumAggregateOutputType = {
  Identifier: number | null
  CreationID: number | null
  MaintenanceID: number | null
  IdentStock: number | null
  IdentStockPropertyGEAR: number | null
  IdentStockPropertyGRADE: number | null
  IdentStockPropertyCONDITION: number | null
  IdentStockPropertyPACKAGE: number | null
  IdentStockPropertyBOAT: number | null
  IdentStockPropertyUSER: number | null
  IdentStockPropertyPORT: number | null
  IdentStockPropertyALLERGY: number | null
  IdentPropertyGEAR: number | null
  IdentPropertyGRADE: number | null
  IdentPropertyCONDITION: number | null
  IdentPropertyPACKAGE: number | null
  IdentPropertyBOAT: number | null
  IdentPropertyUSER: number | null
  IdentPropertyPORT: number | null
  IdentPropertyALLERGY: number | null
}

export type DStockPropertyPivotMinAggregateOutputType = {
  Identifier: number | null
  Status: string | null
  Creation: Date | null
  CreationID: number | null
  Maintenance: Date | null
  MaintenanceID: number | null
  IdentStock: number | null
  Serial: string | null
  UpdateFlag: boolean | null
  IdentStockPropertyGEAR: number | null
  IdentStockPropertyGRADE: number | null
  IdentStockPropertyCONDITION: number | null
  IdentStockPropertyPACKAGE: number | null
  IdentStockPropertyBOAT: number | null
  IdentStockPropertyUSER: number | null
  IdentStockPropertyPORT: number | null
  IdentStockPropertyALLERGY: number | null
  IdentPropertyGEAR: number | null
  IdentPropertyGRADE: number | null
  IdentPropertyCONDITION: number | null
  IdentPropertyPACKAGE: number | null
  IdentPropertyBOAT: number | null
  IdentPropertyUSER: number | null
  IdentPropertyPORT: number | null
  IdentPropertyALLERGY: number | null
  NameGEAR: string | null
  NameGRADE: string | null
  NameCONDITION: string | null
  NamePACKAGE: string | null
  NameBOAT: string | null
  NameUSER: string | null
  NamePORT: string | null
  NameALLERGY: string | null
  ShortGEAR: string | null
  ShortGRADE: string | null
  ShortCONDITION: string | null
  ShortPACKAGE: string | null
  ShortBOAT: string | null
  ShortUSER: string | null
  ShortPORT: string | null
  ShortALLERGY: string | null
  BarcodeGEAR: string | null
  BarcodeGRADE: string | null
  BarcodeCONDITION: string | null
  BarcodePACKAGE: string | null
  BarcodeBOAT: string | null
  BarcodeUSER: string | null
  BarcodePORT: string | null
  BarcodeALLERGY: string | null
}

export type DStockPropertyPivotMaxAggregateOutputType = {
  Identifier: number | null
  Status: string | null
  Creation: Date | null
  CreationID: number | null
  Maintenance: Date | null
  MaintenanceID: number | null
  IdentStock: number | null
  Serial: string | null
  UpdateFlag: boolean | null
  IdentStockPropertyGEAR: number | null
  IdentStockPropertyGRADE: number | null
  IdentStockPropertyCONDITION: number | null
  IdentStockPropertyPACKAGE: number | null
  IdentStockPropertyBOAT: number | null
  IdentStockPropertyUSER: number | null
  IdentStockPropertyPORT: number | null
  IdentStockPropertyALLERGY: number | null
  IdentPropertyGEAR: number | null
  IdentPropertyGRADE: number | null
  IdentPropertyCONDITION: number | null
  IdentPropertyPACKAGE: number | null
  IdentPropertyBOAT: number | null
  IdentPropertyUSER: number | null
  IdentPropertyPORT: number | null
  IdentPropertyALLERGY: number | null
  NameGEAR: string | null
  NameGRADE: string | null
  NameCONDITION: string | null
  NamePACKAGE: string | null
  NameBOAT: string | null
  NameUSER: string | null
  NamePORT: string | null
  NameALLERGY: string | null
  ShortGEAR: string | null
  ShortGRADE: string | null
  ShortCONDITION: string | null
  ShortPACKAGE: string | null
  ShortBOAT: string | null
  ShortUSER: string | null
  ShortPORT: string | null
  ShortALLERGY: string | null
  BarcodeGEAR: string | null
  BarcodeGRADE: string | null
  BarcodeCONDITION: string | null
  BarcodePACKAGE: string | null
  BarcodeBOAT: string | null
  BarcodeUSER: string | null
  BarcodePORT: string | null
  BarcodeALLERGY: string | null
}

export type DStockPropertyPivotCountAggregateOutputType = {
  Identifier: number
  Status: number
  Creation: number
  CreationID: number
  Maintenance: number
  MaintenanceID: number
  IdentStock: number
  Serial: number
  UpdateFlag: number
  IdentStockPropertyGEAR: number
  IdentStockPropertyGRADE: number
  IdentStockPropertyCONDITION: number
  IdentStockPropertyPACKAGE: number
  IdentStockPropertyBOAT: number
  IdentStockPropertyUSER: number
  IdentStockPropertyPORT: number
  IdentStockPropertyALLERGY: number
  IdentPropertyGEAR: number
  IdentPropertyGRADE: number
  IdentPropertyCONDITION: number
  IdentPropertyPACKAGE: number
  IdentPropertyBOAT: number
  IdentPropertyUSER: number
  IdentPropertyPORT: number
  IdentPropertyALLERGY: number
  NameGEAR: number
  NameGRADE: number
  NameCONDITION: number
  NamePACKAGE: number
  NameBOAT: number
  NameUSER: number
  NamePORT: number
  NameALLERGY: number
  ShortGEAR: number
  ShortGRADE: number
  ShortCONDITION: number
  ShortPACKAGE: number
  ShortBOAT: number
  ShortUSER: number
  ShortPORT: number
  ShortALLERGY: number
  BarcodeGEAR: number
  BarcodeGRADE: number
  BarcodeCONDITION: number
  BarcodePACKAGE: number
  BarcodeBOAT: number
  BarcodeUSER: number
  BarcodePORT: number
  BarcodeALLERGY: number
  _all: number
}


export type DStockPropertyPivotAvgAggregateInputType = {
  Identifier?: true
  CreationID?: true
  MaintenanceID?: true
  IdentStock?: true
  IdentStockPropertyGEAR?: true
  IdentStockPropertyGRADE?: true
  IdentStockPropertyCONDITION?: true
  IdentStockPropertyPACKAGE?: true
  IdentStockPropertyBOAT?: true
  IdentStockPropertyUSER?: true
  IdentStockPropertyPORT?: true
  IdentStockPropertyALLERGY?: true
  IdentPropertyGEAR?: true
  IdentPropertyGRADE?: true
  IdentPropertyCONDITION?: true
  IdentPropertyPACKAGE?: true
  IdentPropertyBOAT?: true
  IdentPropertyUSER?: true
  IdentPropertyPORT?: true
  IdentPropertyALLERGY?: true
}

export type DStockPropertyPivotSumAggregateInputType = {
  Identifier?: true
  CreationID?: true
  MaintenanceID?: true
  IdentStock?: true
  IdentStockPropertyGEAR?: true
  IdentStockPropertyGRADE?: true
  IdentStockPropertyCONDITION?: true
  IdentStockPropertyPACKAGE?: true
  IdentStockPropertyBOAT?: true
  IdentStockPropertyUSER?: true
  IdentStockPropertyPORT?: true
  IdentStockPropertyALLERGY?: true
  IdentPropertyGEAR?: true
  IdentPropertyGRADE?: true
  IdentPropertyCONDITION?: true
  IdentPropertyPACKAGE?: true
  IdentPropertyBOAT?: true
  IdentPropertyUSER?: true
  IdentPropertyPORT?: true
  IdentPropertyALLERGY?: true
}

export type DStockPropertyPivotMinAggregateInputType = {
  Identifier?: true
  Status?: true
  Creation?: true
  CreationID?: true
  Maintenance?: true
  MaintenanceID?: true
  IdentStock?: true
  Serial?: true
  UpdateFlag?: true
  IdentStockPropertyGEAR?: true
  IdentStockPropertyGRADE?: true
  IdentStockPropertyCONDITION?: true
  IdentStockPropertyPACKAGE?: true
  IdentStockPropertyBOAT?: true
  IdentStockPropertyUSER?: true
  IdentStockPropertyPORT?: true
  IdentStockPropertyALLERGY?: true
  IdentPropertyGEAR?: true
  IdentPropertyGRADE?: true
  IdentPropertyCONDITION?: true
  IdentPropertyPACKAGE?: true
  IdentPropertyBOAT?: true
  IdentPropertyUSER?: true
  IdentPropertyPORT?: true
  IdentPropertyALLERGY?: true
  NameGEAR?: true
  NameGRADE?: true
  NameCONDITION?: true
  NamePACKAGE?: true
  NameBOAT?: true
  NameUSER?: true
  NamePORT?: true
  NameALLERGY?: true
  ShortGEAR?: true
  ShortGRADE?: true
  ShortCONDITION?: true
  ShortPACKAGE?: true
  ShortBOAT?: true
  ShortUSER?: true
  ShortPORT?: true
  ShortALLERGY?: true
  BarcodeGEAR?: true
  BarcodeGRADE?: true
  BarcodeCONDITION?: true
  BarcodePACKAGE?: true
  BarcodeBOAT?: true
  BarcodeUSER?: true
  BarcodePORT?: true
  BarcodeALLERGY?: true
}

export type DStockPropertyPivotMaxAggregateInputType = {
  Identifier?: true
  Status?: true
  Creation?: true
  CreationID?: true
  Maintenance?: true
  MaintenanceID?: true
  IdentStock?: true
  Serial?: true
  UpdateFlag?: true
  IdentStockPropertyGEAR?: true
  IdentStockPropertyGRADE?: true
  IdentStockPropertyCONDITION?: true
  IdentStockPropertyPACKAGE?: true
  IdentStockPropertyBOAT?: true
  IdentStockPropertyUSER?: true
  IdentStockPropertyPORT?: true
  IdentStockPropertyALLERGY?: true
  IdentPropertyGEAR?: true
  IdentPropertyGRADE?: true
  IdentPropertyCONDITION?: true
  IdentPropertyPACKAGE?: true
  IdentPropertyBOAT?: true
  IdentPropertyUSER?: true
  IdentPropertyPORT?: true
  IdentPropertyALLERGY?: true
  NameGEAR?: true
  NameGRADE?: true
  NameCONDITION?: true
  NamePACKAGE?: true
  NameBOAT?: true
  NameUSER?: true
  NamePORT?: true
  NameALLERGY?: true
  ShortGEAR?: true
  ShortGRADE?: true
  ShortCONDITION?: true
  ShortPACKAGE?: true
  ShortBOAT?: true
  ShortUSER?: true
  ShortPORT?: true
  ShortALLERGY?: true
  BarcodeGEAR?: true
  BarcodeGRADE?: true
  BarcodeCONDITION?: true
  BarcodePACKAGE?: true
  BarcodeBOAT?: true
  BarcodeUSER?: true
  BarcodePORT?: true
  BarcodeALLERGY?: true
}

export type DStockPropertyPivotCountAggregateInputType = {
  Identifier?: true
  Status?: true
  Creation?: true
  CreationID?: true
  Maintenance?: true
  MaintenanceID?: true
  IdentStock?: true
  Serial?: true
  UpdateFlag?: true
  IdentStockPropertyGEAR?: true
  IdentStockPropertyGRADE?: true
  IdentStockPropertyCONDITION?: true
  IdentStockPropertyPACKAGE?: true
  IdentStockPropertyBOAT?: true
  IdentStockPropertyUSER?: true
  IdentStockPropertyPORT?: true
  IdentStockPropertyALLERGY?: true
  IdentPropertyGEAR?: true
  IdentPropertyGRADE?: true
  IdentPropertyCONDITION?: true
  IdentPropertyPACKAGE?: true
  IdentPropertyBOAT?: true
  IdentPropertyUSER?: true
  IdentPropertyPORT?: true
  IdentPropertyALLERGY?: true
  NameGEAR?: true
  NameGRADE?: true
  NameCONDITION?: true
  NamePACKAGE?: true
  NameBOAT?: true
  NameUSER?: true
  NamePORT?: true
  NameALLERGY?: true
  ShortGEAR?: true
  ShortGRADE?: true
  ShortCONDITION?: true
  ShortPACKAGE?: true
  ShortBOAT?: true
  ShortUSER?: true
  ShortPORT?: true
  ShortALLERGY?: true
  BarcodeGEAR?: true
  BarcodeGRADE?: true
  BarcodeCONDITION?: true
  BarcodePACKAGE?: true
  BarcodeBOAT?: true
  BarcodeUSER?: true
  BarcodePORT?: true
  BarcodeALLERGY?: true
  _all?: true
}

export type DStockPropertyPivotAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which dStockPropertyPivot to aggregate.
   */
  where?: Prisma.dStockPropertyPivotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of dStockPropertyPivots to fetch.
   */
  orderBy?: Prisma.dStockPropertyPivotOrderByWithRelationInput | Prisma.dStockPropertyPivotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.dStockPropertyPivotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` dStockPropertyPivots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` dStockPropertyPivots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned dStockPropertyPivots
  **/
  _count?: true | DStockPropertyPivotCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: DStockPropertyPivotAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: DStockPropertyPivotSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DStockPropertyPivotMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DStockPropertyPivotMaxAggregateInputType
}

export type GetDStockPropertyPivotAggregateType<T extends DStockPropertyPivotAggregateArgs> = {
      [P in keyof T & keyof AggregateDStockPropertyPivot]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDStockPropertyPivot[P]>
    : Prisma.GetScalarType<T[P], AggregateDStockPropertyPivot[P]>
}




export type dStockPropertyPivotGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.dStockPropertyPivotWhereInput
  orderBy?: Prisma.dStockPropertyPivotOrderByWithAggregationInput | Prisma.dStockPropertyPivotOrderByWithAggregationInput[]
  by: Prisma.DStockPropertyPivotScalarFieldEnum[] | Prisma.DStockPropertyPivotScalarFieldEnum
  having?: Prisma.dStockPropertyPivotScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DStockPropertyPivotCountAggregateInputType | true
  _avg?: DStockPropertyPivotAvgAggregateInputType
  _sum?: DStockPropertyPivotSumAggregateInputType
  _min?: DStockPropertyPivotMinAggregateInputType
  _max?: DStockPropertyPivotMaxAggregateInputType
}

export type DStockPropertyPivotGroupByOutputType = {
  Identifier: number
  Status: string
  Creation: Date
  CreationID: number
  Maintenance: Date
  MaintenanceID: number
  IdentStock: number
  Serial: string
  UpdateFlag: boolean
  IdentStockPropertyGEAR: number
  IdentStockPropertyGRADE: number
  IdentStockPropertyCONDITION: number
  IdentStockPropertyPACKAGE: number
  IdentStockPropertyBOAT: number
  IdentStockPropertyUSER: number
  IdentStockPropertyPORT: number
  IdentStockPropertyALLERGY: number
  IdentPropertyGEAR: number
  IdentPropertyGRADE: number
  IdentPropertyCONDITION: number
  IdentPropertyPACKAGE: number
  IdentPropertyBOAT: number
  IdentPropertyUSER: number
  IdentPropertyPORT: number
  IdentPropertyALLERGY: number
  NameGEAR: string | null
  NameGRADE: string | null
  NameCONDITION: string | null
  NamePACKAGE: string | null
  NameBOAT: string | null
  NameUSER: string | null
  NamePORT: string | null
  NameALLERGY: string | null
  ShortGEAR: string | null
  ShortGRADE: string | null
  ShortCONDITION: string | null
  ShortPACKAGE: string | null
  ShortBOAT: string | null
  ShortUSER: string | null
  ShortPORT: string | null
  ShortALLERGY: string | null
  BarcodeGEAR: string | null
  BarcodeGRADE: string | null
  BarcodeCONDITION: string | null
  BarcodePACKAGE: string | null
  BarcodeBOAT: string | null
  BarcodeUSER: string | null
  BarcodePORT: string | null
  BarcodeALLERGY: string | null
  _count: DStockPropertyPivotCountAggregateOutputType | null
  _avg: DStockPropertyPivotAvgAggregateOutputType | null
  _sum: DStockPropertyPivotSumAggregateOutputType | null
  _min: DStockPropertyPivotMinAggregateOutputType | null
  _max: DStockPropertyPivotMaxAggregateOutputType | null
}

type GetDStockPropertyPivotGroupByPayload<T extends dStockPropertyPivotGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DStockPropertyPivotGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DStockPropertyPivotGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DStockPropertyPivotGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DStockPropertyPivotGroupByOutputType[P]>
      }
    >
  >



export type dStockPropertyPivotWhereInput = {
  AND?: Prisma.dStockPropertyPivotWhereInput | Prisma.dStockPropertyPivotWhereInput[]
  OR?: Prisma.dStockPropertyPivotWhereInput[]
  NOT?: Prisma.dStockPropertyPivotWhereInput | Prisma.dStockPropertyPivotWhereInput[]
  Identifier?: Prisma.IntFilter<"dStockPropertyPivot"> | number
  Status?: Prisma.StringFilter<"dStockPropertyPivot"> | string
  Creation?: Prisma.DateTimeFilter<"dStockPropertyPivot"> | Date | string
  CreationID?: Prisma.IntFilter<"dStockPropertyPivot"> | number
  Maintenance?: Prisma.DateTimeFilter<"dStockPropertyPivot"> | Date | string
  MaintenanceID?: Prisma.IntFilter<"dStockPropertyPivot"> | number
  IdentStock?: Prisma.IntFilter<"dStockPropertyPivot"> | number
  Serial?: Prisma.StringFilter<"dStockPropertyPivot"> | string
  UpdateFlag?: Prisma.BoolFilter<"dStockPropertyPivot"> | boolean
  IdentStockPropertyGEAR?: Prisma.IntFilter<"dStockPropertyPivot"> | number
  IdentStockPropertyGRADE?: Prisma.IntFilter<"dStockPropertyPivot"> | number
  IdentStockPropertyCONDITION?: Prisma.IntFilter<"dStockPropertyPivot"> | number
  IdentStockPropertyPACKAGE?: Prisma.IntFilter<"dStockPropertyPivot"> | number
  IdentStockPropertyBOAT?: Prisma.IntFilter<"dStockPropertyPivot"> | number
  IdentStockPropertyUSER?: Prisma.IntFilter<"dStockPropertyPivot"> | number
  IdentStockPropertyPORT?: Prisma.IntFilter<"dStockPropertyPivot"> | number
  IdentStockPropertyALLERGY?: Prisma.IntFilter<"dStockPropertyPivot"> | number
  IdentPropertyGEAR?: Prisma.IntFilter<"dStockPropertyPivot"> | number
  IdentPropertyGRADE?: Prisma.IntFilter<"dStockPropertyPivot"> | number
  IdentPropertyCONDITION?: Prisma.IntFilter<"dStockPropertyPivot"> | number
  IdentPropertyPACKAGE?: Prisma.IntFilter<"dStockPropertyPivot"> | number
  IdentPropertyBOAT?: Prisma.IntFilter<"dStockPropertyPivot"> | number
  IdentPropertyUSER?: Prisma.IntFilter<"dStockPropertyPivot"> | number
  IdentPropertyPORT?: Prisma.IntFilter<"dStockPropertyPivot"> | number
  IdentPropertyALLERGY?: Prisma.IntFilter<"dStockPropertyPivot"> | number
  NameGEAR?: Prisma.StringNullableFilter<"dStockPropertyPivot"> | string | null
  NameGRADE?: Prisma.StringNullableFilter<"dStockPropertyPivot"> | string | null
  NameCONDITION?: Prisma.StringNullableFilter<"dStockPropertyPivot"> | string | null
  NamePACKAGE?: Prisma.StringNullableFilter<"dStockPropertyPivot"> | string | null
  NameBOAT?: Prisma.StringNullableFilter<"dStockPropertyPivot"> | string | null
  NameUSER?: Prisma.StringNullableFilter<"dStockPropertyPivot"> | string | null
  NamePORT?: Prisma.StringNullableFilter<"dStockPropertyPivot"> | string | null
  NameALLERGY?: Prisma.StringNullableFilter<"dStockPropertyPivot"> | string | null
  ShortGEAR?: Prisma.StringNullableFilter<"dStockPropertyPivot"> | string | null
  ShortGRADE?: Prisma.StringNullableFilter<"dStockPropertyPivot"> | string | null
  ShortCONDITION?: Prisma.StringNullableFilter<"dStockPropertyPivot"> | string | null
  ShortPACKAGE?: Prisma.StringNullableFilter<"dStockPropertyPivot"> | string | null
  ShortBOAT?: Prisma.StringNullableFilter<"dStockPropertyPivot"> | string | null
  ShortUSER?: Prisma.StringNullableFilter<"dStockPropertyPivot"> | string | null
  ShortPORT?: Prisma.StringNullableFilter<"dStockPropertyPivot"> | string | null
  ShortALLERGY?: Prisma.StringNullableFilter<"dStockPropertyPivot"> | string | null
  BarcodeGEAR?: Prisma.StringNullableFilter<"dStockPropertyPivot"> | string | null
  BarcodeGRADE?: Prisma.StringNullableFilter<"dStockPropertyPivot"> | string | null
  BarcodeCONDITION?: Prisma.StringNullableFilter<"dStockPropertyPivot"> | string | null
  BarcodePACKAGE?: Prisma.StringNullableFilter<"dStockPropertyPivot"> | string | null
  BarcodeBOAT?: Prisma.StringNullableFilter<"dStockPropertyPivot"> | string | null
  BarcodeUSER?: Prisma.StringNullableFilter<"dStockPropertyPivot"> | string | null
  BarcodePORT?: Prisma.StringNullableFilter<"dStockPropertyPivot"> | string | null
  BarcodeALLERGY?: Prisma.StringNullableFilter<"dStockPropertyPivot"> | string | null
}

export type dStockPropertyPivotOrderByWithRelationInput = {
  Identifier?: Prisma.SortOrder
  Status?: Prisma.SortOrder
  Creation?: Prisma.SortOrder
  CreationID?: Prisma.SortOrder
  Maintenance?: Prisma.SortOrder
  MaintenanceID?: Prisma.SortOrder
  IdentStock?: Prisma.SortOrder
  Serial?: Prisma.SortOrder
  UpdateFlag?: Prisma.SortOrder
  IdentStockPropertyGEAR?: Prisma.SortOrder
  IdentStockPropertyGRADE?: Prisma.SortOrder
  IdentStockPropertyCONDITION?: Prisma.SortOrder
  IdentStockPropertyPACKAGE?: Prisma.SortOrder
  IdentStockPropertyBOAT?: Prisma.SortOrder
  IdentStockPropertyUSER?: Prisma.SortOrder
  IdentStockPropertyPORT?: Prisma.SortOrder
  IdentStockPropertyALLERGY?: Prisma.SortOrder
  IdentPropertyGEAR?: Prisma.SortOrder
  IdentPropertyGRADE?: Prisma.SortOrder
  IdentPropertyCONDITION?: Prisma.SortOrder
  IdentPropertyPACKAGE?: Prisma.SortOrder
  IdentPropertyBOAT?: Prisma.SortOrder
  IdentPropertyUSER?: Prisma.SortOrder
  IdentPropertyPORT?: Prisma.SortOrder
  IdentPropertyALLERGY?: Prisma.SortOrder
  NameGEAR?: Prisma.SortOrderInput | Prisma.SortOrder
  NameGRADE?: Prisma.SortOrderInput | Prisma.SortOrder
  NameCONDITION?: Prisma.SortOrderInput | Prisma.SortOrder
  NamePACKAGE?: Prisma.SortOrderInput | Prisma.SortOrder
  NameBOAT?: Prisma.SortOrderInput | Prisma.SortOrder
  NameUSER?: Prisma.SortOrderInput | Prisma.SortOrder
  NamePORT?: Prisma.SortOrderInput | Prisma.SortOrder
  NameALLERGY?: Prisma.SortOrderInput | Prisma.SortOrder
  ShortGEAR?: Prisma.SortOrderInput | Prisma.SortOrder
  ShortGRADE?: Prisma.SortOrderInput | Prisma.SortOrder
  ShortCONDITION?: Prisma.SortOrderInput | Prisma.SortOrder
  ShortPACKAGE?: Prisma.SortOrderInput | Prisma.SortOrder
  ShortBOAT?: Prisma.SortOrderInput | Prisma.SortOrder
  ShortUSER?: Prisma.SortOrderInput | Prisma.SortOrder
  ShortPORT?: Prisma.SortOrderInput | Prisma.SortOrder
  ShortALLERGY?: Prisma.SortOrderInput | Prisma.SortOrder
  BarcodeGEAR?: Prisma.SortOrderInput | Prisma.SortOrder
  BarcodeGRADE?: Prisma.SortOrderInput | Prisma.SortOrder
  BarcodeCONDITION?: Prisma.SortOrderInput | Prisma.SortOrder
  BarcodePACKAGE?: Prisma.SortOrderInput | Prisma.SortOrder
  BarcodeBOAT?: Prisma.SortOrderInput | Prisma.SortOrder
  BarcodeUSER?: Prisma.SortOrderInput | Prisma.SortOrder
  BarcodePORT?: Prisma.SortOrderInput | Prisma.SortOrder
  BarcodeALLERGY?: Prisma.SortOrderInput | Prisma.SortOrder
}

export type dStockPropertyPivotWhereUniqueInput = Prisma.AtLeast<{
  IdentStock?: number
  Serial?: string
  AND?: Prisma.dStockPropertyPivotWhereInput | Prisma.dStockPropertyPivotWhereInput[]
  OR?: Prisma.dStockPropertyPivotWhereInput[]
  NOT?: Prisma.dStockPropertyPivotWhereInput | Prisma.dStockPropertyPivotWhereInput[]
  Identifier?: Prisma.IntFilter<"dStockPropertyPivot"> | number
  Status?: Prisma.StringFilter<"dStockPropertyPivot"> | string
  Creation?: Prisma.DateTimeFilter<"dStockPropertyPivot"> | Date | string
  CreationID?: Prisma.IntFilter<"dStockPropertyPivot"> | number
  Maintenance?: Prisma.DateTimeFilter<"dStockPropertyPivot"> | Date | string
  MaintenanceID?: Prisma.IntFilter<"dStockPropertyPivot"> | number
  UpdateFlag?: Prisma.BoolFilter<"dStockPropertyPivot"> | boolean
  IdentStockPropertyGEAR?: Prisma.IntFilter<"dStockPropertyPivot"> | number
  IdentStockPropertyGRADE?: Prisma.IntFilter<"dStockPropertyPivot"> | number
  IdentStockPropertyCONDITION?: Prisma.IntFilter<"dStockPropertyPivot"> | number
  IdentStockPropertyPACKAGE?: Prisma.IntFilter<"dStockPropertyPivot"> | number
  IdentStockPropertyBOAT?: Prisma.IntFilter<"dStockPropertyPivot"> | number
  IdentStockPropertyUSER?: Prisma.IntFilter<"dStockPropertyPivot"> | number
  IdentStockPropertyPORT?: Prisma.IntFilter<"dStockPropertyPivot"> | number
  IdentStockPropertyALLERGY?: Prisma.IntFilter<"dStockPropertyPivot"> | number
  IdentPropertyGEAR?: Prisma.IntFilter<"dStockPropertyPivot"> | number
  IdentPropertyGRADE?: Prisma.IntFilter<"dStockPropertyPivot"> | number
  IdentPropertyCONDITION?: Prisma.IntFilter<"dStockPropertyPivot"> | number
  IdentPropertyPACKAGE?: Prisma.IntFilter<"dStockPropertyPivot"> | number
  IdentPropertyBOAT?: Prisma.IntFilter<"dStockPropertyPivot"> | number
  IdentPropertyUSER?: Prisma.IntFilter<"dStockPropertyPivot"> | number
  IdentPropertyPORT?: Prisma.IntFilter<"dStockPropertyPivot"> | number
  IdentPropertyALLERGY?: Prisma.IntFilter<"dStockPropertyPivot"> | number
  NameGEAR?: Prisma.StringNullableFilter<"dStockPropertyPivot"> | string | null
  NameGRADE?: Prisma.StringNullableFilter<"dStockPropertyPivot"> | string | null
  NameCONDITION?: Prisma.StringNullableFilter<"dStockPropertyPivot"> | string | null
  NamePACKAGE?: Prisma.StringNullableFilter<"dStockPropertyPivot"> | string | null
  NameBOAT?: Prisma.StringNullableFilter<"dStockPropertyPivot"> | string | null
  NameUSER?: Prisma.StringNullableFilter<"dStockPropertyPivot"> | string | null
  NamePORT?: Prisma.StringNullableFilter<"dStockPropertyPivot"> | string | null
  NameALLERGY?: Prisma.StringNullableFilter<"dStockPropertyPivot"> | string | null
  ShortGEAR?: Prisma.StringNullableFilter<"dStockPropertyPivot"> | string | null
  ShortGRADE?: Prisma.StringNullableFilter<"dStockPropertyPivot"> | string | null
  ShortCONDITION?: Prisma.StringNullableFilter<"dStockPropertyPivot"> | string | null
  ShortPACKAGE?: Prisma.StringNullableFilter<"dStockPropertyPivot"> | string | null
  ShortBOAT?: Prisma.StringNullableFilter<"dStockPropertyPivot"> | string | null
  ShortUSER?: Prisma.StringNullableFilter<"dStockPropertyPivot"> | string | null
  ShortPORT?: Prisma.StringNullableFilter<"dStockPropertyPivot"> | string | null
  ShortALLERGY?: Prisma.StringNullableFilter<"dStockPropertyPivot"> | string | null
  BarcodeGEAR?: Prisma.StringNullableFilter<"dStockPropertyPivot"> | string | null
  BarcodeGRADE?: Prisma.StringNullableFilter<"dStockPropertyPivot"> | string | null
  BarcodeCONDITION?: Prisma.StringNullableFilter<"dStockPropertyPivot"> | string | null
  BarcodePACKAGE?: Prisma.StringNullableFilter<"dStockPropertyPivot"> | string | null
  BarcodeBOAT?: Prisma.StringNullableFilter<"dStockPropertyPivot"> | string | null
  BarcodeUSER?: Prisma.StringNullableFilter<"dStockPropertyPivot"> | string | null
  BarcodePORT?: Prisma.StringNullableFilter<"dStockPropertyPivot"> | string | null
  BarcodeALLERGY?: Prisma.StringNullableFilter<"dStockPropertyPivot"> | string | null
}, "IdentStock" | "Serial">

export type dStockPropertyPivotOrderByWithAggregationInput = {
  Identifier?: Prisma.SortOrder
  Status?: Prisma.SortOrder
  Creation?: Prisma.SortOrder
  CreationID?: Prisma.SortOrder
  Maintenance?: Prisma.SortOrder
  MaintenanceID?: Prisma.SortOrder
  IdentStock?: Prisma.SortOrder
  Serial?: Prisma.SortOrder
  UpdateFlag?: Prisma.SortOrder
  IdentStockPropertyGEAR?: Prisma.SortOrder
  IdentStockPropertyGRADE?: Prisma.SortOrder
  IdentStockPropertyCONDITION?: Prisma.SortOrder
  IdentStockPropertyPACKAGE?: Prisma.SortOrder
  IdentStockPropertyBOAT?: Prisma.SortOrder
  IdentStockPropertyUSER?: Prisma.SortOrder
  IdentStockPropertyPORT?: Prisma.SortOrder
  IdentStockPropertyALLERGY?: Prisma.SortOrder
  IdentPropertyGEAR?: Prisma.SortOrder
  IdentPropertyGRADE?: Prisma.SortOrder
  IdentPropertyCONDITION?: Prisma.SortOrder
  IdentPropertyPACKAGE?: Prisma.SortOrder
  IdentPropertyBOAT?: Prisma.SortOrder
  IdentPropertyUSER?: Prisma.SortOrder
  IdentPropertyPORT?: Prisma.SortOrder
  IdentPropertyALLERGY?: Prisma.SortOrder
  NameGEAR?: Prisma.SortOrderInput | Prisma.SortOrder
  NameGRADE?: Prisma.SortOrderInput | Prisma.SortOrder
  NameCONDITION?: Prisma.SortOrderInput | Prisma.SortOrder
  NamePACKAGE?: Prisma.SortOrderInput | Prisma.SortOrder
  NameBOAT?: Prisma.SortOrderInput | Prisma.SortOrder
  NameUSER?: Prisma.SortOrderInput | Prisma.SortOrder
  NamePORT?: Prisma.SortOrderInput | Prisma.SortOrder
  NameALLERGY?: Prisma.SortOrderInput | Prisma.SortOrder
  ShortGEAR?: Prisma.SortOrderInput | Prisma.SortOrder
  ShortGRADE?: Prisma.SortOrderInput | Prisma.SortOrder
  ShortCONDITION?: Prisma.SortOrderInput | Prisma.SortOrder
  ShortPACKAGE?: Prisma.SortOrderInput | Prisma.SortOrder
  ShortBOAT?: Prisma.SortOrderInput | Prisma.SortOrder
  ShortUSER?: Prisma.SortOrderInput | Prisma.SortOrder
  ShortPORT?: Prisma.SortOrderInput | Prisma.SortOrder
  ShortALLERGY?: Prisma.SortOrderInput | Prisma.SortOrder
  BarcodeGEAR?: Prisma.SortOrderInput | Prisma.SortOrder
  BarcodeGRADE?: Prisma.SortOrderInput | Prisma.SortOrder
  BarcodeCONDITION?: Prisma.SortOrderInput | Prisma.SortOrder
  BarcodePACKAGE?: Prisma.SortOrderInput | Prisma.SortOrder
  BarcodeBOAT?: Prisma.SortOrderInput | Prisma.SortOrder
  BarcodeUSER?: Prisma.SortOrderInput | Prisma.SortOrder
  BarcodePORT?: Prisma.SortOrderInput | Prisma.SortOrder
  BarcodeALLERGY?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.dStockPropertyPivotCountOrderByAggregateInput
  _avg?: Prisma.dStockPropertyPivotAvgOrderByAggregateInput
  _max?: Prisma.dStockPropertyPivotMaxOrderByAggregateInput
  _min?: Prisma.dStockPropertyPivotMinOrderByAggregateInput
  _sum?: Prisma.dStockPropertyPivotSumOrderByAggregateInput
}

export type dStockPropertyPivotScalarWhereWithAggregatesInput = {
  AND?: Prisma.dStockPropertyPivotScalarWhereWithAggregatesInput | Prisma.dStockPropertyPivotScalarWhereWithAggregatesInput[]
  OR?: Prisma.dStockPropertyPivotScalarWhereWithAggregatesInput[]
  NOT?: Prisma.dStockPropertyPivotScalarWhereWithAggregatesInput | Prisma.dStockPropertyPivotScalarWhereWithAggregatesInput[]
  Identifier?: Prisma.IntWithAggregatesFilter<"dStockPropertyPivot"> | number
  Status?: Prisma.StringWithAggregatesFilter<"dStockPropertyPivot"> | string
  Creation?: Prisma.DateTimeWithAggregatesFilter<"dStockPropertyPivot"> | Date | string
  CreationID?: Prisma.IntWithAggregatesFilter<"dStockPropertyPivot"> | number
  Maintenance?: Prisma.DateTimeWithAggregatesFilter<"dStockPropertyPivot"> | Date | string
  MaintenanceID?: Prisma.IntWithAggregatesFilter<"dStockPropertyPivot"> | number
  IdentStock?: Prisma.IntWithAggregatesFilter<"dStockPropertyPivot"> | number
  Serial?: Prisma.StringWithAggregatesFilter<"dStockPropertyPivot"> | string
  UpdateFlag?: Prisma.BoolWithAggregatesFilter<"dStockPropertyPivot"> | boolean
  IdentStockPropertyGEAR?: Prisma.IntWithAggregatesFilter<"dStockPropertyPivot"> | number
  IdentStockPropertyGRADE?: Prisma.IntWithAggregatesFilter<"dStockPropertyPivot"> | number
  IdentStockPropertyCONDITION?: Prisma.IntWithAggregatesFilter<"dStockPropertyPivot"> | number
  IdentStockPropertyPACKAGE?: Prisma.IntWithAggregatesFilter<"dStockPropertyPivot"> | number
  IdentStockPropertyBOAT?: Prisma.IntWithAggregatesFilter<"dStockPropertyPivot"> | number
  IdentStockPropertyUSER?: Prisma.IntWithAggregatesFilter<"dStockPropertyPivot"> | number
  IdentStockPropertyPORT?: Prisma.IntWithAggregatesFilter<"dStockPropertyPivot"> | number
  IdentStockPropertyALLERGY?: Prisma.IntWithAggregatesFilter<"dStockPropertyPivot"> | number
  IdentPropertyGEAR?: Prisma.IntWithAggregatesFilter<"dStockPropertyPivot"> | number
  IdentPropertyGRADE?: Prisma.IntWithAggregatesFilter<"dStockPropertyPivot"> | number
  IdentPropertyCONDITION?: Prisma.IntWithAggregatesFilter<"dStockPropertyPivot"> | number
  IdentPropertyPACKAGE?: Prisma.IntWithAggregatesFilter<"dStockPropertyPivot"> | number
  IdentPropertyBOAT?: Prisma.IntWithAggregatesFilter<"dStockPropertyPivot"> | number
  IdentPropertyUSER?: Prisma.IntWithAggregatesFilter<"dStockPropertyPivot"> | number
  IdentPropertyPORT?: Prisma.IntWithAggregatesFilter<"dStockPropertyPivot"> | number
  IdentPropertyALLERGY?: Prisma.IntWithAggregatesFilter<"dStockPropertyPivot"> | number
  NameGEAR?: Prisma.StringNullableWithAggregatesFilter<"dStockPropertyPivot"> | string | null
  NameGRADE?: Prisma.StringNullableWithAggregatesFilter<"dStockPropertyPivot"> | string | null
  NameCONDITION?: Prisma.StringNullableWithAggregatesFilter<"dStockPropertyPivot"> | string | null
  NamePACKAGE?: Prisma.StringNullableWithAggregatesFilter<"dStockPropertyPivot"> | string | null
  NameBOAT?: Prisma.StringNullableWithAggregatesFilter<"dStockPropertyPivot"> | string | null
  NameUSER?: Prisma.StringNullableWithAggregatesFilter<"dStockPropertyPivot"> | string | null
  NamePORT?: Prisma.StringNullableWithAggregatesFilter<"dStockPropertyPivot"> | string | null
  NameALLERGY?: Prisma.StringNullableWithAggregatesFilter<"dStockPropertyPivot"> | string | null
  ShortGEAR?: Prisma.StringNullableWithAggregatesFilter<"dStockPropertyPivot"> | string | null
  ShortGRADE?: Prisma.StringNullableWithAggregatesFilter<"dStockPropertyPivot"> | string | null
  ShortCONDITION?: Prisma.StringNullableWithAggregatesFilter<"dStockPropertyPivot"> | string | null
  ShortPACKAGE?: Prisma.StringNullableWithAggregatesFilter<"dStockPropertyPivot"> | string | null
  ShortBOAT?: Prisma.StringNullableWithAggregatesFilter<"dStockPropertyPivot"> | string | null
  ShortUSER?: Prisma.StringNullableWithAggregatesFilter<"dStockPropertyPivot"> | string | null
  ShortPORT?: Prisma.StringNullableWithAggregatesFilter<"dStockPropertyPivot"> | string | null
  ShortALLERGY?: Prisma.StringNullableWithAggregatesFilter<"dStockPropertyPivot"> | string | null
  BarcodeGEAR?: Prisma.StringNullableWithAggregatesFilter<"dStockPropertyPivot"> | string | null
  BarcodeGRADE?: Prisma.StringNullableWithAggregatesFilter<"dStockPropertyPivot"> | string | null
  BarcodeCONDITION?: Prisma.StringNullableWithAggregatesFilter<"dStockPropertyPivot"> | string | null
  BarcodePACKAGE?: Prisma.StringNullableWithAggregatesFilter<"dStockPropertyPivot"> | string | null
  BarcodeBOAT?: Prisma.StringNullableWithAggregatesFilter<"dStockPropertyPivot"> | string | null
  BarcodeUSER?: Prisma.StringNullableWithAggregatesFilter<"dStockPropertyPivot"> | string | null
  BarcodePORT?: Prisma.StringNullableWithAggregatesFilter<"dStockPropertyPivot"> | string | null
  BarcodeALLERGY?: Prisma.StringNullableWithAggregatesFilter<"dStockPropertyPivot"> | string | null
}

export type dStockPropertyPivotCreateInput = {
  Identifier?: number
  Status?: string
  Creation?: Date | string
  CreationID?: number
  Maintenance?: Date | string
  MaintenanceID?: number
  IdentStock?: number
  Serial?: string
  UpdateFlag?: boolean
  IdentStockPropertyGEAR?: number
  IdentStockPropertyGRADE?: number
  IdentStockPropertyCONDITION?: number
  IdentStockPropertyPACKAGE?: number
  IdentStockPropertyBOAT?: number
  IdentStockPropertyUSER?: number
  IdentStockPropertyPORT?: number
  IdentStockPropertyALLERGY?: number
  IdentPropertyGEAR?: number
  IdentPropertyGRADE?: number
  IdentPropertyCONDITION?: number
  IdentPropertyPACKAGE?: number
  IdentPropertyBOAT?: number
  IdentPropertyUSER?: number
  IdentPropertyPORT?: number
  IdentPropertyALLERGY?: number
  NameGEAR?: string | null
  NameGRADE?: string | null
  NameCONDITION?: string | null
  NamePACKAGE?: string | null
  NameBOAT?: string | null
  NameUSER?: string | null
  NamePORT?: string | null
  NameALLERGY?: string | null
  ShortGEAR?: string | null
  ShortGRADE?: string | null
  ShortCONDITION?: string | null
  ShortPACKAGE?: string | null
  ShortBOAT?: string | null
  ShortUSER?: string | null
  ShortPORT?: string | null
  ShortALLERGY?: string | null
  BarcodeGEAR?: string | null
  BarcodeGRADE?: string | null
  BarcodeCONDITION?: string | null
  BarcodePACKAGE?: string | null
  BarcodeBOAT?: string | null
  BarcodeUSER?: string | null
  BarcodePORT?: string | null
  BarcodeALLERGY?: string | null
}

export type dStockPropertyPivotUncheckedCreateInput = {
  Identifier?: number
  Status?: string
  Creation?: Date | string
  CreationID?: number
  Maintenance?: Date | string
  MaintenanceID?: number
  IdentStock?: number
  Serial?: string
  UpdateFlag?: boolean
  IdentStockPropertyGEAR?: number
  IdentStockPropertyGRADE?: number
  IdentStockPropertyCONDITION?: number
  IdentStockPropertyPACKAGE?: number
  IdentStockPropertyBOAT?: number
  IdentStockPropertyUSER?: number
  IdentStockPropertyPORT?: number
  IdentStockPropertyALLERGY?: number
  IdentPropertyGEAR?: number
  IdentPropertyGRADE?: number
  IdentPropertyCONDITION?: number
  IdentPropertyPACKAGE?: number
  IdentPropertyBOAT?: number
  IdentPropertyUSER?: number
  IdentPropertyPORT?: number
  IdentPropertyALLERGY?: number
  NameGEAR?: string | null
  NameGRADE?: string | null
  NameCONDITION?: string | null
  NamePACKAGE?: string | null
  NameBOAT?: string | null
  NameUSER?: string | null
  NamePORT?: string | null
  NameALLERGY?: string | null
  ShortGEAR?: string | null
  ShortGRADE?: string | null
  ShortCONDITION?: string | null
  ShortPACKAGE?: string | null
  ShortBOAT?: string | null
  ShortUSER?: string | null
  ShortPORT?: string | null
  ShortALLERGY?: string | null
  BarcodeGEAR?: string | null
  BarcodeGRADE?: string | null
  BarcodeCONDITION?: string | null
  BarcodePACKAGE?: string | null
  BarcodeBOAT?: string | null
  BarcodeUSER?: string | null
  BarcodePORT?: string | null
  BarcodeALLERGY?: string | null
}

export type dStockPropertyPivotUpdateInput = {
  Identifier?: Prisma.IntFieldUpdateOperationsInput | number
  Status?: Prisma.StringFieldUpdateOperationsInput | string
  Creation?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  CreationID?: Prisma.IntFieldUpdateOperationsInput | number
  Maintenance?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  MaintenanceID?: Prisma.IntFieldUpdateOperationsInput | number
  IdentStock?: Prisma.IntFieldUpdateOperationsInput | number
  Serial?: Prisma.StringFieldUpdateOperationsInput | string
  UpdateFlag?: Prisma.BoolFieldUpdateOperationsInput | boolean
  IdentStockPropertyGEAR?: Prisma.IntFieldUpdateOperationsInput | number
  IdentStockPropertyGRADE?: Prisma.IntFieldUpdateOperationsInput | number
  IdentStockPropertyCONDITION?: Prisma.IntFieldUpdateOperationsInput | number
  IdentStockPropertyPACKAGE?: Prisma.IntFieldUpdateOperationsInput | number
  IdentStockPropertyBOAT?: Prisma.IntFieldUpdateOperationsInput | number
  IdentStockPropertyUSER?: Prisma.IntFieldUpdateOperationsInput | number
  IdentStockPropertyPORT?: Prisma.IntFieldUpdateOperationsInput | number
  IdentStockPropertyALLERGY?: Prisma.IntFieldUpdateOperationsInput | number
  IdentPropertyGEAR?: Prisma.IntFieldUpdateOperationsInput | number
  IdentPropertyGRADE?: Prisma.IntFieldUpdateOperationsInput | number
  IdentPropertyCONDITION?: Prisma.IntFieldUpdateOperationsInput | number
  IdentPropertyPACKAGE?: Prisma.IntFieldUpdateOperationsInput | number
  IdentPropertyBOAT?: Prisma.IntFieldUpdateOperationsInput | number
  IdentPropertyUSER?: Prisma.IntFieldUpdateOperationsInput | number
  IdentPropertyPORT?: Prisma.IntFieldUpdateOperationsInput | number
  IdentPropertyALLERGY?: Prisma.IntFieldUpdateOperationsInput | number
  NameGEAR?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  NameGRADE?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  NameCONDITION?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  NamePACKAGE?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  NameBOAT?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  NameUSER?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  NamePORT?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  NameALLERGY?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ShortGEAR?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ShortGRADE?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ShortCONDITION?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ShortPACKAGE?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ShortBOAT?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ShortUSER?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ShortPORT?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ShortALLERGY?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  BarcodeGEAR?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  BarcodeGRADE?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  BarcodeCONDITION?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  BarcodePACKAGE?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  BarcodeBOAT?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  BarcodeUSER?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  BarcodePORT?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  BarcodeALLERGY?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type dStockPropertyPivotUncheckedUpdateInput = {
  Identifier?: Prisma.IntFieldUpdateOperationsInput | number
  Status?: Prisma.StringFieldUpdateOperationsInput | string
  Creation?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  CreationID?: Prisma.IntFieldUpdateOperationsInput | number
  Maintenance?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  MaintenanceID?: Prisma.IntFieldUpdateOperationsInput | number
  IdentStock?: Prisma.IntFieldUpdateOperationsInput | number
  Serial?: Prisma.StringFieldUpdateOperationsInput | string
  UpdateFlag?: Prisma.BoolFieldUpdateOperationsInput | boolean
  IdentStockPropertyGEAR?: Prisma.IntFieldUpdateOperationsInput | number
  IdentStockPropertyGRADE?: Prisma.IntFieldUpdateOperationsInput | number
  IdentStockPropertyCONDITION?: Prisma.IntFieldUpdateOperationsInput | number
  IdentStockPropertyPACKAGE?: Prisma.IntFieldUpdateOperationsInput | number
  IdentStockPropertyBOAT?: Prisma.IntFieldUpdateOperationsInput | number
  IdentStockPropertyUSER?: Prisma.IntFieldUpdateOperationsInput | number
  IdentStockPropertyPORT?: Prisma.IntFieldUpdateOperationsInput | number
  IdentStockPropertyALLERGY?: Prisma.IntFieldUpdateOperationsInput | number
  IdentPropertyGEAR?: Prisma.IntFieldUpdateOperationsInput | number
  IdentPropertyGRADE?: Prisma.IntFieldUpdateOperationsInput | number
  IdentPropertyCONDITION?: Prisma.IntFieldUpdateOperationsInput | number
  IdentPropertyPACKAGE?: Prisma.IntFieldUpdateOperationsInput | number
  IdentPropertyBOAT?: Prisma.IntFieldUpdateOperationsInput | number
  IdentPropertyUSER?: Prisma.IntFieldUpdateOperationsInput | number
  IdentPropertyPORT?: Prisma.IntFieldUpdateOperationsInput | number
  IdentPropertyALLERGY?: Prisma.IntFieldUpdateOperationsInput | number
  NameGEAR?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  NameGRADE?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  NameCONDITION?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  NamePACKAGE?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  NameBOAT?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  NameUSER?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  NamePORT?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  NameALLERGY?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ShortGEAR?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ShortGRADE?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ShortCONDITION?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ShortPACKAGE?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ShortBOAT?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ShortUSER?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ShortPORT?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ShortALLERGY?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  BarcodeGEAR?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  BarcodeGRADE?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  BarcodeCONDITION?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  BarcodePACKAGE?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  BarcodeBOAT?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  BarcodeUSER?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  BarcodePORT?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  BarcodeALLERGY?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type dStockPropertyPivotCreateManyInput = {
  Status?: string
  Creation?: Date | string
  CreationID?: number
  Maintenance?: Date | string
  MaintenanceID?: number
  IdentStock?: number
  Serial?: string
  UpdateFlag?: boolean
  IdentStockPropertyGEAR?: number
  IdentStockPropertyGRADE?: number
  IdentStockPropertyCONDITION?: number
  IdentStockPropertyPACKAGE?: number
  IdentStockPropertyBOAT?: number
  IdentStockPropertyUSER?: number
  IdentStockPropertyPORT?: number
  IdentStockPropertyALLERGY?: number
  IdentPropertyGEAR?: number
  IdentPropertyGRADE?: number
  IdentPropertyCONDITION?: number
  IdentPropertyPACKAGE?: number
  IdentPropertyBOAT?: number
  IdentPropertyUSER?: number
  IdentPropertyPORT?: number
  IdentPropertyALLERGY?: number
  NameGEAR?: string | null
  NameGRADE?: string | null
  NameCONDITION?: string | null
  NamePACKAGE?: string | null
  NameBOAT?: string | null
  NameUSER?: string | null
  NamePORT?: string | null
  NameALLERGY?: string | null
  ShortGEAR?: string | null
  ShortGRADE?: string | null
  ShortCONDITION?: string | null
  ShortPACKAGE?: string | null
  ShortBOAT?: string | null
  ShortUSER?: string | null
  ShortPORT?: string | null
  ShortALLERGY?: string | null
  BarcodeGEAR?: string | null
  BarcodeGRADE?: string | null
  BarcodeCONDITION?: string | null
  BarcodePACKAGE?: string | null
  BarcodeBOAT?: string | null
  BarcodeUSER?: string | null
  BarcodePORT?: string | null
  BarcodeALLERGY?: string | null
}

export type dStockPropertyPivotUpdateManyMutationInput = {
  Identifier?: Prisma.IntFieldUpdateOperationsInput | number
  Status?: Prisma.StringFieldUpdateOperationsInput | string
  Creation?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  CreationID?: Prisma.IntFieldUpdateOperationsInput | number
  Maintenance?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  MaintenanceID?: Prisma.IntFieldUpdateOperationsInput | number
  IdentStock?: Prisma.IntFieldUpdateOperationsInput | number
  Serial?: Prisma.StringFieldUpdateOperationsInput | string
  UpdateFlag?: Prisma.BoolFieldUpdateOperationsInput | boolean
  IdentStockPropertyGEAR?: Prisma.IntFieldUpdateOperationsInput | number
  IdentStockPropertyGRADE?: Prisma.IntFieldUpdateOperationsInput | number
  IdentStockPropertyCONDITION?: Prisma.IntFieldUpdateOperationsInput | number
  IdentStockPropertyPACKAGE?: Prisma.IntFieldUpdateOperationsInput | number
  IdentStockPropertyBOAT?: Prisma.IntFieldUpdateOperationsInput | number
  IdentStockPropertyUSER?: Prisma.IntFieldUpdateOperationsInput | number
  IdentStockPropertyPORT?: Prisma.IntFieldUpdateOperationsInput | number
  IdentStockPropertyALLERGY?: Prisma.IntFieldUpdateOperationsInput | number
  IdentPropertyGEAR?: Prisma.IntFieldUpdateOperationsInput | number
  IdentPropertyGRADE?: Prisma.IntFieldUpdateOperationsInput | number
  IdentPropertyCONDITION?: Prisma.IntFieldUpdateOperationsInput | number
  IdentPropertyPACKAGE?: Prisma.IntFieldUpdateOperationsInput | number
  IdentPropertyBOAT?: Prisma.IntFieldUpdateOperationsInput | number
  IdentPropertyUSER?: Prisma.IntFieldUpdateOperationsInput | number
  IdentPropertyPORT?: Prisma.IntFieldUpdateOperationsInput | number
  IdentPropertyALLERGY?: Prisma.IntFieldUpdateOperationsInput | number
  NameGEAR?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  NameGRADE?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  NameCONDITION?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  NamePACKAGE?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  NameBOAT?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  NameUSER?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  NamePORT?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  NameALLERGY?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ShortGEAR?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ShortGRADE?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ShortCONDITION?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ShortPACKAGE?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ShortBOAT?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ShortUSER?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ShortPORT?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ShortALLERGY?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  BarcodeGEAR?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  BarcodeGRADE?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  BarcodeCONDITION?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  BarcodePACKAGE?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  BarcodeBOAT?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  BarcodeUSER?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  BarcodePORT?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  BarcodeALLERGY?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type dStockPropertyPivotUncheckedUpdateManyInput = {
  Identifier?: Prisma.IntFieldUpdateOperationsInput | number
  Status?: Prisma.StringFieldUpdateOperationsInput | string
  Creation?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  CreationID?: Prisma.IntFieldUpdateOperationsInput | number
  Maintenance?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  MaintenanceID?: Prisma.IntFieldUpdateOperationsInput | number
  IdentStock?: Prisma.IntFieldUpdateOperationsInput | number
  Serial?: Prisma.StringFieldUpdateOperationsInput | string
  UpdateFlag?: Prisma.BoolFieldUpdateOperationsInput | boolean
  IdentStockPropertyGEAR?: Prisma.IntFieldUpdateOperationsInput | number
  IdentStockPropertyGRADE?: Prisma.IntFieldUpdateOperationsInput | number
  IdentStockPropertyCONDITION?: Prisma.IntFieldUpdateOperationsInput | number
  IdentStockPropertyPACKAGE?: Prisma.IntFieldUpdateOperationsInput | number
  IdentStockPropertyBOAT?: Prisma.IntFieldUpdateOperationsInput | number
  IdentStockPropertyUSER?: Prisma.IntFieldUpdateOperationsInput | number
  IdentStockPropertyPORT?: Prisma.IntFieldUpdateOperationsInput | number
  IdentStockPropertyALLERGY?: Prisma.IntFieldUpdateOperationsInput | number
  IdentPropertyGEAR?: Prisma.IntFieldUpdateOperationsInput | number
  IdentPropertyGRADE?: Prisma.IntFieldUpdateOperationsInput | number
  IdentPropertyCONDITION?: Prisma.IntFieldUpdateOperationsInput | number
  IdentPropertyPACKAGE?: Prisma.IntFieldUpdateOperationsInput | number
  IdentPropertyBOAT?: Prisma.IntFieldUpdateOperationsInput | number
  IdentPropertyUSER?: Prisma.IntFieldUpdateOperationsInput | number
  IdentPropertyPORT?: Prisma.IntFieldUpdateOperationsInput | number
  IdentPropertyALLERGY?: Prisma.IntFieldUpdateOperationsInput | number
  NameGEAR?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  NameGRADE?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  NameCONDITION?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  NamePACKAGE?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  NameBOAT?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  NameUSER?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  NamePORT?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  NameALLERGY?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ShortGEAR?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ShortGRADE?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ShortCONDITION?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ShortPACKAGE?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ShortBOAT?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ShortUSER?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ShortPORT?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ShortALLERGY?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  BarcodeGEAR?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  BarcodeGRADE?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  BarcodeCONDITION?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  BarcodePACKAGE?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  BarcodeBOAT?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  BarcodeUSER?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  BarcodePORT?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  BarcodeALLERGY?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type dStockPropertyPivotCountOrderByAggregateInput = {
  Identifier?: Prisma.SortOrder
  Status?: Prisma.SortOrder
  Creation?: Prisma.SortOrder
  CreationID?: Prisma.SortOrder
  Maintenance?: Prisma.SortOrder
  MaintenanceID?: Prisma.SortOrder
  IdentStock?: Prisma.SortOrder
  Serial?: Prisma.SortOrder
  UpdateFlag?: Prisma.SortOrder
  IdentStockPropertyGEAR?: Prisma.SortOrder
  IdentStockPropertyGRADE?: Prisma.SortOrder
  IdentStockPropertyCONDITION?: Prisma.SortOrder
  IdentStockPropertyPACKAGE?: Prisma.SortOrder
  IdentStockPropertyBOAT?: Prisma.SortOrder
  IdentStockPropertyUSER?: Prisma.SortOrder
  IdentStockPropertyPORT?: Prisma.SortOrder
  IdentStockPropertyALLERGY?: Prisma.SortOrder
  IdentPropertyGEAR?: Prisma.SortOrder
  IdentPropertyGRADE?: Prisma.SortOrder
  IdentPropertyCONDITION?: Prisma.SortOrder
  IdentPropertyPACKAGE?: Prisma.SortOrder
  IdentPropertyBOAT?: Prisma.SortOrder
  IdentPropertyUSER?: Prisma.SortOrder
  IdentPropertyPORT?: Prisma.SortOrder
  IdentPropertyALLERGY?: Prisma.SortOrder
  NameGEAR?: Prisma.SortOrder
  NameGRADE?: Prisma.SortOrder
  NameCONDITION?: Prisma.SortOrder
  NamePACKAGE?: Prisma.SortOrder
  NameBOAT?: Prisma.SortOrder
  NameUSER?: Prisma.SortOrder
  NamePORT?: Prisma.SortOrder
  NameALLERGY?: Prisma.SortOrder
  ShortGEAR?: Prisma.SortOrder
  ShortGRADE?: Prisma.SortOrder
  ShortCONDITION?: Prisma.SortOrder
  ShortPACKAGE?: Prisma.SortOrder
  ShortBOAT?: Prisma.SortOrder
  ShortUSER?: Prisma.SortOrder
  ShortPORT?: Prisma.SortOrder
  ShortALLERGY?: Prisma.SortOrder
  BarcodeGEAR?: Prisma.SortOrder
  BarcodeGRADE?: Prisma.SortOrder
  BarcodeCONDITION?: Prisma.SortOrder
  BarcodePACKAGE?: Prisma.SortOrder
  BarcodeBOAT?: Prisma.SortOrder
  BarcodeUSER?: Prisma.SortOrder
  BarcodePORT?: Prisma.SortOrder
  BarcodeALLERGY?: Prisma.SortOrder
}

export type dStockPropertyPivotAvgOrderByAggregateInput = {
  Identifier?: Prisma.SortOrder
  CreationID?: Prisma.SortOrder
  MaintenanceID?: Prisma.SortOrder
  IdentStock?: Prisma.SortOrder
  IdentStockPropertyGEAR?: Prisma.SortOrder
  IdentStockPropertyGRADE?: Prisma.SortOrder
  IdentStockPropertyCONDITION?: Prisma.SortOrder
  IdentStockPropertyPACKAGE?: Prisma.SortOrder
  IdentStockPropertyBOAT?: Prisma.SortOrder
  IdentStockPropertyUSER?: Prisma.SortOrder
  IdentStockPropertyPORT?: Prisma.SortOrder
  IdentStockPropertyALLERGY?: Prisma.SortOrder
  IdentPropertyGEAR?: Prisma.SortOrder
  IdentPropertyGRADE?: Prisma.SortOrder
  IdentPropertyCONDITION?: Prisma.SortOrder
  IdentPropertyPACKAGE?: Prisma.SortOrder
  IdentPropertyBOAT?: Prisma.SortOrder
  IdentPropertyUSER?: Prisma.SortOrder
  IdentPropertyPORT?: Prisma.SortOrder
  IdentPropertyALLERGY?: Prisma.SortOrder
}

export type dStockPropertyPivotMaxOrderByAggregateInput = {
  Identifier?: Prisma.SortOrder
  Status?: Prisma.SortOrder
  Creation?: Prisma.SortOrder
  CreationID?: Prisma.SortOrder
  Maintenance?: Prisma.SortOrder
  MaintenanceID?: Prisma.SortOrder
  IdentStock?: Prisma.SortOrder
  Serial?: Prisma.SortOrder
  UpdateFlag?: Prisma.SortOrder
  IdentStockPropertyGEAR?: Prisma.SortOrder
  IdentStockPropertyGRADE?: Prisma.SortOrder
  IdentStockPropertyCONDITION?: Prisma.SortOrder
  IdentStockPropertyPACKAGE?: Prisma.SortOrder
  IdentStockPropertyBOAT?: Prisma.SortOrder
  IdentStockPropertyUSER?: Prisma.SortOrder
  IdentStockPropertyPORT?: Prisma.SortOrder
  IdentStockPropertyALLERGY?: Prisma.SortOrder
  IdentPropertyGEAR?: Prisma.SortOrder
  IdentPropertyGRADE?: Prisma.SortOrder
  IdentPropertyCONDITION?: Prisma.SortOrder
  IdentPropertyPACKAGE?: Prisma.SortOrder
  IdentPropertyBOAT?: Prisma.SortOrder
  IdentPropertyUSER?: Prisma.SortOrder
  IdentPropertyPORT?: Prisma.SortOrder
  IdentPropertyALLERGY?: Prisma.SortOrder
  NameGEAR?: Prisma.SortOrder
  NameGRADE?: Prisma.SortOrder
  NameCONDITION?: Prisma.SortOrder
  NamePACKAGE?: Prisma.SortOrder
  NameBOAT?: Prisma.SortOrder
  NameUSER?: Prisma.SortOrder
  NamePORT?: Prisma.SortOrder
  NameALLERGY?: Prisma.SortOrder
  ShortGEAR?: Prisma.SortOrder
  ShortGRADE?: Prisma.SortOrder
  ShortCONDITION?: Prisma.SortOrder
  ShortPACKAGE?: Prisma.SortOrder
  ShortBOAT?: Prisma.SortOrder
  ShortUSER?: Prisma.SortOrder
  ShortPORT?: Prisma.SortOrder
  ShortALLERGY?: Prisma.SortOrder
  BarcodeGEAR?: Prisma.SortOrder
  BarcodeGRADE?: Prisma.SortOrder
  BarcodeCONDITION?: Prisma.SortOrder
  BarcodePACKAGE?: Prisma.SortOrder
  BarcodeBOAT?: Prisma.SortOrder
  BarcodeUSER?: Prisma.SortOrder
  BarcodePORT?: Prisma.SortOrder
  BarcodeALLERGY?: Prisma.SortOrder
}

export type dStockPropertyPivotMinOrderByAggregateInput = {
  Identifier?: Prisma.SortOrder
  Status?: Prisma.SortOrder
  Creation?: Prisma.SortOrder
  CreationID?: Prisma.SortOrder
  Maintenance?: Prisma.SortOrder
  MaintenanceID?: Prisma.SortOrder
  IdentStock?: Prisma.SortOrder
  Serial?: Prisma.SortOrder
  UpdateFlag?: Prisma.SortOrder
  IdentStockPropertyGEAR?: Prisma.SortOrder
  IdentStockPropertyGRADE?: Prisma.SortOrder
  IdentStockPropertyCONDITION?: Prisma.SortOrder
  IdentStockPropertyPACKAGE?: Prisma.SortOrder
  IdentStockPropertyBOAT?: Prisma.SortOrder
  IdentStockPropertyUSER?: Prisma.SortOrder
  IdentStockPropertyPORT?: Prisma.SortOrder
  IdentStockPropertyALLERGY?: Prisma.SortOrder
  IdentPropertyGEAR?: Prisma.SortOrder
  IdentPropertyGRADE?: Prisma.SortOrder
  IdentPropertyCONDITION?: Prisma.SortOrder
  IdentPropertyPACKAGE?: Prisma.SortOrder
  IdentPropertyBOAT?: Prisma.SortOrder
  IdentPropertyUSER?: Prisma.SortOrder
  IdentPropertyPORT?: Prisma.SortOrder
  IdentPropertyALLERGY?: Prisma.SortOrder
  NameGEAR?: Prisma.SortOrder
  NameGRADE?: Prisma.SortOrder
  NameCONDITION?: Prisma.SortOrder
  NamePACKAGE?: Prisma.SortOrder
  NameBOAT?: Prisma.SortOrder
  NameUSER?: Prisma.SortOrder
  NamePORT?: Prisma.SortOrder
  NameALLERGY?: Prisma.SortOrder
  ShortGEAR?: Prisma.SortOrder
  ShortGRADE?: Prisma.SortOrder
  ShortCONDITION?: Prisma.SortOrder
  ShortPACKAGE?: Prisma.SortOrder
  ShortBOAT?: Prisma.SortOrder
  ShortUSER?: Prisma.SortOrder
  ShortPORT?: Prisma.SortOrder
  ShortALLERGY?: Prisma.SortOrder
  BarcodeGEAR?: Prisma.SortOrder
  BarcodeGRADE?: Prisma.SortOrder
  BarcodeCONDITION?: Prisma.SortOrder
  BarcodePACKAGE?: Prisma.SortOrder
  BarcodeBOAT?: Prisma.SortOrder
  BarcodeUSER?: Prisma.SortOrder
  BarcodePORT?: Prisma.SortOrder
  BarcodeALLERGY?: Prisma.SortOrder
}

export type dStockPropertyPivotSumOrderByAggregateInput = {
  Identifier?: Prisma.SortOrder
  CreationID?: Prisma.SortOrder
  MaintenanceID?: Prisma.SortOrder
  IdentStock?: Prisma.SortOrder
  IdentStockPropertyGEAR?: Prisma.SortOrder
  IdentStockPropertyGRADE?: Prisma.SortOrder
  IdentStockPropertyCONDITION?: Prisma.SortOrder
  IdentStockPropertyPACKAGE?: Prisma.SortOrder
  IdentStockPropertyBOAT?: Prisma.SortOrder
  IdentStockPropertyUSER?: Prisma.SortOrder
  IdentStockPropertyPORT?: Prisma.SortOrder
  IdentStockPropertyALLERGY?: Prisma.SortOrder
  IdentPropertyGEAR?: Prisma.SortOrder
  IdentPropertyGRADE?: Prisma.SortOrder
  IdentPropertyCONDITION?: Prisma.SortOrder
  IdentPropertyPACKAGE?: Prisma.SortOrder
  IdentPropertyBOAT?: Prisma.SortOrder
  IdentPropertyUSER?: Prisma.SortOrder
  IdentPropertyPORT?: Prisma.SortOrder
  IdentPropertyALLERGY?: Prisma.SortOrder
}



export type dStockPropertyPivotSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  Identifier?: boolean
  Status?: boolean
  Creation?: boolean
  CreationID?: boolean
  Maintenance?: boolean
  MaintenanceID?: boolean
  IdentStock?: boolean
  Serial?: boolean
  UpdateFlag?: boolean
  IdentStockPropertyGEAR?: boolean
  IdentStockPropertyGRADE?: boolean
  IdentStockPropertyCONDITION?: boolean
  IdentStockPropertyPACKAGE?: boolean
  IdentStockPropertyBOAT?: boolean
  IdentStockPropertyUSER?: boolean
  IdentStockPropertyPORT?: boolean
  IdentStockPropertyALLERGY?: boolean
  IdentPropertyGEAR?: boolean
  IdentPropertyGRADE?: boolean
  IdentPropertyCONDITION?: boolean
  IdentPropertyPACKAGE?: boolean
  IdentPropertyBOAT?: boolean
  IdentPropertyUSER?: boolean
  IdentPropertyPORT?: boolean
  IdentPropertyALLERGY?: boolean
  NameGEAR?: boolean
  NameGRADE?: boolean
  NameCONDITION?: boolean
  NamePACKAGE?: boolean
  NameBOAT?: boolean
  NameUSER?: boolean
  NamePORT?: boolean
  NameALLERGY?: boolean
  ShortGEAR?: boolean
  ShortGRADE?: boolean
  ShortCONDITION?: boolean
  ShortPACKAGE?: boolean
  ShortBOAT?: boolean
  ShortUSER?: boolean
  ShortPORT?: boolean
  ShortALLERGY?: boolean
  BarcodeGEAR?: boolean
  BarcodeGRADE?: boolean
  BarcodeCONDITION?: boolean
  BarcodePACKAGE?: boolean
  BarcodeBOAT?: boolean
  BarcodeUSER?: boolean
  BarcodePORT?: boolean
  BarcodeALLERGY?: boolean
}, ExtArgs["result"]["dStockPropertyPivot"]>



export type dStockPropertyPivotSelectScalar = {
  Identifier?: boolean
  Status?: boolean
  Creation?: boolean
  CreationID?: boolean
  Maintenance?: boolean
  MaintenanceID?: boolean
  IdentStock?: boolean
  Serial?: boolean
  UpdateFlag?: boolean
  IdentStockPropertyGEAR?: boolean
  IdentStockPropertyGRADE?: boolean
  IdentStockPropertyCONDITION?: boolean
  IdentStockPropertyPACKAGE?: boolean
  IdentStockPropertyBOAT?: boolean
  IdentStockPropertyUSER?: boolean
  IdentStockPropertyPORT?: boolean
  IdentStockPropertyALLERGY?: boolean
  IdentPropertyGEAR?: boolean
  IdentPropertyGRADE?: boolean
  IdentPropertyCONDITION?: boolean
  IdentPropertyPACKAGE?: boolean
  IdentPropertyBOAT?: boolean
  IdentPropertyUSER?: boolean
  IdentPropertyPORT?: boolean
  IdentPropertyALLERGY?: boolean
  NameGEAR?: boolean
  NameGRADE?: boolean
  NameCONDITION?: boolean
  NamePACKAGE?: boolean
  NameBOAT?: boolean
  NameUSER?: boolean
  NamePORT?: boolean
  NameALLERGY?: boolean
  ShortGEAR?: boolean
  ShortGRADE?: boolean
  ShortCONDITION?: boolean
  ShortPACKAGE?: boolean
  ShortBOAT?: boolean
  ShortUSER?: boolean
  ShortPORT?: boolean
  ShortALLERGY?: boolean
  BarcodeGEAR?: boolean
  BarcodeGRADE?: boolean
  BarcodeCONDITION?: boolean
  BarcodePACKAGE?: boolean
  BarcodeBOAT?: boolean
  BarcodeUSER?: boolean
  BarcodePORT?: boolean
  BarcodeALLERGY?: boolean
}

export type dStockPropertyPivotOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"Identifier" | "Status" | "Creation" | "CreationID" | "Maintenance" | "MaintenanceID" | "IdentStock" | "Serial" | "UpdateFlag" | "IdentStockPropertyGEAR" | "IdentStockPropertyGRADE" | "IdentStockPropertyCONDITION" | "IdentStockPropertyPACKAGE" | "IdentStockPropertyBOAT" | "IdentStockPropertyUSER" | "IdentStockPropertyPORT" | "IdentStockPropertyALLERGY" | "IdentPropertyGEAR" | "IdentPropertyGRADE" | "IdentPropertyCONDITION" | "IdentPropertyPACKAGE" | "IdentPropertyBOAT" | "IdentPropertyUSER" | "IdentPropertyPORT" | "IdentPropertyALLERGY" | "NameGEAR" | "NameGRADE" | "NameCONDITION" | "NamePACKAGE" | "NameBOAT" | "NameUSER" | "NamePORT" | "NameALLERGY" | "ShortGEAR" | "ShortGRADE" | "ShortCONDITION" | "ShortPACKAGE" | "ShortBOAT" | "ShortUSER" | "ShortPORT" | "ShortALLERGY" | "BarcodeGEAR" | "BarcodeGRADE" | "BarcodeCONDITION" | "BarcodePACKAGE" | "BarcodeBOAT" | "BarcodeUSER" | "BarcodePORT" | "BarcodeALLERGY", ExtArgs["result"]["dStockPropertyPivot"]>

export type $dStockPropertyPivotPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "dStockPropertyPivot"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    Identifier: number
    Status: string
    Creation: Date
    CreationID: number
    Maintenance: Date
    MaintenanceID: number
    IdentStock: number
    Serial: string
    UpdateFlag: boolean
    IdentStockPropertyGEAR: number
    IdentStockPropertyGRADE: number
    IdentStockPropertyCONDITION: number
    IdentStockPropertyPACKAGE: number
    IdentStockPropertyBOAT: number
    IdentStockPropertyUSER: number
    IdentStockPropertyPORT: number
    IdentStockPropertyALLERGY: number
    IdentPropertyGEAR: number
    IdentPropertyGRADE: number
    IdentPropertyCONDITION: number
    IdentPropertyPACKAGE: number
    IdentPropertyBOAT: number
    IdentPropertyUSER: number
    IdentPropertyPORT: number
    IdentPropertyALLERGY: number
    NameGEAR: string | null
    NameGRADE: string | null
    NameCONDITION: string | null
    NamePACKAGE: string | null
    NameBOAT: string | null
    NameUSER: string | null
    NamePORT: string | null
    NameALLERGY: string | null
    ShortGEAR: string | null
    ShortGRADE: string | null
    ShortCONDITION: string | null
    ShortPACKAGE: string | null
    ShortBOAT: string | null
    ShortUSER: string | null
    ShortPORT: string | null
    ShortALLERGY: string | null
    BarcodeGEAR: string | null
    BarcodeGRADE: string | null
    BarcodeCONDITION: string | null
    BarcodePACKAGE: string | null
    BarcodeBOAT: string | null
    BarcodeUSER: string | null
    BarcodePORT: string | null
    BarcodeALLERGY: string | null
  }, ExtArgs["result"]["dStockPropertyPivot"]>
  composites: {}
}

export type dStockPropertyPivotGetPayload<S extends boolean | null | undefined | dStockPropertyPivotDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$dStockPropertyPivotPayload, S>

export type dStockPropertyPivotCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<dStockPropertyPivotFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DStockPropertyPivotCountAggregateInputType | true
  }

export interface dStockPropertyPivotDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['dStockPropertyPivot'], meta: { name: 'dStockPropertyPivot' } }
  /**
   * Find zero or one DStockPropertyPivot that matches the filter.
   * @param {dStockPropertyPivotFindUniqueArgs} args - Arguments to find a DStockPropertyPivot
   * @example
   * // Get one DStockPropertyPivot
   * const dStockPropertyPivot = await prisma.dStockPropertyPivot.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends dStockPropertyPivotFindUniqueArgs>(args: Prisma.SelectSubset<T, dStockPropertyPivotFindUniqueArgs<ExtArgs>>): Prisma.Prisma__dStockPropertyPivotClient<runtime.Types.Result.GetResult<Prisma.$dStockPropertyPivotPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one DStockPropertyPivot that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {dStockPropertyPivotFindUniqueOrThrowArgs} args - Arguments to find a DStockPropertyPivot
   * @example
   * // Get one DStockPropertyPivot
   * const dStockPropertyPivot = await prisma.dStockPropertyPivot.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends dStockPropertyPivotFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, dStockPropertyPivotFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__dStockPropertyPivotClient<runtime.Types.Result.GetResult<Prisma.$dStockPropertyPivotPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DStockPropertyPivot that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dStockPropertyPivotFindFirstArgs} args - Arguments to find a DStockPropertyPivot
   * @example
   * // Get one DStockPropertyPivot
   * const dStockPropertyPivot = await prisma.dStockPropertyPivot.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends dStockPropertyPivotFindFirstArgs>(args?: Prisma.SelectSubset<T, dStockPropertyPivotFindFirstArgs<ExtArgs>>): Prisma.Prisma__dStockPropertyPivotClient<runtime.Types.Result.GetResult<Prisma.$dStockPropertyPivotPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DStockPropertyPivot that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dStockPropertyPivotFindFirstOrThrowArgs} args - Arguments to find a DStockPropertyPivot
   * @example
   * // Get one DStockPropertyPivot
   * const dStockPropertyPivot = await prisma.dStockPropertyPivot.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends dStockPropertyPivotFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, dStockPropertyPivotFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__dStockPropertyPivotClient<runtime.Types.Result.GetResult<Prisma.$dStockPropertyPivotPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more DStockPropertyPivots that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dStockPropertyPivotFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all DStockPropertyPivots
   * const dStockPropertyPivots = await prisma.dStockPropertyPivot.findMany()
   * 
   * // Get first 10 DStockPropertyPivots
   * const dStockPropertyPivots = await prisma.dStockPropertyPivot.findMany({ take: 10 })
   * 
   * // Only select the `Identifier`
   * const dStockPropertyPivotWithIdentifierOnly = await prisma.dStockPropertyPivot.findMany({ select: { Identifier: true } })
   * 
   */
  findMany<T extends dStockPropertyPivotFindManyArgs>(args?: Prisma.SelectSubset<T, dStockPropertyPivotFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$dStockPropertyPivotPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a DStockPropertyPivot.
   * @param {dStockPropertyPivotCreateArgs} args - Arguments to create a DStockPropertyPivot.
   * @example
   * // Create one DStockPropertyPivot
   * const DStockPropertyPivot = await prisma.dStockPropertyPivot.create({
   *   data: {
   *     // ... data to create a DStockPropertyPivot
   *   }
   * })
   * 
   */
  create<T extends dStockPropertyPivotCreateArgs>(args: Prisma.SelectSubset<T, dStockPropertyPivotCreateArgs<ExtArgs>>): Prisma.Prisma__dStockPropertyPivotClient<runtime.Types.Result.GetResult<Prisma.$dStockPropertyPivotPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many DStockPropertyPivots.
   * @param {dStockPropertyPivotCreateManyArgs} args - Arguments to create many DStockPropertyPivots.
   * @example
   * // Create many DStockPropertyPivots
   * const dStockPropertyPivot = await prisma.dStockPropertyPivot.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends dStockPropertyPivotCreateManyArgs>(args?: Prisma.SelectSubset<T, dStockPropertyPivotCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a DStockPropertyPivot.
   * @param {dStockPropertyPivotDeleteArgs} args - Arguments to delete one DStockPropertyPivot.
   * @example
   * // Delete one DStockPropertyPivot
   * const DStockPropertyPivot = await prisma.dStockPropertyPivot.delete({
   *   where: {
   *     // ... filter to delete one DStockPropertyPivot
   *   }
   * })
   * 
   */
  delete<T extends dStockPropertyPivotDeleteArgs>(args: Prisma.SelectSubset<T, dStockPropertyPivotDeleteArgs<ExtArgs>>): Prisma.Prisma__dStockPropertyPivotClient<runtime.Types.Result.GetResult<Prisma.$dStockPropertyPivotPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one DStockPropertyPivot.
   * @param {dStockPropertyPivotUpdateArgs} args - Arguments to update one DStockPropertyPivot.
   * @example
   * // Update one DStockPropertyPivot
   * const dStockPropertyPivot = await prisma.dStockPropertyPivot.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends dStockPropertyPivotUpdateArgs>(args: Prisma.SelectSubset<T, dStockPropertyPivotUpdateArgs<ExtArgs>>): Prisma.Prisma__dStockPropertyPivotClient<runtime.Types.Result.GetResult<Prisma.$dStockPropertyPivotPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more DStockPropertyPivots.
   * @param {dStockPropertyPivotDeleteManyArgs} args - Arguments to filter DStockPropertyPivots to delete.
   * @example
   * // Delete a few DStockPropertyPivots
   * const { count } = await prisma.dStockPropertyPivot.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends dStockPropertyPivotDeleteManyArgs>(args?: Prisma.SelectSubset<T, dStockPropertyPivotDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DStockPropertyPivots.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dStockPropertyPivotUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many DStockPropertyPivots
   * const dStockPropertyPivot = await prisma.dStockPropertyPivot.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends dStockPropertyPivotUpdateManyArgs>(args: Prisma.SelectSubset<T, dStockPropertyPivotUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one DStockPropertyPivot.
   * @param {dStockPropertyPivotUpsertArgs} args - Arguments to update or create a DStockPropertyPivot.
   * @example
   * // Update or create a DStockPropertyPivot
   * const dStockPropertyPivot = await prisma.dStockPropertyPivot.upsert({
   *   create: {
   *     // ... data to create a DStockPropertyPivot
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the DStockPropertyPivot we want to update
   *   }
   * })
   */
  upsert<T extends dStockPropertyPivotUpsertArgs>(args: Prisma.SelectSubset<T, dStockPropertyPivotUpsertArgs<ExtArgs>>): Prisma.Prisma__dStockPropertyPivotClient<runtime.Types.Result.GetResult<Prisma.$dStockPropertyPivotPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of DStockPropertyPivots.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dStockPropertyPivotCountArgs} args - Arguments to filter DStockPropertyPivots to count.
   * @example
   * // Count the number of DStockPropertyPivots
   * const count = await prisma.dStockPropertyPivot.count({
   *   where: {
   *     // ... the filter for the DStockPropertyPivots we want to count
   *   }
   * })
  **/
  count<T extends dStockPropertyPivotCountArgs>(
    args?: Prisma.Subset<T, dStockPropertyPivotCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DStockPropertyPivotCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a DStockPropertyPivot.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DStockPropertyPivotAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DStockPropertyPivotAggregateArgs>(args: Prisma.Subset<T, DStockPropertyPivotAggregateArgs>): Prisma.PrismaPromise<GetDStockPropertyPivotAggregateType<T>>

  /**
   * Group by DStockPropertyPivot.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dStockPropertyPivotGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends dStockPropertyPivotGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: dStockPropertyPivotGroupByArgs['orderBy'] }
      : { orderBy?: dStockPropertyPivotGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, dStockPropertyPivotGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDStockPropertyPivotGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the dStockPropertyPivot model
 */
readonly fields: dStockPropertyPivotFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for dStockPropertyPivot.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__dStockPropertyPivotClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the dStockPropertyPivot model
 */
export interface dStockPropertyPivotFieldRefs {
  readonly Identifier: Prisma.FieldRef<"dStockPropertyPivot", 'Int'>
  readonly Status: Prisma.FieldRef<"dStockPropertyPivot", 'String'>
  readonly Creation: Prisma.FieldRef<"dStockPropertyPivot", 'DateTime'>
  readonly CreationID: Prisma.FieldRef<"dStockPropertyPivot", 'Int'>
  readonly Maintenance: Prisma.FieldRef<"dStockPropertyPivot", 'DateTime'>
  readonly MaintenanceID: Prisma.FieldRef<"dStockPropertyPivot", 'Int'>
  readonly IdentStock: Prisma.FieldRef<"dStockPropertyPivot", 'Int'>
  readonly Serial: Prisma.FieldRef<"dStockPropertyPivot", 'String'>
  readonly UpdateFlag: Prisma.FieldRef<"dStockPropertyPivot", 'Boolean'>
  readonly IdentStockPropertyGEAR: Prisma.FieldRef<"dStockPropertyPivot", 'Int'>
  readonly IdentStockPropertyGRADE: Prisma.FieldRef<"dStockPropertyPivot", 'Int'>
  readonly IdentStockPropertyCONDITION: Prisma.FieldRef<"dStockPropertyPivot", 'Int'>
  readonly IdentStockPropertyPACKAGE: Prisma.FieldRef<"dStockPropertyPivot", 'Int'>
  readonly IdentStockPropertyBOAT: Prisma.FieldRef<"dStockPropertyPivot", 'Int'>
  readonly IdentStockPropertyUSER: Prisma.FieldRef<"dStockPropertyPivot", 'Int'>
  readonly IdentStockPropertyPORT: Prisma.FieldRef<"dStockPropertyPivot", 'Int'>
  readonly IdentStockPropertyALLERGY: Prisma.FieldRef<"dStockPropertyPivot", 'Int'>
  readonly IdentPropertyGEAR: Prisma.FieldRef<"dStockPropertyPivot", 'Int'>
  readonly IdentPropertyGRADE: Prisma.FieldRef<"dStockPropertyPivot", 'Int'>
  readonly IdentPropertyCONDITION: Prisma.FieldRef<"dStockPropertyPivot", 'Int'>
  readonly IdentPropertyPACKAGE: Prisma.FieldRef<"dStockPropertyPivot", 'Int'>
  readonly IdentPropertyBOAT: Prisma.FieldRef<"dStockPropertyPivot", 'Int'>
  readonly IdentPropertyUSER: Prisma.FieldRef<"dStockPropertyPivot", 'Int'>
  readonly IdentPropertyPORT: Prisma.FieldRef<"dStockPropertyPivot", 'Int'>
  readonly IdentPropertyALLERGY: Prisma.FieldRef<"dStockPropertyPivot", 'Int'>
  readonly NameGEAR: Prisma.FieldRef<"dStockPropertyPivot", 'String'>
  readonly NameGRADE: Prisma.FieldRef<"dStockPropertyPivot", 'String'>
  readonly NameCONDITION: Prisma.FieldRef<"dStockPropertyPivot", 'String'>
  readonly NamePACKAGE: Prisma.FieldRef<"dStockPropertyPivot", 'String'>
  readonly NameBOAT: Prisma.FieldRef<"dStockPropertyPivot", 'String'>
  readonly NameUSER: Prisma.FieldRef<"dStockPropertyPivot", 'String'>
  readonly NamePORT: Prisma.FieldRef<"dStockPropertyPivot", 'String'>
  readonly NameALLERGY: Prisma.FieldRef<"dStockPropertyPivot", 'String'>
  readonly ShortGEAR: Prisma.FieldRef<"dStockPropertyPivot", 'String'>
  readonly ShortGRADE: Prisma.FieldRef<"dStockPropertyPivot", 'String'>
  readonly ShortCONDITION: Prisma.FieldRef<"dStockPropertyPivot", 'String'>
  readonly ShortPACKAGE: Prisma.FieldRef<"dStockPropertyPivot", 'String'>
  readonly ShortBOAT: Prisma.FieldRef<"dStockPropertyPivot", 'String'>
  readonly ShortUSER: Prisma.FieldRef<"dStockPropertyPivot", 'String'>
  readonly ShortPORT: Prisma.FieldRef<"dStockPropertyPivot", 'String'>
  readonly ShortALLERGY: Prisma.FieldRef<"dStockPropertyPivot", 'String'>
  readonly BarcodeGEAR: Prisma.FieldRef<"dStockPropertyPivot", 'String'>
  readonly BarcodeGRADE: Prisma.FieldRef<"dStockPropertyPivot", 'String'>
  readonly BarcodeCONDITION: Prisma.FieldRef<"dStockPropertyPivot", 'String'>
  readonly BarcodePACKAGE: Prisma.FieldRef<"dStockPropertyPivot", 'String'>
  readonly BarcodeBOAT: Prisma.FieldRef<"dStockPropertyPivot", 'String'>
  readonly BarcodeUSER: Prisma.FieldRef<"dStockPropertyPivot", 'String'>
  readonly BarcodePORT: Prisma.FieldRef<"dStockPropertyPivot", 'String'>
  readonly BarcodeALLERGY: Prisma.FieldRef<"dStockPropertyPivot", 'String'>
}
    

// Custom InputTypes
/**
 * dStockPropertyPivot findUnique
 */
export type dStockPropertyPivotFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dStockPropertyPivot
   */
  select?: Prisma.dStockPropertyPivotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dStockPropertyPivot
   */
  omit?: Prisma.dStockPropertyPivotOmit<ExtArgs> | null
  /**
   * Filter, which dStockPropertyPivot to fetch.
   */
  where: Prisma.dStockPropertyPivotWhereUniqueInput
}

/**
 * dStockPropertyPivot findUniqueOrThrow
 */
export type dStockPropertyPivotFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dStockPropertyPivot
   */
  select?: Prisma.dStockPropertyPivotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dStockPropertyPivot
   */
  omit?: Prisma.dStockPropertyPivotOmit<ExtArgs> | null
  /**
   * Filter, which dStockPropertyPivot to fetch.
   */
  where: Prisma.dStockPropertyPivotWhereUniqueInput
}

/**
 * dStockPropertyPivot findFirst
 */
export type dStockPropertyPivotFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dStockPropertyPivot
   */
  select?: Prisma.dStockPropertyPivotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dStockPropertyPivot
   */
  omit?: Prisma.dStockPropertyPivotOmit<ExtArgs> | null
  /**
   * Filter, which dStockPropertyPivot to fetch.
   */
  where?: Prisma.dStockPropertyPivotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of dStockPropertyPivots to fetch.
   */
  orderBy?: Prisma.dStockPropertyPivotOrderByWithRelationInput | Prisma.dStockPropertyPivotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for dStockPropertyPivots.
   */
  cursor?: Prisma.dStockPropertyPivotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` dStockPropertyPivots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` dStockPropertyPivots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of dStockPropertyPivots.
   */
  distinct?: Prisma.DStockPropertyPivotScalarFieldEnum | Prisma.DStockPropertyPivotScalarFieldEnum[]
}

/**
 * dStockPropertyPivot findFirstOrThrow
 */
export type dStockPropertyPivotFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dStockPropertyPivot
   */
  select?: Prisma.dStockPropertyPivotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dStockPropertyPivot
   */
  omit?: Prisma.dStockPropertyPivotOmit<ExtArgs> | null
  /**
   * Filter, which dStockPropertyPivot to fetch.
   */
  where?: Prisma.dStockPropertyPivotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of dStockPropertyPivots to fetch.
   */
  orderBy?: Prisma.dStockPropertyPivotOrderByWithRelationInput | Prisma.dStockPropertyPivotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for dStockPropertyPivots.
   */
  cursor?: Prisma.dStockPropertyPivotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` dStockPropertyPivots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` dStockPropertyPivots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of dStockPropertyPivots.
   */
  distinct?: Prisma.DStockPropertyPivotScalarFieldEnum | Prisma.DStockPropertyPivotScalarFieldEnum[]
}

/**
 * dStockPropertyPivot findMany
 */
export type dStockPropertyPivotFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dStockPropertyPivot
   */
  select?: Prisma.dStockPropertyPivotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dStockPropertyPivot
   */
  omit?: Prisma.dStockPropertyPivotOmit<ExtArgs> | null
  /**
   * Filter, which dStockPropertyPivots to fetch.
   */
  where?: Prisma.dStockPropertyPivotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of dStockPropertyPivots to fetch.
   */
  orderBy?: Prisma.dStockPropertyPivotOrderByWithRelationInput | Prisma.dStockPropertyPivotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing dStockPropertyPivots.
   */
  cursor?: Prisma.dStockPropertyPivotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` dStockPropertyPivots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` dStockPropertyPivots.
   */
  skip?: number
  distinct?: Prisma.DStockPropertyPivotScalarFieldEnum | Prisma.DStockPropertyPivotScalarFieldEnum[]
}

/**
 * dStockPropertyPivot create
 */
export type dStockPropertyPivotCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dStockPropertyPivot
   */
  select?: Prisma.dStockPropertyPivotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dStockPropertyPivot
   */
  omit?: Prisma.dStockPropertyPivotOmit<ExtArgs> | null
  /**
   * The data needed to create a dStockPropertyPivot.
   */
  data?: Prisma.XOR<Prisma.dStockPropertyPivotCreateInput, Prisma.dStockPropertyPivotUncheckedCreateInput>
}

/**
 * dStockPropertyPivot createMany
 */
export type dStockPropertyPivotCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many dStockPropertyPivots.
   */
  data: Prisma.dStockPropertyPivotCreateManyInput | Prisma.dStockPropertyPivotCreateManyInput[]
}

/**
 * dStockPropertyPivot update
 */
export type dStockPropertyPivotUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dStockPropertyPivot
   */
  select?: Prisma.dStockPropertyPivotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dStockPropertyPivot
   */
  omit?: Prisma.dStockPropertyPivotOmit<ExtArgs> | null
  /**
   * The data needed to update a dStockPropertyPivot.
   */
  data: Prisma.XOR<Prisma.dStockPropertyPivotUpdateInput, Prisma.dStockPropertyPivotUncheckedUpdateInput>
  /**
   * Choose, which dStockPropertyPivot to update.
   */
  where: Prisma.dStockPropertyPivotWhereUniqueInput
}

/**
 * dStockPropertyPivot updateMany
 */
export type dStockPropertyPivotUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update dStockPropertyPivots.
   */
  data: Prisma.XOR<Prisma.dStockPropertyPivotUpdateManyMutationInput, Prisma.dStockPropertyPivotUncheckedUpdateManyInput>
  /**
   * Filter which dStockPropertyPivots to update
   */
  where?: Prisma.dStockPropertyPivotWhereInput
  /**
   * Limit how many dStockPropertyPivots to update.
   */
  limit?: number
}

/**
 * dStockPropertyPivot upsert
 */
export type dStockPropertyPivotUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dStockPropertyPivot
   */
  select?: Prisma.dStockPropertyPivotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dStockPropertyPivot
   */
  omit?: Prisma.dStockPropertyPivotOmit<ExtArgs> | null
  /**
   * The filter to search for the dStockPropertyPivot to update in case it exists.
   */
  where: Prisma.dStockPropertyPivotWhereUniqueInput
  /**
   * In case the dStockPropertyPivot found by the `where` argument doesn't exist, create a new dStockPropertyPivot with this data.
   */
  create: Prisma.XOR<Prisma.dStockPropertyPivotCreateInput, Prisma.dStockPropertyPivotUncheckedCreateInput>
  /**
   * In case the dStockPropertyPivot was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.dStockPropertyPivotUpdateInput, Prisma.dStockPropertyPivotUncheckedUpdateInput>
}

/**
 * dStockPropertyPivot delete
 */
export type dStockPropertyPivotDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dStockPropertyPivot
   */
  select?: Prisma.dStockPropertyPivotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dStockPropertyPivot
   */
  omit?: Prisma.dStockPropertyPivotOmit<ExtArgs> | null
  /**
   * Filter which dStockPropertyPivot to delete.
   */
  where: Prisma.dStockPropertyPivotWhereUniqueInput
}

/**
 * dStockPropertyPivot deleteMany
 */
export type dStockPropertyPivotDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which dStockPropertyPivots to delete
   */
  where?: Prisma.dStockPropertyPivotWhereInput
  /**
   * Limit how many dStockPropertyPivots to delete.
   */
  limit?: number
}

/**
 * dStockPropertyPivot without action
 */
export type dStockPropertyPivotDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dStockPropertyPivot
   */
  select?: Prisma.dStockPropertyPivotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dStockPropertyPivot
   */
  omit?: Prisma.dStockPropertyPivotOmit<ExtArgs> | null
}
