
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model Conf_EOQSTOK
 * 
 */
export type Conf_EOQSTOK = Prisma.Conf_EOQSTOKModel
/**
 * Model dAddress
 * 
 */
export type dAddress = Prisma.dAddressModel
/**
 * Model dChannelOrder
 * 
 */
export type dChannelOrder = Prisma.dChannelOrderModel
/**
 * Model dCode
 * 
 */
export type dCode = Prisma.dCodeModel
/**
 * Model dCommand
 * 
 */
export type dCommand = Prisma.dCommandModel
/**
 * Model dControl
 * 
 */
export type dControl = Prisma.dControlModel
/**
 * Model dCustomer
 * 
 */
export type dCustomer = Prisma.dCustomerModel
/**
 * Model dData
 * 
 */
export type dData = Prisma.dDataModel
/**
 * Model dDepth
 * 
 */
export type dDepth = Prisma.dDepthModel
/**
 * Model dERP
 * 
 */
export type dERP = Prisma.dERPModel
/**
 * Model dMeta
 * 
 */
export type dMeta = Prisma.dMetaModel
/**
 * Model dOrder
 * 
 */
export type dOrder = Prisma.dOrderModel
/**
 * Model dPage
 * 
 */
export type dPage = Prisma.dPageModel
/**
 * Model dProduct
 * 
 */
export type dProduct = Prisma.dProductModel
/**
 * Model dProductProperty
 * 
 */
export type dProductProperty = Prisma.dProductPropertyModel
/**
 * Model dProductPropertyPivot
 * 
 */
export type dProductPropertyPivot = Prisma.dProductPropertyPivotModel
/**
 * Model dProperty
 * 
 */
export type dProperty = Prisma.dPropertyModel
/**
 * Model dPurchaseOrder
 * 
 */
export type dPurchaseOrder = Prisma.dPurchaseOrderModel
/**
 * Model dSalesOrder
 * 
 */
export type dSalesOrder = Prisma.dSalesOrderModel
/**
 * Model dStation
 * 
 */
export type dStation = Prisma.dStationModel
/**
 * Model dStock
 * 
 */
export type dStock = Prisma.dStockModel
/**
 * Model dStockAudit
 * 
 */
export type dStockAudit = Prisma.dStockAuditModel
/**
 * Model dStockProperty
 * 
 */
export type dStockProperty = Prisma.dStockPropertyModel
/**
 * Model dStockPropertyPivot
 * 
 */
export type dStockPropertyPivot = Prisma.dStockPropertyPivotModel
/**
 * Model dStorage
 * 
 */
export type dStorage = Prisma.dStorageModel
/**
 * Model dSupplier
 * 
 */
export type dSupplier = Prisma.dSupplierModel
/**
 * Model dSync
 * 
 */
export type dSync = Prisma.dSyncModel
/**
 * Model dText
 * 
 */
export type dText = Prisma.dTextModel
/**
 * Model dTransferOrder
 * 
 */
export type dTransferOrder = Prisma.dTransferOrderModel
/**
 * Model dUser
 * 
 */
export type dUser = Prisma.dUserModel
/**
 * Model dVendor
 * 
 */
export type dVendor = Prisma.dVendorModel
/**
 * Model dWorkOrder
 * 
 */
export type dWorkOrder = Prisma.dWorkOrderModel
/**
 * Model ItemSage
 * 
 */
export type ItemSage = Prisma.ItemSageModel
/**
 * Model SageName
 * 
 */
export type SageName = Prisma.SageNameModel
/**
 * Model SageVendor
 * 
 */
export type SageVendor = Prisma.SageVendorModel
/**
 * Model sessions
 * 
 */
export type sessions = Prisma.sessionsModel
/**
 * Model StockCremora
 * 
 */
export type StockCremora = Prisma.StockCremoraModel
/**
 * Model sysdiagrams
 * 
 */
export type sysdiagrams = Prisma.sysdiagramsModel
/**
 * Model tProperty
 * 
 */
export type tProperty = Prisma.tPropertyModel
